// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: backend/proto/backend.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/go-micro/v2/api"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for Backend service

func NewBackendEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for Backend service

type BackendService interface {
	CreateBackend(ctx context.Context, in *CreateBackendRequest, opts ...client.CallOption) (*CreateBackendResponse, error)
	GetBackend(ctx context.Context, in *GetBackendRequest, opts ...client.CallOption) (*GetBackendResponse, error)
	ListBackend(ctx context.Context, in *ListBackendRequest, opts ...client.CallOption) (*ListBackendResponse, error)
	UpdateBackend(ctx context.Context, in *UpdateBackendRequest, opts ...client.CallOption) (*UpdateBackendResponse, error)
	DeleteBackend(ctx context.Context, in *DeleteBackendRequest, opts ...client.CallOption) (*DeleteBackendResponse, error)
	ListType(ctx context.Context, in *ListTypeRequest, opts ...client.CallOption) (*ListTypeResponse, error)
	CreateTier(ctx context.Context, in *CreateTierRequest, opts ...client.CallOption) (*CreateTierResponse, error)
	GetTier(ctx context.Context, in *GetTierRequest, opts ...client.CallOption) (*GetTierResponse, error)
	ListTiers(ctx context.Context, in *ListTierRequest, opts ...client.CallOption) (*ListTierResponse, error)
	UpdateTier(ctx context.Context, in *UpdateTierRequest, opts ...client.CallOption) (*UpdateTierResponse, error)
	DeleteTier(ctx context.Context, in *DeleteTierRequest, opts ...client.CallOption) (*DeleteTierResponse, error)
}

type backendService struct {
	c    client.Client
	name string
}

func NewBackendService(name string, c client.Client) BackendService {
	return &backendService{
		c:    c,
		name: name,
	}
}

func (c *backendService) CreateBackend(ctx context.Context, in *CreateBackendRequest, opts ...client.CallOption) (*CreateBackendResponse, error) {
	req := c.c.NewRequest(c.name, "Backend.CreateBackend", in)
	out := new(CreateBackendResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backendService) GetBackend(ctx context.Context, in *GetBackendRequest, opts ...client.CallOption) (*GetBackendResponse, error) {
	req := c.c.NewRequest(c.name, "Backend.GetBackend", in)
	out := new(GetBackendResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backendService) ListBackend(ctx context.Context, in *ListBackendRequest, opts ...client.CallOption) (*ListBackendResponse, error) {
	req := c.c.NewRequest(c.name, "Backend.ListBackend", in)
	out := new(ListBackendResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backendService) UpdateBackend(ctx context.Context, in *UpdateBackendRequest, opts ...client.CallOption) (*UpdateBackendResponse, error) {
	req := c.c.NewRequest(c.name, "Backend.UpdateBackend", in)
	out := new(UpdateBackendResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backendService) DeleteBackend(ctx context.Context, in *DeleteBackendRequest, opts ...client.CallOption) (*DeleteBackendResponse, error) {
	req := c.c.NewRequest(c.name, "Backend.DeleteBackend", in)
	out := new(DeleteBackendResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backendService) ListType(ctx context.Context, in *ListTypeRequest, opts ...client.CallOption) (*ListTypeResponse, error) {
	req := c.c.NewRequest(c.name, "Backend.ListType", in)
	out := new(ListTypeResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backendService) CreateTier(ctx context.Context, in *CreateTierRequest, opts ...client.CallOption) (*CreateTierResponse, error) {
	req := c.c.NewRequest(c.name, "Backend.CreateTier", in)
	out := new(CreateTierResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backendService) GetTier(ctx context.Context, in *GetTierRequest, opts ...client.CallOption) (*GetTierResponse, error) {
	req := c.c.NewRequest(c.name, "Backend.GetTier", in)
	out := new(GetTierResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backendService) ListTiers(ctx context.Context, in *ListTierRequest, opts ...client.CallOption) (*ListTierResponse, error) {
	req := c.c.NewRequest(c.name, "Backend.ListTiers", in)
	out := new(ListTierResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backendService) UpdateTier(ctx context.Context, in *UpdateTierRequest, opts ...client.CallOption) (*UpdateTierResponse, error) {
	req := c.c.NewRequest(c.name, "Backend.UpdateTier", in)
	out := new(UpdateTierResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backendService) DeleteTier(ctx context.Context, in *DeleteTierRequest, opts ...client.CallOption) (*DeleteTierResponse, error) {
	req := c.c.NewRequest(c.name, "Backend.DeleteTier", in)
	out := new(DeleteTierResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Backend service

type BackendHandler interface {
	CreateBackend(context.Context, *CreateBackendRequest, *CreateBackendResponse) error
	GetBackend(context.Context, *GetBackendRequest, *GetBackendResponse) error
	ListBackend(context.Context, *ListBackendRequest, *ListBackendResponse) error
	UpdateBackend(context.Context, *UpdateBackendRequest, *UpdateBackendResponse) error
	DeleteBackend(context.Context, *DeleteBackendRequest, *DeleteBackendResponse) error
	ListType(context.Context, *ListTypeRequest, *ListTypeResponse) error
	CreateTier(context.Context, *CreateTierRequest, *CreateTierResponse) error
	GetTier(context.Context, *GetTierRequest, *GetTierResponse) error
	ListTiers(context.Context, *ListTierRequest, *ListTierResponse) error
	UpdateTier(context.Context, *UpdateTierRequest, *UpdateTierResponse) error
	DeleteTier(context.Context, *DeleteTierRequest, *DeleteTierResponse) error
}

func RegisterBackendHandler(s server.Server, hdlr BackendHandler, opts ...server.HandlerOption) error {
	type backend interface {
		CreateBackend(ctx context.Context, in *CreateBackendRequest, out *CreateBackendResponse) error
		GetBackend(ctx context.Context, in *GetBackendRequest, out *GetBackendResponse) error
		ListBackend(ctx context.Context, in *ListBackendRequest, out *ListBackendResponse) error
		UpdateBackend(ctx context.Context, in *UpdateBackendRequest, out *UpdateBackendResponse) error
		DeleteBackend(ctx context.Context, in *DeleteBackendRequest, out *DeleteBackendResponse) error
		ListType(ctx context.Context, in *ListTypeRequest, out *ListTypeResponse) error
		CreateTier(ctx context.Context, in *CreateTierRequest, out *CreateTierResponse) error
		GetTier(ctx context.Context, in *GetTierRequest, out *GetTierResponse) error
		ListTiers(ctx context.Context, in *ListTierRequest, out *ListTierResponse) error
		UpdateTier(ctx context.Context, in *UpdateTierRequest, out *UpdateTierResponse) error
		DeleteTier(ctx context.Context, in *DeleteTierRequest, out *DeleteTierResponse) error
	}
	type Backend struct {
		backend
	}
	h := &backendHandler{hdlr}
	return s.Handle(s.NewHandler(&Backend{h}, opts...))
}

type backendHandler struct {
	BackendHandler
}

func (h *backendHandler) CreateBackend(ctx context.Context, in *CreateBackendRequest, out *CreateBackendResponse) error {
	return h.BackendHandler.CreateBackend(ctx, in, out)
}

func (h *backendHandler) GetBackend(ctx context.Context, in *GetBackendRequest, out *GetBackendResponse) error {
	return h.BackendHandler.GetBackend(ctx, in, out)
}

func (h *backendHandler) ListBackend(ctx context.Context, in *ListBackendRequest, out *ListBackendResponse) error {
	return h.BackendHandler.ListBackend(ctx, in, out)
}

func (h *backendHandler) UpdateBackend(ctx context.Context, in *UpdateBackendRequest, out *UpdateBackendResponse) error {
	return h.BackendHandler.UpdateBackend(ctx, in, out)
}

func (h *backendHandler) DeleteBackend(ctx context.Context, in *DeleteBackendRequest, out *DeleteBackendResponse) error {
	return h.BackendHandler.DeleteBackend(ctx, in, out)
}

func (h *backendHandler) ListType(ctx context.Context, in *ListTypeRequest, out *ListTypeResponse) error {
	return h.BackendHandler.ListType(ctx, in, out)
}

func (h *backendHandler) CreateTier(ctx context.Context, in *CreateTierRequest, out *CreateTierResponse) error {
	return h.BackendHandler.CreateTier(ctx, in, out)
}

func (h *backendHandler) GetTier(ctx context.Context, in *GetTierRequest, out *GetTierResponse) error {
	return h.BackendHandler.GetTier(ctx, in, out)
}

func (h *backendHandler) ListTiers(ctx context.Context, in *ListTierRequest, out *ListTierResponse) error {
	return h.BackendHandler.ListTiers(ctx, in, out)
}

func (h *backendHandler) UpdateTier(ctx context.Context, in *UpdateTierRequest, out *UpdateTierResponse) error {
	return h.BackendHandler.UpdateTier(ctx, in, out)
}

func (h *backendHandler) DeleteTier(ctx context.Context, in *DeleteTierRequest, out *DeleteTierResponse) error {
	return h.BackendHandler.DeleteTier(ctx, in, out)
}
