// Code generated by protoc-gen-go. DO NOT EDIT.
// source: backend.proto

package backend

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type GetBackendRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetBackendRequest) Reset()         { *m = GetBackendRequest{} }
func (m *GetBackendRequest) String() string { return proto.CompactTextString(m) }
func (*GetBackendRequest) ProtoMessage()    {}
func (*GetBackendRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_backend_b7754cea5cdc26f4, []int{0}
}
func (m *GetBackendRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBackendRequest.Unmarshal(m, b)
}
func (m *GetBackendRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBackendRequest.Marshal(b, m, deterministic)
}
func (dst *GetBackendRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBackendRequest.Merge(dst, src)
}
func (m *GetBackendRequest) XXX_Size() int {
	return xxx_messageInfo_GetBackendRequest.Size(m)
}
func (m *GetBackendRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBackendRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetBackendRequest proto.InternalMessageInfo

func (m *GetBackendRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type GetBackendResponse struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetBackendResponse) Reset()         { *m = GetBackendResponse{} }
func (m *GetBackendResponse) String() string { return proto.CompactTextString(m) }
func (*GetBackendResponse) ProtoMessage()    {}
func (*GetBackendResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_backend_b7754cea5cdc26f4, []int{1}
}
func (m *GetBackendResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBackendResponse.Unmarshal(m, b)
}
func (m *GetBackendResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBackendResponse.Marshal(b, m, deterministic)
}
func (dst *GetBackendResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBackendResponse.Merge(dst, src)
}
func (m *GetBackendResponse) XXX_Size() int {
	return xxx_messageInfo_GetBackendResponse.Size(m)
}
func (m *GetBackendResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBackendResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetBackendResponse proto.InternalMessageInfo

func (m *GetBackendResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *GetBackendResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func init() {
	proto.RegisterType((*GetBackendRequest)(nil), "GetBackendRequest")
	proto.RegisterType((*GetBackendResponse)(nil), "GetBackendResponse")
}

func init() { proto.RegisterFile("backend.proto", fileDescriptor_backend_b7754cea5cdc26f4) }

var fileDescriptor_backend_b7754cea5cdc26f4 = []byte{
	// 130 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4d, 0x4a, 0x4c, 0xce,
	0x4e, 0xcd, 0x4b, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x57, 0x52, 0xe6, 0x12, 0x74, 0x4f, 0x2d,
	0x71, 0x82, 0x88, 0x05, 0xa5, 0x16, 0x96, 0xa6, 0x16, 0x97, 0x08, 0xf1, 0x71, 0x31, 0x65, 0xa6,
	0x48, 0x30, 0x2a, 0x30, 0x6a, 0x70, 0x06, 0x31, 0x65, 0xa6, 0x28, 0x59, 0x70, 0x09, 0x21, 0x2b,
	0x2a, 0x2e, 0xc8, 0xcf, 0x2b, 0x4e, 0x45, 0x57, 0x25, 0x24, 0xc4, 0xc5, 0x92, 0x97, 0x98, 0x9b,
	0x2a, 0xc1, 0x04, 0x16, 0x01, 0xb3, 0x8d, 0x9c, 0xb8, 0xd8, 0xa1, 0xda, 0x84, 0xcc, 0xb9, 0xb8,
	0x10, 0x86, 0x08, 0x09, 0xe9, 0x61, 0x58, 0x2b, 0x25, 0xac, 0x87, 0x69, 0x8b, 0x12, 0x43, 0x12,
	0x1b, 0xd8, 0xa5, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0xd2, 0x36, 0xf6, 0x35, 0xba, 0x00,
	0x00, 0x00,
}
