// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: backend/proto/backend.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/go-micro/v2/api"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for Backend service

func NewBackendEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for Backend service

type BackendService interface {
	CreateBackend(ctx context.Context, in *CreateBackendRequest, opts ...client.CallOption) (*CreateBackendResponse, error)
	GetBackend(ctx context.Context, in *GetBackendRequest, opts ...client.CallOption) (*GetBackendResponse, error)
	ListBackend(ctx context.Context, in *ListBackendRequest, opts ...client.CallOption) (*ListBackendResponse, error)
	UpdateBackend(ctx context.Context, in *UpdateBackendRequest, opts ...client.CallOption) (*UpdateBackendResponse, error)
	DeleteBackend(ctx context.Context, in *DeleteBackendRequest, opts ...client.CallOption) (*DeleteBackendResponse, error)
	ListType(ctx context.Context, in *ListTypeRequest, opts ...client.CallOption) (*ListTypeResponse, error)
	CreateSsp(ctx context.Context, in *CreateSspRequest, opts ...client.CallOption) (*CreateSspResponse, error)
	GetSsp(ctx context.Context, in *GetSspRequest, opts ...client.CallOption) (*GetSspResponse, error)
	ListSsps(ctx context.Context, in *ListSspRequest, opts ...client.CallOption) (*ListSspResponse, error)
	UpdateSsp(ctx context.Context, in *UpdateSspRequest, opts ...client.CallOption) (*UpdateSspResponse, error)
	DeleteSsp(ctx context.Context, in *DeleteSspRequest, opts ...client.CallOption) (*DeleteSspResponse, error)
}

type backendService struct {
	c    client.Client
	name string
}

func NewBackendService(name string, c client.Client) BackendService {
	return &backendService{
		c:    c,
		name: name,
	}
}

func (c *backendService) CreateBackend(ctx context.Context, in *CreateBackendRequest, opts ...client.CallOption) (*CreateBackendResponse, error) {
	req := c.c.NewRequest(c.name, "Backend.CreateBackend", in)
	out := new(CreateBackendResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backendService) GetBackend(ctx context.Context, in *GetBackendRequest, opts ...client.CallOption) (*GetBackendResponse, error) {
	req := c.c.NewRequest(c.name, "Backend.GetBackend", in)
	out := new(GetBackendResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backendService) ListBackend(ctx context.Context, in *ListBackendRequest, opts ...client.CallOption) (*ListBackendResponse, error) {
	req := c.c.NewRequest(c.name, "Backend.ListBackend", in)
	out := new(ListBackendResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backendService) UpdateBackend(ctx context.Context, in *UpdateBackendRequest, opts ...client.CallOption) (*UpdateBackendResponse, error) {
	req := c.c.NewRequest(c.name, "Backend.UpdateBackend", in)
	out := new(UpdateBackendResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backendService) DeleteBackend(ctx context.Context, in *DeleteBackendRequest, opts ...client.CallOption) (*DeleteBackendResponse, error) {
	req := c.c.NewRequest(c.name, "Backend.DeleteBackend", in)
	out := new(DeleteBackendResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backendService) ListType(ctx context.Context, in *ListTypeRequest, opts ...client.CallOption) (*ListTypeResponse, error) {
	req := c.c.NewRequest(c.name, "Backend.ListType", in)
	out := new(ListTypeResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backendService) CreateSsp(ctx context.Context, in *CreateSspRequest, opts ...client.CallOption) (*CreateSspResponse, error) {
	req := c.c.NewRequest(c.name, "Backend.CreateSsp", in)
	out := new(CreateSspResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backendService) GetSsp(ctx context.Context, in *GetSspRequest, opts ...client.CallOption) (*GetSspResponse, error) {
	req := c.c.NewRequest(c.name, "Backend.GetSsp", in)
	out := new(GetSspResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backendService) ListSsps(ctx context.Context, in *ListSspRequest, opts ...client.CallOption) (*ListSspResponse, error) {
	req := c.c.NewRequest(c.name, "Backend.ListSsps", in)
	out := new(ListSspResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backendService) UpdateSsp(ctx context.Context, in *UpdateSspRequest, opts ...client.CallOption) (*UpdateSspResponse, error) {
	req := c.c.NewRequest(c.name, "Backend.UpdateSsp", in)
	out := new(UpdateSspResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backendService) DeleteSsp(ctx context.Context, in *DeleteSspRequest, opts ...client.CallOption) (*DeleteSspResponse, error) {
	req := c.c.NewRequest(c.name, "Backend.DeleteSsp", in)
	out := new(DeleteSspResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Backend service

type BackendHandler interface {
	CreateBackend(context.Context, *CreateBackendRequest, *CreateBackendResponse) error
	GetBackend(context.Context, *GetBackendRequest, *GetBackendResponse) error
	ListBackend(context.Context, *ListBackendRequest, *ListBackendResponse) error
	UpdateBackend(context.Context, *UpdateBackendRequest, *UpdateBackendResponse) error
	DeleteBackend(context.Context, *DeleteBackendRequest, *DeleteBackendResponse) error
	ListType(context.Context, *ListTypeRequest, *ListTypeResponse) error
	CreateSsp(context.Context, *CreateSspRequest, *CreateSspResponse) error
	GetSsp(context.Context, *GetSspRequest, *GetSspResponse) error
	ListSsps(context.Context, *ListSspRequest, *ListSspResponse) error
	UpdateSsp(context.Context, *UpdateSspRequest, *UpdateSspResponse) error
	DeleteSsp(context.Context, *DeleteSspRequest, *DeleteSspResponse) error
}

func RegisterBackendHandler(s server.Server, hdlr BackendHandler, opts ...server.HandlerOption) error {
	type backend interface {
		CreateBackend(ctx context.Context, in *CreateBackendRequest, out *CreateBackendResponse) error
		GetBackend(ctx context.Context, in *GetBackendRequest, out *GetBackendResponse) error
		ListBackend(ctx context.Context, in *ListBackendRequest, out *ListBackendResponse) error
		UpdateBackend(ctx context.Context, in *UpdateBackendRequest, out *UpdateBackendResponse) error
		DeleteBackend(ctx context.Context, in *DeleteBackendRequest, out *DeleteBackendResponse) error
		ListType(ctx context.Context, in *ListTypeRequest, out *ListTypeResponse) error
		CreateSsp(ctx context.Context, in *CreateSspRequest, out *CreateSspResponse) error
		GetSsp(ctx context.Context, in *GetSspRequest, out *GetSspResponse) error
		ListSsps(ctx context.Context, in *ListSspRequest, out *ListSspResponse) error
		UpdateSsp(ctx context.Context, in *UpdateSspRequest, out *UpdateSspResponse) error
		DeleteSsp(ctx context.Context, in *DeleteSspRequest, out *DeleteSspResponse) error
	}
	type Backend struct {
		backend
	}
	h := &backendHandler{hdlr}
	return s.Handle(s.NewHandler(&Backend{h}, opts...))
}

type backendHandler struct {
	BackendHandler
}

func (h *backendHandler) CreateBackend(ctx context.Context, in *CreateBackendRequest, out *CreateBackendResponse) error {
	return h.BackendHandler.CreateBackend(ctx, in, out)
}

func (h *backendHandler) GetBackend(ctx context.Context, in *GetBackendRequest, out *GetBackendResponse) error {
	return h.BackendHandler.GetBackend(ctx, in, out)
}

func (h *backendHandler) ListBackend(ctx context.Context, in *ListBackendRequest, out *ListBackendResponse) error {
	return h.BackendHandler.ListBackend(ctx, in, out)
}

func (h *backendHandler) UpdateBackend(ctx context.Context, in *UpdateBackendRequest, out *UpdateBackendResponse) error {
	return h.BackendHandler.UpdateBackend(ctx, in, out)
}

func (h *backendHandler) DeleteBackend(ctx context.Context, in *DeleteBackendRequest, out *DeleteBackendResponse) error {
	return h.BackendHandler.DeleteBackend(ctx, in, out)
}

func (h *backendHandler) ListType(ctx context.Context, in *ListTypeRequest, out *ListTypeResponse) error {
	return h.BackendHandler.ListType(ctx, in, out)
}

func (h *backendHandler) CreateSsp(ctx context.Context, in *CreateSspRequest, out *CreateSspResponse) error {
	return h.BackendHandler.CreateSsp(ctx, in, out)
}

func (h *backendHandler) GetSsp(ctx context.Context, in *GetSspRequest, out *GetSspResponse) error {
	return h.BackendHandler.GetSsp(ctx, in, out)
}

func (h *backendHandler) ListSsps(ctx context.Context, in *ListSspRequest, out *ListSspResponse) error {
	return h.BackendHandler.ListSsps(ctx, in, out)
}

func (h *backendHandler) UpdateSsp(ctx context.Context, in *UpdateSspRequest, out *UpdateSspResponse) error {
	return h.BackendHandler.UpdateSsp(ctx, in, out)
}

func (h *backendHandler) DeleteSsp(ctx context.Context, in *DeleteSspRequest, out *DeleteSspResponse) error {
	return h.BackendHandler.DeleteSsp(ctx, in, out)
}
