#!/bin/bash

# Copyright 2019 The soda Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

BASE_DIR=$(dirname "$PWD") 
apt-get update && apt-get install -y git make curl wget libltdl7 libseccomp2 libffi-dev gawk
wget https://storage.googleapis.com/golang/go1.12.1.linux-amd64.tar.gz
tar -C /usr/local -xzf go1.12.1.linux-amd64.tar.gz
echo 'export PATH=$PATH:/usr/local/go/bin' >> /etc/profile
echo 'export GOPATH=$HOME/gopath' >> /etc/profile
source /etc/profile
cd $HOME
mkdir -p gopath/src/github.com/soda/multi-cloud
cd gopath/src/github.com/soda/multi-cloud
cp -r ${BASE_DIR}/* .
make docker
cp datamover/datamover ${BASE_DIR}/datamover
