#!/bin/bash

# Copyright 2020 The SODA Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -o errexit
# Keep track of the script directory
TOP_DIR=$(cd $(dirname "$0") && pwd)
# soda Root directory
soda_DIR=$(cd $TOP_DIR/../.. && pwd)

split_line(){
    echo "================================================================================================"
    echo $*
    echo "================================================================================================"
}

# Start unit test.
split_line "Start unit test"
# api tests
go test -v github.com/soda/multi-cloud/api/pkg/utils/... -cover
go test -v github.com/soda/multi-cloud/api/pkg/policy/... -cover
#block test
go test -v github.com/soda/multi-cloud/block/pkg/... -cover
#file and backend tests
go test -v github.com/soda/multi-cloud/file/pkg/service/... -cover
go test -v github.com/soda/multi-cloud/backend/pkg/service/... -cover

