// Code generated by protoc-gen-go. DO NOT EDIT.
// source: dataflow.proto

/*
Package dataflow is a generated protocol buffer package.

It is generated from these files:
	dataflow.proto

It has these top-level messages:
	Schedule
	Policy
	GetPolicyRequest
	GetPolicyResponse
	CreatePolicyRequest
	CreatePolicyResponse
	UpdatePolicyRequest
	UpdatePolicyResponse
	DeletePolicyRequest
	DeletePolicyResponse
	KV
	Filter
	Connector
	Plan
	CreatePlanRequest
	CreatePlanResponse
	GetPlanRequest
	GetPlanResponse
	UpdatePlanRequest
	UpdatePlanResponse
	DeletePlanRequest
	DeletePlanResponse
	RunPlanRequest
	RunPlanResponse
	Job
	GetJobRequest
	GetJobResponse
*/
package dataflow

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Schedule struct {
	Type             string   `protobuf:"bytes,1,opt,name=type" json:"type,omitempty"`
	Days             []string `protobuf:"bytes,2,rep,name=days" json:"days,omitempty"`
	TimePoint        string   `protobuf:"bytes,3,opt,name=time_point,json=timePoint" json:"time_point,omitempty"`
	TiggerProperties string   `protobuf:"bytes,4,opt,name=tigger_properties,json=tiggerProperties" json:"tigger_properties,omitempty"`
}

func (m *Schedule) Reset()                    { *m = Schedule{} }
func (m *Schedule) String() string            { return proto.CompactTextString(m) }
func (*Schedule) ProtoMessage()               {}
func (*Schedule) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Schedule) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Schedule) GetDays() []string {
	if m != nil {
		return m.Days
	}
	return nil
}

func (m *Schedule) GetTimePoint() string {
	if m != nil {
		return m.TimePoint
	}
	return ""
}

func (m *Schedule) GetTiggerProperties() string {
	if m != nil {
		return m.TiggerProperties
	}
	return ""
}

type Policy struct {
	Id          string    `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Name        string    `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Tenant      string    `protobuf:"bytes,3,opt,name=tenant" json:"tenant,omitempty"`
	Description string    `protobuf:"bytes,4,opt,name=description" json:"description,omitempty"`
	Schedule    *Schedule `protobuf:"bytes,5,opt,name=schedule" json:"schedule,omitempty"`
}

func (m *Policy) Reset()                    { *m = Policy{} }
func (m *Policy) String() string            { return proto.CompactTextString(m) }
func (*Policy) ProtoMessage()               {}
func (*Policy) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Policy) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Policy) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Policy) GetTenant() string {
	if m != nil {
		return m.Tenant
	}
	return ""
}

func (m *Policy) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Policy) GetSchedule() *Schedule {
	if m != nil {
		return m.Schedule
	}
	return nil
}

type GetPolicyRequest struct {
	Name   string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Tenant string `protobuf:"bytes,2,opt,name=tenant" json:"tenant,omitempty"`
}

func (m *GetPolicyRequest) Reset()                    { *m = GetPolicyRequest{} }
func (m *GetPolicyRequest) String() string            { return proto.CompactTextString(m) }
func (*GetPolicyRequest) ProtoMessage()               {}
func (*GetPolicyRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *GetPolicyRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *GetPolicyRequest) GetTenant() string {
	if m != nil {
		return m.Tenant
	}
	return ""
}

type GetPolicyResponse struct {
	Err  string    `protobuf:"bytes,1,opt,name=err" json:"err,omitempty"`
	Pols []*Policy `protobuf:"bytes,2,rep,name=pols" json:"pols,omitempty"`
}

func (m *GetPolicyResponse) Reset()                    { *m = GetPolicyResponse{} }
func (m *GetPolicyResponse) String() string            { return proto.CompactTextString(m) }
func (*GetPolicyResponse) ProtoMessage()               {}
func (*GetPolicyResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *GetPolicyResponse) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

func (m *GetPolicyResponse) GetPols() []*Policy {
	if m != nil {
		return m.Pols
	}
	return nil
}

type CreatePolicyRequest struct {
	Pol *Policy `protobuf:"bytes,1,opt,name=pol" json:"pol,omitempty"`
}

func (m *CreatePolicyRequest) Reset()                    { *m = CreatePolicyRequest{} }
func (m *CreatePolicyRequest) String() string            { return proto.CompactTextString(m) }
func (*CreatePolicyRequest) ProtoMessage()               {}
func (*CreatePolicyRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *CreatePolicyRequest) GetPol() *Policy {
	if m != nil {
		return m.Pol
	}
	return nil
}

type CreatePolicyResponse struct {
	Err   string `protobuf:"bytes,1,opt,name=err" json:"err,omitempty"`
	PolId string `protobuf:"bytes,2,opt,name=polId" json:"polId,omitempty"`
}

func (m *CreatePolicyResponse) Reset()                    { *m = CreatePolicyResponse{} }
func (m *CreatePolicyResponse) String() string            { return proto.CompactTextString(m) }
func (*CreatePolicyResponse) ProtoMessage()               {}
func (*CreatePolicyResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *CreatePolicyResponse) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

func (m *CreatePolicyResponse) GetPolId() string {
	if m != nil {
		return m.PolId
	}
	return ""
}

type UpdatePolicyRequest struct {
	Pol *Policy `protobuf:"bytes,1,opt,name=pol" json:"pol,omitempty"`
}

func (m *UpdatePolicyRequest) Reset()                    { *m = UpdatePolicyRequest{} }
func (m *UpdatePolicyRequest) String() string            { return proto.CompactTextString(m) }
func (*UpdatePolicyRequest) ProtoMessage()               {}
func (*UpdatePolicyRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *UpdatePolicyRequest) GetPol() *Policy {
	if m != nil {
		return m.Pol
	}
	return nil
}

type UpdatePolicyResponse struct {
	Err   string `protobuf:"bytes,1,opt,name=err" json:"err,omitempty"`
	PolId string `protobuf:"bytes,2,opt,name=polId" json:"polId,omitempty"`
}

func (m *UpdatePolicyResponse) Reset()                    { *m = UpdatePolicyResponse{} }
func (m *UpdatePolicyResponse) String() string            { return proto.CompactTextString(m) }
func (*UpdatePolicyResponse) ProtoMessage()               {}
func (*UpdatePolicyResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *UpdatePolicyResponse) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

func (m *UpdatePolicyResponse) GetPolId() string {
	if m != nil {
		return m.PolId
	}
	return ""
}

type DeletePolicyRequest struct {
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (m *DeletePolicyRequest) Reset()                    { *m = DeletePolicyRequest{} }
func (m *DeletePolicyRequest) String() string            { return proto.CompactTextString(m) }
func (*DeletePolicyRequest) ProtoMessage()               {}
func (*DeletePolicyRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *DeletePolicyRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type DeletePolicyResponse struct {
	Err string `protobuf:"bytes,1,opt,name=err" json:"err,omitempty"`
}

func (m *DeletePolicyResponse) Reset()                    { *m = DeletePolicyResponse{} }
func (m *DeletePolicyResponse) String() string            { return proto.CompactTextString(m) }
func (*DeletePolicyResponse) ProtoMessage()               {}
func (*DeletePolicyResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *DeletePolicyResponse) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

type KV struct {
	Key   string `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
	Value string `protobuf:"bytes,2,opt,name=value" json:"value,omitempty"`
}

func (m *KV) Reset()                    { *m = KV{} }
func (m *KV) String() string            { return proto.CompactTextString(m) }
func (*KV) ProtoMessage()               {}
func (*KV) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *KV) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *KV) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type Filter struct {
	Prefix string `protobuf:"bytes,1,opt,name=prefix" json:"prefix,omitempty"`
	Tag    []*KV  `protobuf:"bytes,2,rep,name=tag" json:"tag,omitempty"`
}

func (m *Filter) Reset()                    { *m = Filter{} }
func (m *Filter) String() string            { return proto.CompactTextString(m) }
func (*Filter) ProtoMessage()               {}
func (*Filter) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *Filter) GetPrefix() string {
	if m != nil {
		return m.Prefix
	}
	return ""
}

func (m *Filter) GetTag() []*KV {
	if m != nil {
		return m.Tag
	}
	return nil
}

type Connector struct {
	StorType   string `protobuf:"bytes,1,opt,name=storType" json:"storType,omitempty"`
	BucketName string `protobuf:"bytes,2,opt,name=bucketName" json:"bucketName,omitempty"`
	ConnConfig []*KV  `protobuf:"bytes,3,rep,name=connConfig" json:"connConfig,omitempty"`
}

func (m *Connector) Reset()                    { *m = Connector{} }
func (m *Connector) String() string            { return proto.CompactTextString(m) }
func (*Connector) ProtoMessage()               {}
func (*Connector) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *Connector) GetStorType() string {
	if m != nil {
		return m.StorType
	}
	return ""
}

func (m *Connector) GetBucketName() string {
	if m != nil {
		return m.BucketName
	}
	return ""
}

func (m *Connector) GetConnConfig() []*KV {
	if m != nil {
		return m.ConnConfig
	}
	return nil
}

type Plan struct {
	Id           string     `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Name         string     `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Description  string     `protobuf:"bytes,3,opt,name=description" json:"description,omitempty"`
	Type         string     `protobuf:"bytes,4,opt,name=type" json:"type,omitempty"`
	PolicyId     string     `protobuf:"bytes,5,opt,name=policyId" json:"policyId,omitempty"`
	PolicyName   string     `protobuf:"bytes,6,opt,name=policyName" json:"policyName,omitempty"`
	SourceConn   *Connector `protobuf:"bytes,7,opt,name=sourceConn" json:"sourceConn,omitempty"`
	DestConn     *Connector `protobuf:"bytes,8,opt,name=destConn" json:"destConn,omitempty"`
	Filt         *Filter    `protobuf:"bytes,9,opt,name=filt" json:"filt,omitempty"`
	OverWrite    bool       `protobuf:"varint,10,opt,name=overWrite" json:"overWrite,omitempty"`
	RemainSource bool       `protobuf:"varint,11,opt,name=remainSource" json:"remainSource,omitempty"`
	Tenant       string     `protobuf:"bytes,12,opt,name=tenant" json:"tenant,omitempty"`
}

func (m *Plan) Reset()                    { *m = Plan{} }
func (m *Plan) String() string            { return proto.CompactTextString(m) }
func (*Plan) ProtoMessage()               {}
func (*Plan) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

func (m *Plan) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Plan) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Plan) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Plan) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Plan) GetPolicyId() string {
	if m != nil {
		return m.PolicyId
	}
	return ""
}

func (m *Plan) GetPolicyName() string {
	if m != nil {
		return m.PolicyName
	}
	return ""
}

func (m *Plan) GetSourceConn() *Connector {
	if m != nil {
		return m.SourceConn
	}
	return nil
}

func (m *Plan) GetDestConn() *Connector {
	if m != nil {
		return m.DestConn
	}
	return nil
}

func (m *Plan) GetFilt() *Filter {
	if m != nil {
		return m.Filt
	}
	return nil
}

func (m *Plan) GetOverWrite() bool {
	if m != nil {
		return m.OverWrite
	}
	return false
}

func (m *Plan) GetRemainSource() bool {
	if m != nil {
		return m.RemainSource
	}
	return false
}

func (m *Plan) GetTenant() string {
	if m != nil {
		return m.Tenant
	}
	return ""
}

type CreatePlanRequest struct {
	Plan   *Plan  `protobuf:"bytes,1,opt,name=plan" json:"plan,omitempty"`
	Tenant string `protobuf:"bytes,2,opt,name=tenant" json:"tenant,omitempty"`
}

func (m *CreatePlanRequest) Reset()                    { *m = CreatePlanRequest{} }
func (m *CreatePlanRequest) String() string            { return proto.CompactTextString(m) }
func (*CreatePlanRequest) ProtoMessage()               {}
func (*CreatePlanRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

func (m *CreatePlanRequest) GetPlan() *Plan {
	if m != nil {
		return m.Plan
	}
	return nil
}

func (m *CreatePlanRequest) GetTenant() string {
	if m != nil {
		return m.Tenant
	}
	return ""
}

type CreatePlanResponse struct {
	Err    string `protobuf:"bytes,1,opt,name=err" json:"err,omitempty"`
	PlanId string `protobuf:"bytes,2,opt,name=planId" json:"planId,omitempty"`
}

func (m *CreatePlanResponse) Reset()                    { *m = CreatePlanResponse{} }
func (m *CreatePlanResponse) String() string            { return proto.CompactTextString(m) }
func (*CreatePlanResponse) ProtoMessage()               {}
func (*CreatePlanResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{15} }

func (m *CreatePlanResponse) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

func (m *CreatePlanResponse) GetPlanId() string {
	if m != nil {
		return m.PlanId
	}
	return ""
}

type GetPlanRequest struct {
	Name   string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Tenant string `protobuf:"bytes,2,opt,name=tenant" json:"tenant,omitempty"`
}

func (m *GetPlanRequest) Reset()                    { *m = GetPlanRequest{} }
func (m *GetPlanRequest) String() string            { return proto.CompactTextString(m) }
func (*GetPlanRequest) ProtoMessage()               {}
func (*GetPlanRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{16} }

func (m *GetPlanRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *GetPlanRequest) GetTenant() string {
	if m != nil {
		return m.Tenant
	}
	return ""
}

type GetPlanResponse struct {
	Err   string  `protobuf:"bytes,1,opt,name=err" json:"err,omitempty"`
	Plans []*Plan `protobuf:"bytes,2,rep,name=plans" json:"plans,omitempty"`
}

func (m *GetPlanResponse) Reset()                    { *m = GetPlanResponse{} }
func (m *GetPlanResponse) String() string            { return proto.CompactTextString(m) }
func (*GetPlanResponse) ProtoMessage()               {}
func (*GetPlanResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{17} }

func (m *GetPlanResponse) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

func (m *GetPlanResponse) GetPlans() []*Plan {
	if m != nil {
		return m.Plans
	}
	return nil
}

type UpdatePlanRequest struct {
	Plan   *Plan  `protobuf:"bytes,1,opt,name=plan" json:"plan,omitempty"`
	Tenant string `protobuf:"bytes,2,opt,name=tenant" json:"tenant,omitempty"`
}

func (m *UpdatePlanRequest) Reset()                    { *m = UpdatePlanRequest{} }
func (m *UpdatePlanRequest) String() string            { return proto.CompactTextString(m) }
func (*UpdatePlanRequest) ProtoMessage()               {}
func (*UpdatePlanRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{18} }

func (m *UpdatePlanRequest) GetPlan() *Plan {
	if m != nil {
		return m.Plan
	}
	return nil
}

func (m *UpdatePlanRequest) GetTenant() string {
	if m != nil {
		return m.Tenant
	}
	return ""
}

type UpdatePlanResponse struct {
	Err    string `protobuf:"bytes,1,opt,name=err" json:"err,omitempty"`
	PlanId string `protobuf:"bytes,2,opt,name=planId" json:"planId,omitempty"`
}

func (m *UpdatePlanResponse) Reset()                    { *m = UpdatePlanResponse{} }
func (m *UpdatePlanResponse) String() string            { return proto.CompactTextString(m) }
func (*UpdatePlanResponse) ProtoMessage()               {}
func (*UpdatePlanResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{19} }

func (m *UpdatePlanResponse) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

func (m *UpdatePlanResponse) GetPlanId() string {
	if m != nil {
		return m.PlanId
	}
	return ""
}

type DeletePlanRequest struct {
	Id     string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Tenant string `protobuf:"bytes,2,opt,name=tenant" json:"tenant,omitempty"`
}

func (m *DeletePlanRequest) Reset()                    { *m = DeletePlanRequest{} }
func (m *DeletePlanRequest) String() string            { return proto.CompactTextString(m) }
func (*DeletePlanRequest) ProtoMessage()               {}
func (*DeletePlanRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{20} }

func (m *DeletePlanRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *DeletePlanRequest) GetTenant() string {
	if m != nil {
		return m.Tenant
	}
	return ""
}

type DeletePlanResponse struct {
	Err string `protobuf:"bytes,1,opt,name=err" json:"err,omitempty"`
}

func (m *DeletePlanResponse) Reset()                    { *m = DeletePlanResponse{} }
func (m *DeletePlanResponse) String() string            { return proto.CompactTextString(m) }
func (*DeletePlanResponse) ProtoMessage()               {}
func (*DeletePlanResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{21} }

func (m *DeletePlanResponse) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

type RunPlanRequest struct {
	Id     string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Tenant string `protobuf:"bytes,2,opt,name=tenant" json:"tenant,omitempty"`
}

func (m *RunPlanRequest) Reset()                    { *m = RunPlanRequest{} }
func (m *RunPlanRequest) String() string            { return proto.CompactTextString(m) }
func (*RunPlanRequest) ProtoMessage()               {}
func (*RunPlanRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{22} }

func (m *RunPlanRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *RunPlanRequest) GetTenant() string {
	if m != nil {
		return m.Tenant
	}
	return ""
}

type RunPlanResponse struct {
	Err   string `protobuf:"bytes,1,opt,name=err" json:"err,omitempty"`
	JobId string `protobuf:"bytes,2,opt,name=jobId" json:"jobId,omitempty"`
}

func (m *RunPlanResponse) Reset()                    { *m = RunPlanResponse{} }
func (m *RunPlanResponse) String() string            { return proto.CompactTextString(m) }
func (*RunPlanResponse) ProtoMessage()               {}
func (*RunPlanResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{23} }

func (m *RunPlanResponse) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

func (m *RunPlanResponse) GetJobId() string {
	if m != nil {
		return m.JobId
	}
	return ""
}

type Job struct {
	Id             string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Type           string `protobuf:"bytes,2,opt,name=type" json:"type,omitempty"`
	PlanName       string `protobuf:"bytes,3,opt,name=planName" json:"planName,omitempty"`
	PlanId         string `protobuf:"bytes,4,opt,name=planId" json:"planId,omitempty"`
	Description    string `protobuf:"bytes,5,opt,name=description" json:"description,omitempty"`
	SourceLocation string `protobuf:"bytes,6,opt,name=sourceLocation" json:"sourceLocation,omitempty"`
	DestLocation   string `protobuf:"bytes,7,opt,name=destLocation" json:"destLocation,omitempty"`
	CreateTime     int64  `protobuf:"varint,8,opt,name=createTime" json:"createTime,omitempty"`
	StartTime      int64  `protobuf:"varint,9,opt,name=startTime" json:"startTime,omitempty"`
	EndTime        int64  `protobuf:"varint,10,opt,name=endTime" json:"endTime,omitempty"`
	OverWrite      bool   `protobuf:"varint,11,opt,name=overWrite" json:"overWrite,omitempty"`
	RemainSource   bool   `protobuf:"varint,12,opt,name=remainSource" json:"remainSource,omitempty"`
}

func (m *Job) Reset()                    { *m = Job{} }
func (m *Job) String() string            { return proto.CompactTextString(m) }
func (*Job) ProtoMessage()               {}
func (*Job) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{24} }

func (m *Job) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Job) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Job) GetPlanName() string {
	if m != nil {
		return m.PlanName
	}
	return ""
}

func (m *Job) GetPlanId() string {
	if m != nil {
		return m.PlanId
	}
	return ""
}

func (m *Job) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Job) GetSourceLocation() string {
	if m != nil {
		return m.SourceLocation
	}
	return ""
}

func (m *Job) GetDestLocation() string {
	if m != nil {
		return m.DestLocation
	}
	return ""
}

func (m *Job) GetCreateTime() int64 {
	if m != nil {
		return m.CreateTime
	}
	return 0
}

func (m *Job) GetStartTime() int64 {
	if m != nil {
		return m.StartTime
	}
	return 0
}

func (m *Job) GetEndTime() int64 {
	if m != nil {
		return m.EndTime
	}
	return 0
}

func (m *Job) GetOverWrite() bool {
	if m != nil {
		return m.OverWrite
	}
	return false
}

func (m *Job) GetRemainSource() bool {
	if m != nil {
		return m.RemainSource
	}
	return false
}

type GetJobRequest struct {
	Id     string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Tenant string `protobuf:"bytes,2,opt,name=tenant" json:"tenant,omitempty"`
}

func (m *GetJobRequest) Reset()                    { *m = GetJobRequest{} }
func (m *GetJobRequest) String() string            { return proto.CompactTextString(m) }
func (*GetJobRequest) ProtoMessage()               {}
func (*GetJobRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{25} }

func (m *GetJobRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *GetJobRequest) GetTenant() string {
	if m != nil {
		return m.Tenant
	}
	return ""
}

type GetJobResponse struct {
	Err  string `protobuf:"bytes,1,opt,name=err" json:"err,omitempty"`
	Jobs []*Job `protobuf:"bytes,2,rep,name=jobs" json:"jobs,omitempty"`
}

func (m *GetJobResponse) Reset()                    { *m = GetJobResponse{} }
func (m *GetJobResponse) String() string            { return proto.CompactTextString(m) }
func (*GetJobResponse) ProtoMessage()               {}
func (*GetJobResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{26} }

func (m *GetJobResponse) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

func (m *GetJobResponse) GetJobs() []*Job {
	if m != nil {
		return m.Jobs
	}
	return nil
}

func init() {
	proto.RegisterType((*Schedule)(nil), "Schedule")
	proto.RegisterType((*Policy)(nil), "Policy")
	proto.RegisterType((*GetPolicyRequest)(nil), "GetPolicyRequest")
	proto.RegisterType((*GetPolicyResponse)(nil), "GetPolicyResponse")
	proto.RegisterType((*CreatePolicyRequest)(nil), "CreatePolicyRequest")
	proto.RegisterType((*CreatePolicyResponse)(nil), "CreatePolicyResponse")
	proto.RegisterType((*UpdatePolicyRequest)(nil), "UpdatePolicyRequest")
	proto.RegisterType((*UpdatePolicyResponse)(nil), "UpdatePolicyResponse")
	proto.RegisterType((*DeletePolicyRequest)(nil), "DeletePolicyRequest")
	proto.RegisterType((*DeletePolicyResponse)(nil), "DeletePolicyResponse")
	proto.RegisterType((*KV)(nil), "KV")
	proto.RegisterType((*Filter)(nil), "Filter")
	proto.RegisterType((*Connector)(nil), "Connector")
	proto.RegisterType((*Plan)(nil), "Plan")
	proto.RegisterType((*CreatePlanRequest)(nil), "CreatePlanRequest")
	proto.RegisterType((*CreatePlanResponse)(nil), "CreatePlanResponse")
	proto.RegisterType((*GetPlanRequest)(nil), "GetPlanRequest")
	proto.RegisterType((*GetPlanResponse)(nil), "GetPlanResponse")
	proto.RegisterType((*UpdatePlanRequest)(nil), "UpdatePlanRequest")
	proto.RegisterType((*UpdatePlanResponse)(nil), "UpdatePlanResponse")
	proto.RegisterType((*DeletePlanRequest)(nil), "DeletePlanRequest")
	proto.RegisterType((*DeletePlanResponse)(nil), "DeletePlanResponse")
	proto.RegisterType((*RunPlanRequest)(nil), "RunPlanRequest")
	proto.RegisterType((*RunPlanResponse)(nil), "RunPlanResponse")
	proto.RegisterType((*Job)(nil), "Job")
	proto.RegisterType((*GetJobRequest)(nil), "GetJobRequest")
	proto.RegisterType((*GetJobResponse)(nil), "GetJobResponse")
}

func init() { proto.RegisterFile("dataflow.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 1008 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x56, 0x6d, 0x6f, 0xe3, 0x44,
	0x10, 0x6e, 0x62, 0x37, 0x4d, 0x26, 0x25, 0x2f, 0x93, 0x14, 0x19, 0xf3, 0xa2, 0x68, 0xd1, 0x55,
	0x15, 0x87, 0x56, 0xa8, 0x20, 0x15, 0x04, 0x54, 0x88, 0x9e, 0x7a, 0xba, 0x3b, 0x84, 0x2a, 0xdf,
	0x71, 0x7c, 0x3c, 0x39, 0xf1, 0xb6, 0xf8, 0xea, 0x7a, 0x8d, 0xbd, 0xb9, 0x23, 0x5f, 0xf8, 0x07,
	0xfc, 0x1c, 0x7e, 0x12, 0xe2, 0x6f, 0xa0, 0x5d, 0x6f, 0xec, 0xb5, 0x9d, 0x1c, 0x84, 0xfb, 0xe6,
	0x79, 0x76, 0xc6, 0x33, 0x3b, 0x3b, 0xcf, 0xb3, 0x0b, 0x83, 0xc0, 0x17, 0xfe, 0x75, 0xc4, 0x5f,
	0xd3, 0x24, 0xe5, 0x82, 0x93, 0xdf, 0xa1, 0xfb, 0x74, 0xf1, 0x0b, 0x0b, 0x96, 0x11, 0x43, 0x04,
	0x5b, 0xac, 0x12, 0xe6, 0xb4, 0x66, 0xad, 0x93, 0x9e, 0xa7, 0xbe, 0x25, 0x16, 0xf8, 0xab, 0xcc,
	0x69, 0xcf, 0x2c, 0x89, 0xc9, 0x6f, 0xfc, 0x10, 0x40, 0x84, 0x77, 0xec, 0x45, 0xc2, 0xc3, 0x58,
	0x38, 0x96, 0xf2, 0xee, 0x49, 0xe4, 0x4a, 0x02, 0x78, 0x1f, 0xc6, 0x22, 0xbc, 0xb9, 0x61, 0xe9,
	0x8b, 0x24, 0xe5, 0x09, 0x4b, 0x45, 0xc8, 0x32, 0xc7, 0x56, 0x5e, 0xa3, 0x7c, 0xe1, 0xaa, 0xc0,
	0xc9, 0x1f, 0x2d, 0xe8, 0x5c, 0xf1, 0x28, 0x5c, 0xac, 0x70, 0x00, 0xed, 0x30, 0xd0, 0xc9, 0xdb,
	0x61, 0x20, 0x53, 0xc7, 0xfe, 0x1d, 0x73, 0xda, 0x79, 0x39, 0xf2, 0x1b, 0xdf, 0x85, 0x8e, 0x60,
	0xb1, 0x5f, 0xa4, 0xd5, 0x16, 0xce, 0xa0, 0x1f, 0xb0, 0x6c, 0x91, 0x86, 0x89, 0x08, 0x79, 0xac,
	0xb3, 0x99, 0x10, 0xde, 0x83, 0x6e, 0xa6, 0x37, 0xea, 0xec, 0xcf, 0x5a, 0x27, 0xfd, 0xd3, 0x1e,
	0x5d, 0xef, 0xdc, 0x2b, 0x96, 0xc8, 0x39, 0x8c, 0x1e, 0x32, 0x91, 0x57, 0xe4, 0xb1, 0x5f, 0x97,
	0x2c, 0x13, 0x45, 0x21, 0xad, 0x8d, 0x85, 0xb4, 0xcd, 0x42, 0xc8, 0xf7, 0x30, 0x36, 0xe2, 0xb3,
	0x84, 0xc7, 0x19, 0xc3, 0x11, 0x58, 0x2c, 0x4d, 0x75, 0xbc, 0xfc, 0xc4, 0xf7, 0xc1, 0x4e, 0x78,
	0x94, 0xb7, 0xb5, 0x7f, 0x7a, 0x40, 0x75, 0x80, 0x02, 0xc9, 0x67, 0x30, 0xb9, 0x48, 0x99, 0x2f,
	0x58, 0xb5, 0x8c, 0xf7, 0xc0, 0x4a, 0x78, 0xa4, 0xfe, 0x62, 0x84, 0x48, 0x8c, 0x9c, 0xc3, 0xb4,
	0x1a, 0xb1, 0x35, 0xf1, 0x14, 0xf6, 0x13, 0x1e, 0x3d, 0x0a, 0x74, 0xd9, 0xb9, 0x21, 0x33, 0xfe,
	0x94, 0x04, 0x3b, 0x66, 0xac, 0x46, 0xec, 0x98, 0xf1, 0x1e, 0x4c, 0x1e, 0xb0, 0x88, 0xd5, 0x33,
	0xd6, 0x66, 0x80, 0x9c, 0xc0, 0xb4, 0xea, 0xb6, 0x2d, 0x0d, 0xf9, 0x14, 0xda, 0x4f, 0x9e, 0x4b,
	0xfc, 0x96, 0xad, 0xd6, 0xf8, 0x2d, 0x5b, 0xc9, 0xf4, 0xaf, 0xfc, 0x68, 0xb9, 0x1e, 0xa3, 0xdc,
	0x20, 0x67, 0xd0, 0xb9, 0x0c, 0x23, 0xc1, 0x52, 0x79, 0x90, 0x49, 0xca, 0xae, 0xc3, 0xdf, 0x74,
	0x90, 0xb6, 0xf0, 0x08, 0x2c, 0xe1, 0xdf, 0xe8, 0x03, 0xb2, 0xe8, 0x93, 0xe7, 0x9e, 0xb4, 0x49,
	0x04, 0xbd, 0x0b, 0x1e, 0xc7, 0x6c, 0x21, 0x78, 0x8a, 0x2e, 0x74, 0x33, 0xc1, 0xd3, 0x67, 0x25,
	0x69, 0x0a, 0x1b, 0x3f, 0x02, 0x98, 0x2f, 0x17, 0xb7, 0x4c, 0xfc, 0x58, 0xce, 0xb0, 0x81, 0xe0,
	0xc7, 0x00, 0x0b, 0x1e, 0xc7, 0x17, 0x3c, 0xbe, 0x0e, 0x6f, 0x1c, 0xab, 0x4c, 0x63, 0xc0, 0xe4,
	0xef, 0x36, 0xd8, 0x57, 0x91, 0x1f, 0xff, 0x27, 0x6e, 0xd4, 0x38, 0x60, 0x35, 0x39, 0xb0, 0x26,
	0xb8, 0x6d, 0x10, 0xdc, 0x85, 0x6e, 0xa2, 0x7a, 0xfb, 0x28, 0x50, 0xbc, 0xe8, 0x79, 0x85, 0x2d,
	0xf7, 0x90, 0x7f, 0xab, 0x3d, 0x74, 0xf2, 0x3d, 0x94, 0x08, 0x7e, 0x02, 0x90, 0xf1, 0x65, 0xba,
	0x60, 0xb2, 0x25, 0xce, 0x81, 0x1a, 0x13, 0xa0, 0x45, 0x7f, 0x3c, 0x63, 0x15, 0x8f, 0xa1, 0x1b,
	0xb0, 0x4c, 0x28, 0xcf, 0x6e, 0xc3, 0xb3, 0x58, 0x93, 0xcc, 0xb8, 0x0e, 0x23, 0xe1, 0xf4, 0xf4,
	0xd0, 0xe5, 0xc7, 0xe4, 0x29, 0x10, 0x3f, 0x80, 0x1e, 0x7f, 0xc5, 0xd2, 0x9f, 0xd3, 0x50, 0x30,
	0x07, 0x66, 0xad, 0x93, 0xae, 0x57, 0x02, 0x48, 0xe0, 0x30, 0x65, 0x77, 0x7e, 0x18, 0x3f, 0x55,
	0x69, 0x9d, 0xbe, 0x72, 0xa8, 0x60, 0x06, 0x6f, 0x0f, 0x2b, 0xbc, 0xbd, 0x84, 0xb1, 0x66, 0x50,
	0xe4, 0xc7, 0xe5, 0xfc, 0xdb, 0x49, 0xe4, 0xc7, 0x9a, 0x00, 0xfb, 0x54, 0xad, 0x29, 0x68, 0x2b,
	0xff, 0xcf, 0x01, 0xcd, 0xff, 0x6c, 0x65, 0x85, 0x1c, 0xbb, 0xc8, 0x8f, 0x0b, 0x5a, 0x68, 0x8b,
	0x7c, 0x03, 0x03, 0xa9, 0x1f, 0x46, 0x11, 0xbb, 0xa8, 0xcf, 0x77, 0x30, 0x2c, 0xa2, 0xdf, 0xa0,
	0x3d, 0xfb, 0x32, 0xd9, 0x5a, 0x7c, 0xf4, 0xb6, 0x72, 0x4c, 0xf6, 0x41, 0xf3, 0xfa, 0xad, 0xfb,
	0x60, 0xfe, 0x67, 0xe7, 0x3e, 0x7c, 0x0d, 0x63, 0x4d, 0x7c, 0xa3, 0x8e, 0x3a, 0x0b, 0xb6, 0x25,
	0x3f, 0x06, 0x34, 0x83, 0xb7, 0x6a, 0xc6, 0x97, 0x30, 0xf0, 0x96, 0xf1, 0xff, 0xc9, 0xf0, 0x15,
	0x0c, 0x8b, 0xc8, 0x37, 0x29, 0xdf, 0x4b, 0x3e, 0x2f, 0x95, 0x4f, 0x19, 0xe4, 0xaf, 0x36, 0x58,
	0x8f, 0xf9, 0x7c, 0x13, 0xa5, 0x15, 0x39, 0xdb, 0x35, 0x72, 0x46, 0x7e, 0xac, 0xe8, 0x67, 0x69,
	0x72, 0x6a, 0xdb, 0xe8, 0x9c, 0x6d, 0x76, 0xae, 0x2e, 0x03, 0xfb, 0x4d, 0x19, 0x38, 0x86, 0x41,
	0x4e, 0xcc, 0x1f, 0xf8, 0xc2, 0x57, 0x4e, 0x39, 0xb5, 0x6b, 0xa8, 0xe4, 0x93, 0xa4, 0x65, 0xe1,
	0x75, 0xa0, 0xbc, 0x2a, 0x98, 0x94, 0x88, 0x85, 0x9a, 0xf7, 0x67, 0xe1, 0x1d, 0x53, 0xc4, 0xb6,
	0x3c, 0x03, 0x91, 0x8c, 0xcd, 0x84, 0x9f, 0x0a, 0xb5, 0xdc, 0x53, 0xcb, 0x25, 0x80, 0x0e, 0x1c,
	0xb0, 0x38, 0x50, 0x6b, 0xa0, 0xd6, 0xd6, 0x66, 0x95, 0xe9, 0xfd, 0x7f, 0x63, 0xfa, 0x61, 0x93,
	0xe9, 0xe4, 0x0c, 0xde, 0x79, 0xc8, 0xc4, 0x63, 0x3e, 0xdf, 0xf5, 0x6c, 0x73, 0x0a, 0xaa, 0xc0,
	0xad, 0x47, 0xeb, 0x80, 0xfd, 0x92, 0xcf, 0xd7, 0x14, 0xb2, 0xa9, 0xf4, 0x56, 0xc8, 0xe9, 0x9f,
	0x36, 0x74, 0x1f, 0xf8, 0xc2, 0xbf, 0x8c, 0xf8, 0x6b, 0xfc, 0x02, 0x7a, 0xc5, 0x6b, 0x00, 0xc7,
	0xb4, 0xfe, 0xb2, 0x70, 0x91, 0x36, 0x1e, 0x0b, 0x64, 0x0f, 0xbf, 0x85, 0x43, 0xf3, 0x36, 0xc7,
	0x29, 0xdd, 0xf0, 0x1c, 0x70, 0x8f, 0xe8, 0xa6, 0x2b, 0x3f, 0x0f, 0x37, 0xaf, 0x66, 0x9c, 0xd2,
	0x0d, 0x77, 0xbb, 0x7b, 0x44, 0x37, 0xdd, 0xdf, 0x79, 0xb8, 0x79, 0xe5, 0xe2, 0x94, 0x6e, 0xb8,
	0xa8, 0xdd, 0x23, 0xba, 0xe9, 0x5e, 0x26, 0x7b, 0x48, 0xe1, 0x40, 0x4b, 0x10, 0x0e, 0x69, 0x55,
	0xca, 0xdc, 0x11, 0xad, 0xa9, 0x13, 0xd9, 0xc3, 0x33, 0x80, 0x52, 0x30, 0x11, 0x69, 0x43, 0x85,
	0xdd, 0x09, 0x6d, 0x2a, 0x6a, 0x1e, 0x58, 0x2a, 0x0c, 0x22, 0x6d, 0xc8, 0x96, 0x3b, 0xa1, 0x4d,
	0x09, 0xca, 0x03, 0x4b, 0x75, 0x40, 0xa4, 0x0d, 0x9d, 0x71, 0x27, 0xb4, 0x29, 0x1f, 0x64, 0x0f,
	0xef, 0x43, 0x27, 0x1f, 0x0c, 0x1c, 0xd0, 0xca, 0x68, 0xb9, 0x43, 0x5a, 0x9d, 0x98, 0xbc, 0x0f,
	0x5a, 0x21, 0x70, 0x48, 0xab, 0x2a, 0xe3, 0x8e, 0x68, 0x4d, 0x3c, 0xc8, 0xde, 0xbc, 0xa3, 0xde,
	0xe3, 0x9f, 0xff, 0x13, 0x00, 0x00, 0xff, 0xff, 0x21, 0x74, 0xb1, 0x8d, 0xa1, 0x0b, 0x00, 0x00,
}
