// Code generated by protoc-gen-go. DO NOT EDIT.
// source: dataflow.proto

package dataflow

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type GetPolicyRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetPolicyRequest) Reset()         { *m = GetPolicyRequest{} }
func (m *GetPolicyRequest) String() string { return proto.CompactTextString(m) }
func (*GetPolicyRequest) ProtoMessage()    {}
func (*GetPolicyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_dataflow_9f1421f30e31620b, []int{0}
}
func (m *GetPolicyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPolicyRequest.Unmarshal(m, b)
}
func (m *GetPolicyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPolicyRequest.Marshal(b, m, deterministic)
}
func (dst *GetPolicyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPolicyRequest.Merge(dst, src)
}
func (m *GetPolicyRequest) XXX_Size() int {
	return xxx_messageInfo_GetPolicyRequest.Size(m)
}
func (m *GetPolicyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPolicyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetPolicyRequest proto.InternalMessageInfo

func (m *GetPolicyRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type GetPolicyResponse struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetPolicyResponse) Reset()         { *m = GetPolicyResponse{} }
func (m *GetPolicyResponse) String() string { return proto.CompactTextString(m) }
func (*GetPolicyResponse) ProtoMessage()    {}
func (*GetPolicyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_dataflow_9f1421f30e31620b, []int{1}
}
func (m *GetPolicyResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPolicyResponse.Unmarshal(m, b)
}
func (m *GetPolicyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPolicyResponse.Marshal(b, m, deterministic)
}
func (dst *GetPolicyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPolicyResponse.Merge(dst, src)
}
func (m *GetPolicyResponse) XXX_Size() int {
	return xxx_messageInfo_GetPolicyResponse.Size(m)
}
func (m *GetPolicyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPolicyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetPolicyResponse proto.InternalMessageInfo

func (m *GetPolicyResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *GetPolicyResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func init() {
	proto.RegisterType((*GetPolicyRequest)(nil), "GetPolicyRequest")
	proto.RegisterType((*GetPolicyResponse)(nil), "GetPolicyResponse")
}

func init() { proto.RegisterFile("dataflow.proto", fileDescriptor_dataflow_9f1421f30e31620b) }

var fileDescriptor_dataflow_9f1421f30e31620b = []byte{
	// 140 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4b, 0x49, 0x2c, 0x49,
	0x4c, 0xcb, 0xc9, 0x2f, 0xd7, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x57, 0x52, 0xe2, 0x12, 0x70, 0x4f,
	0x2d, 0x09, 0xc8, 0xcf, 0xc9, 0x4c, 0xae, 0x0c, 0x4a, 0x2d, 0x2c, 0x4d, 0x2d, 0x2e, 0x11, 0xe2,
	0xe3, 0x62, 0xca, 0x4c, 0x91, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x62, 0xca, 0x4c, 0x51, 0x32,
	0xe7, 0x12, 0x44, 0x52, 0x53, 0x5c, 0x90, 0x9f, 0x57, 0x9c, 0x8a, 0xae, 0x48, 0x48, 0x88, 0x8b,
	0x25, 0x2f, 0x31, 0x37, 0x55, 0x82, 0x09, 0x2c, 0x02, 0x66, 0x1b, 0x39, 0x70, 0x71, 0xb8, 0x24,
	0x96, 0x24, 0xba, 0xe5, 0xe4, 0x97, 0x0b, 0x99, 0x70, 0x71, 0xc2, 0x0d, 0x11, 0x12, 0xd4, 0x43,
	0xb7, 0x54, 0x4a, 0x48, 0x0f, 0xc3, 0x0e, 0x25, 0x86, 0x24, 0x36, 0xb0, 0x2b, 0x8d, 0x01, 0x01,
	0x00, 0x00, 0xff, 0xff, 0x9b, 0x33, 0x64, 0x73, 0xb7, 0x00, 0x00, 0x00,
}
