// Code generated by protoc-gen-go. DO NOT EDIT.
// source: dataflow.proto

package dataflow

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Schedule struct {
	Type                 string   `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Days                 []string `protobuf:"bytes,2,rep,name=days,proto3" json:"days,omitempty"`
	TimePoint            string   `protobuf:"bytes,3,opt,name=time_point,json=timePoint,proto3" json:"time_point,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Schedule) Reset()         { *m = Schedule{} }
func (m *Schedule) String() string { return proto.CompactTextString(m) }
func (*Schedule) ProtoMessage()    {}
func (*Schedule) Descriptor() ([]byte, []int) {
	return fileDescriptor_dataflow_a958fb8d2e54cbb5, []int{0}
}
func (m *Schedule) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Schedule.Unmarshal(m, b)
}
func (m *Schedule) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Schedule.Marshal(b, m, deterministic)
}
func (dst *Schedule) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Schedule.Merge(dst, src)
}
func (m *Schedule) XXX_Size() int {
	return xxx_messageInfo_Schedule.Size(m)
}
func (m *Schedule) XXX_DiscardUnknown() {
	xxx_messageInfo_Schedule.DiscardUnknown(m)
}

var xxx_messageInfo_Schedule proto.InternalMessageInfo

func (m *Schedule) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Schedule) GetDays() []string {
	if m != nil {
		return m.Days
	}
	return nil
}

func (m *Schedule) GetTimePoint() string {
	if m != nil {
		return m.TimePoint
	}
	return ""
}

type Policy struct {
	Id                   string    `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string    `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Tenant               string    `protobuf:"bytes,3,opt,name=tenant,proto3" json:"tenant,omitempty"`
	Description          string    `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Sched                *Schedule `protobuf:"bytes,5,opt,name=sched,proto3" json:"sched,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Policy) Reset()         { *m = Policy{} }
func (m *Policy) String() string { return proto.CompactTextString(m) }
func (*Policy) ProtoMessage()    {}
func (*Policy) Descriptor() ([]byte, []int) {
	return fileDescriptor_dataflow_a958fb8d2e54cbb5, []int{1}
}
func (m *Policy) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Policy.Unmarshal(m, b)
}
func (m *Policy) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Policy.Marshal(b, m, deterministic)
}
func (dst *Policy) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Policy.Merge(dst, src)
}
func (m *Policy) XXX_Size() int {
	return xxx_messageInfo_Policy.Size(m)
}
func (m *Policy) XXX_DiscardUnknown() {
	xxx_messageInfo_Policy.DiscardUnknown(m)
}

var xxx_messageInfo_Policy proto.InternalMessageInfo

func (m *Policy) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Policy) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Policy) GetTenant() string {
	if m != nil {
		return m.Tenant
	}
	return ""
}

func (m *Policy) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Policy) GetSched() *Schedule {
	if m != nil {
		return m.Sched
	}
	return nil
}

type GetPolicyRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Tenant               string   `protobuf:"bytes,2,opt,name=tenant,proto3" json:"tenant,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetPolicyRequest) Reset()         { *m = GetPolicyRequest{} }
func (m *GetPolicyRequest) String() string { return proto.CompactTextString(m) }
func (*GetPolicyRequest) ProtoMessage()    {}
func (*GetPolicyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_dataflow_a958fb8d2e54cbb5, []int{2}
}
func (m *GetPolicyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPolicyRequest.Unmarshal(m, b)
}
func (m *GetPolicyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPolicyRequest.Marshal(b, m, deterministic)
}
func (dst *GetPolicyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPolicyRequest.Merge(dst, src)
}
func (m *GetPolicyRequest) XXX_Size() int {
	return xxx_messageInfo_GetPolicyRequest.Size(m)
}
func (m *GetPolicyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPolicyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetPolicyRequest proto.InternalMessageInfo

func (m *GetPolicyRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *GetPolicyRequest) GetTenant() string {
	if m != nil {
		return m.Tenant
	}
	return ""
}

type GetPolicyResponse struct {
	Err                  string    `protobuf:"bytes,1,opt,name=err,proto3" json:"err,omitempty"`
	Pols                 []*Policy `protobuf:"bytes,2,rep,name=pols,proto3" json:"pols,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *GetPolicyResponse) Reset()         { *m = GetPolicyResponse{} }
func (m *GetPolicyResponse) String() string { return proto.CompactTextString(m) }
func (*GetPolicyResponse) ProtoMessage()    {}
func (*GetPolicyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_dataflow_a958fb8d2e54cbb5, []int{3}
}
func (m *GetPolicyResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPolicyResponse.Unmarshal(m, b)
}
func (m *GetPolicyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPolicyResponse.Marshal(b, m, deterministic)
}
func (dst *GetPolicyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPolicyResponse.Merge(dst, src)
}
func (m *GetPolicyResponse) XXX_Size() int {
	return xxx_messageInfo_GetPolicyResponse.Size(m)
}
func (m *GetPolicyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPolicyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetPolicyResponse proto.InternalMessageInfo

func (m *GetPolicyResponse) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

func (m *GetPolicyResponse) GetPols() []*Policy {
	if m != nil {
		return m.Pols
	}
	return nil
}

type CreatePolicyRequest struct {
	Pol                  *Policy  `protobuf:"bytes,1,opt,name=pol,proto3" json:"pol,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreatePolicyRequest) Reset()         { *m = CreatePolicyRequest{} }
func (m *CreatePolicyRequest) String() string { return proto.CompactTextString(m) }
func (*CreatePolicyRequest) ProtoMessage()    {}
func (*CreatePolicyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_dataflow_a958fb8d2e54cbb5, []int{4}
}
func (m *CreatePolicyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreatePolicyRequest.Unmarshal(m, b)
}
func (m *CreatePolicyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreatePolicyRequest.Marshal(b, m, deterministic)
}
func (dst *CreatePolicyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreatePolicyRequest.Merge(dst, src)
}
func (m *CreatePolicyRequest) XXX_Size() int {
	return xxx_messageInfo_CreatePolicyRequest.Size(m)
}
func (m *CreatePolicyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreatePolicyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreatePolicyRequest proto.InternalMessageInfo

func (m *CreatePolicyRequest) GetPol() *Policy {
	if m != nil {
		return m.Pol
	}
	return nil
}

type CreatePolicyResponse struct {
	Err                  string   `protobuf:"bytes,1,opt,name=err,proto3" json:"err,omitempty"`
	PolId                string   `protobuf:"bytes,2,opt,name=polId,proto3" json:"polId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreatePolicyResponse) Reset()         { *m = CreatePolicyResponse{} }
func (m *CreatePolicyResponse) String() string { return proto.CompactTextString(m) }
func (*CreatePolicyResponse) ProtoMessage()    {}
func (*CreatePolicyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_dataflow_a958fb8d2e54cbb5, []int{5}
}
func (m *CreatePolicyResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreatePolicyResponse.Unmarshal(m, b)
}
func (m *CreatePolicyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreatePolicyResponse.Marshal(b, m, deterministic)
}
func (dst *CreatePolicyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreatePolicyResponse.Merge(dst, src)
}
func (m *CreatePolicyResponse) XXX_Size() int {
	return xxx_messageInfo_CreatePolicyResponse.Size(m)
}
func (m *CreatePolicyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreatePolicyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreatePolicyResponse proto.InternalMessageInfo

func (m *CreatePolicyResponse) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

func (m *CreatePolicyResponse) GetPolId() string {
	if m != nil {
		return m.PolId
	}
	return ""
}

type UpdatePolicyRequest struct {
	Pol                  *Policy  `protobuf:"bytes,1,opt,name=pol,proto3" json:"pol,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdatePolicyRequest) Reset()         { *m = UpdatePolicyRequest{} }
func (m *UpdatePolicyRequest) String() string { return proto.CompactTextString(m) }
func (*UpdatePolicyRequest) ProtoMessage()    {}
func (*UpdatePolicyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_dataflow_a958fb8d2e54cbb5, []int{6}
}
func (m *UpdatePolicyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdatePolicyRequest.Unmarshal(m, b)
}
func (m *UpdatePolicyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdatePolicyRequest.Marshal(b, m, deterministic)
}
func (dst *UpdatePolicyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdatePolicyRequest.Merge(dst, src)
}
func (m *UpdatePolicyRequest) XXX_Size() int {
	return xxx_messageInfo_UpdatePolicyRequest.Size(m)
}
func (m *UpdatePolicyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdatePolicyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdatePolicyRequest proto.InternalMessageInfo

func (m *UpdatePolicyRequest) GetPol() *Policy {
	if m != nil {
		return m.Pol
	}
	return nil
}

type UpdatePolicyResponse struct {
	Err                  string   `protobuf:"bytes,1,opt,name=err,proto3" json:"err,omitempty"`
	PolId                string   `protobuf:"bytes,2,opt,name=polId,proto3" json:"polId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdatePolicyResponse) Reset()         { *m = UpdatePolicyResponse{} }
func (m *UpdatePolicyResponse) String() string { return proto.CompactTextString(m) }
func (*UpdatePolicyResponse) ProtoMessage()    {}
func (*UpdatePolicyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_dataflow_a958fb8d2e54cbb5, []int{7}
}
func (m *UpdatePolicyResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdatePolicyResponse.Unmarshal(m, b)
}
func (m *UpdatePolicyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdatePolicyResponse.Marshal(b, m, deterministic)
}
func (dst *UpdatePolicyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdatePolicyResponse.Merge(dst, src)
}
func (m *UpdatePolicyResponse) XXX_Size() int {
	return xxx_messageInfo_UpdatePolicyResponse.Size(m)
}
func (m *UpdatePolicyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdatePolicyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdatePolicyResponse proto.InternalMessageInfo

func (m *UpdatePolicyResponse) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

func (m *UpdatePolicyResponse) GetPolId() string {
	if m != nil {
		return m.PolId
	}
	return ""
}

type DeletePolicyRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeletePolicyRequest) Reset()         { *m = DeletePolicyRequest{} }
func (m *DeletePolicyRequest) String() string { return proto.CompactTextString(m) }
func (*DeletePolicyRequest) ProtoMessage()    {}
func (*DeletePolicyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_dataflow_a958fb8d2e54cbb5, []int{8}
}
func (m *DeletePolicyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeletePolicyRequest.Unmarshal(m, b)
}
func (m *DeletePolicyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeletePolicyRequest.Marshal(b, m, deterministic)
}
func (dst *DeletePolicyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeletePolicyRequest.Merge(dst, src)
}
func (m *DeletePolicyRequest) XXX_Size() int {
	return xxx_messageInfo_DeletePolicyRequest.Size(m)
}
func (m *DeletePolicyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeletePolicyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeletePolicyRequest proto.InternalMessageInfo

func (m *DeletePolicyRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type DeletePolicyResponse struct {
	Err                  string   `protobuf:"bytes,1,opt,name=err,proto3" json:"err,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeletePolicyResponse) Reset()         { *m = DeletePolicyResponse{} }
func (m *DeletePolicyResponse) String() string { return proto.CompactTextString(m) }
func (*DeletePolicyResponse) ProtoMessage()    {}
func (*DeletePolicyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_dataflow_a958fb8d2e54cbb5, []int{9}
}
func (m *DeletePolicyResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeletePolicyResponse.Unmarshal(m, b)
}
func (m *DeletePolicyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeletePolicyResponse.Marshal(b, m, deterministic)
}
func (dst *DeletePolicyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeletePolicyResponse.Merge(dst, src)
}
func (m *DeletePolicyResponse) XXX_Size() int {
	return xxx_messageInfo_DeletePolicyResponse.Size(m)
}
func (m *DeletePolicyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeletePolicyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeletePolicyResponse proto.InternalMessageInfo

func (m *DeletePolicyResponse) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

type KV struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KV) Reset()         { *m = KV{} }
func (m *KV) String() string { return proto.CompactTextString(m) }
func (*KV) ProtoMessage()    {}
func (*KV) Descriptor() ([]byte, []int) {
	return fileDescriptor_dataflow_a958fb8d2e54cbb5, []int{10}
}
func (m *KV) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KV.Unmarshal(m, b)
}
func (m *KV) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KV.Marshal(b, m, deterministic)
}
func (dst *KV) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KV.Merge(dst, src)
}
func (m *KV) XXX_Size() int {
	return xxx_messageInfo_KV.Size(m)
}
func (m *KV) XXX_DiscardUnknown() {
	xxx_messageInfo_KV.DiscardUnknown(m)
}

var xxx_messageInfo_KV proto.InternalMessageInfo

func (m *KV) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *KV) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type Filter struct {
	Prefix               string   `protobuf:"bytes,1,opt,name=prefix,proto3" json:"prefix,omitempty"`
	Tag                  []*KV    `protobuf:"bytes,2,rep,name=tag,proto3" json:"tag,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Filter) Reset()         { *m = Filter{} }
func (m *Filter) String() string { return proto.CompactTextString(m) }
func (*Filter) ProtoMessage()    {}
func (*Filter) Descriptor() ([]byte, []int) {
	return fileDescriptor_dataflow_a958fb8d2e54cbb5, []int{11}
}
func (m *Filter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Filter.Unmarshal(m, b)
}
func (m *Filter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Filter.Marshal(b, m, deterministic)
}
func (dst *Filter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Filter.Merge(dst, src)
}
func (m *Filter) XXX_Size() int {
	return xxx_messageInfo_Filter.Size(m)
}
func (m *Filter) XXX_DiscardUnknown() {
	xxx_messageInfo_Filter.DiscardUnknown(m)
}

var xxx_messageInfo_Filter proto.InternalMessageInfo

func (m *Filter) GetPrefix() string {
	if m != nil {
		return m.Prefix
	}
	return ""
}

func (m *Filter) GetTag() []*KV {
	if m != nil {
		return m.Tag
	}
	return nil
}

type Connector struct {
	StorType             string   `protobuf:"bytes,1,opt,name=storType,proto3" json:"storType,omitempty"`
	BucketName           string   `protobuf:"bytes,2,opt,name=bucketName,proto3" json:"bucketName,omitempty"`
	ConnConfig           []*KV    `protobuf:"bytes,3,rep,name=connConfig,proto3" json:"connConfig,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Connector) Reset()         { *m = Connector{} }
func (m *Connector) String() string { return proto.CompactTextString(m) }
func (*Connector) ProtoMessage()    {}
func (*Connector) Descriptor() ([]byte, []int) {
	return fileDescriptor_dataflow_a958fb8d2e54cbb5, []int{12}
}
func (m *Connector) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Connector.Unmarshal(m, b)
}
func (m *Connector) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Connector.Marshal(b, m, deterministic)
}
func (dst *Connector) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Connector.Merge(dst, src)
}
func (m *Connector) XXX_Size() int {
	return xxx_messageInfo_Connector.Size(m)
}
func (m *Connector) XXX_DiscardUnknown() {
	xxx_messageInfo_Connector.DiscardUnknown(m)
}

var xxx_messageInfo_Connector proto.InternalMessageInfo

func (m *Connector) GetStorType() string {
	if m != nil {
		return m.StorType
	}
	return ""
}

func (m *Connector) GetBucketName() string {
	if m != nil {
		return m.BucketName
	}
	return ""
}

func (m *Connector) GetConnConfig() []*KV {
	if m != nil {
		return m.ConnConfig
	}
	return nil
}

type Plan struct {
	Id                   string     `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string     `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description          string     `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Type                 string     `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	PolicyId             string     `protobuf:"bytes,5,opt,name=policyId,proto3" json:"policyId,omitempty"`
	PolicyName           string     `protobuf:"bytes,6,opt,name=policyName,proto3" json:"policyName,omitempty"`
	SourceConn           *Connector `protobuf:"bytes,7,opt,name=sourceConn,proto3" json:"sourceConn,omitempty"`
	DestConn             *Connector `protobuf:"bytes,8,opt,name=destConn,proto3" json:"destConn,omitempty"`
	Filt                 *Filter    `protobuf:"bytes,9,opt,name=filt,proto3" json:"filt,omitempty"`
	OverWrite            bool       `protobuf:"varint,10,opt,name=overWrite,proto3" json:"overWrite,omitempty"`
	RemainSource         bool       `protobuf:"varint,11,opt,name=remainSource,proto3" json:"remainSource,omitempty"`
	Tenant               string     `protobuf:"bytes,12,opt,name=tenant,proto3" json:"tenant,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Plan) Reset()         { *m = Plan{} }
func (m *Plan) String() string { return proto.CompactTextString(m) }
func (*Plan) ProtoMessage()    {}
func (*Plan) Descriptor() ([]byte, []int) {
	return fileDescriptor_dataflow_a958fb8d2e54cbb5, []int{13}
}
func (m *Plan) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Plan.Unmarshal(m, b)
}
func (m *Plan) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Plan.Marshal(b, m, deterministic)
}
func (dst *Plan) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Plan.Merge(dst, src)
}
func (m *Plan) XXX_Size() int {
	return xxx_messageInfo_Plan.Size(m)
}
func (m *Plan) XXX_DiscardUnknown() {
	xxx_messageInfo_Plan.DiscardUnknown(m)
}

var xxx_messageInfo_Plan proto.InternalMessageInfo

func (m *Plan) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Plan) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Plan) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Plan) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Plan) GetPolicyId() string {
	if m != nil {
		return m.PolicyId
	}
	return ""
}

func (m *Plan) GetPolicyName() string {
	if m != nil {
		return m.PolicyName
	}
	return ""
}

func (m *Plan) GetSourceConn() *Connector {
	if m != nil {
		return m.SourceConn
	}
	return nil
}

func (m *Plan) GetDestConn() *Connector {
	if m != nil {
		return m.DestConn
	}
	return nil
}

func (m *Plan) GetFilt() *Filter {
	if m != nil {
		return m.Filt
	}
	return nil
}

func (m *Plan) GetOverWrite() bool {
	if m != nil {
		return m.OverWrite
	}
	return false
}

func (m *Plan) GetRemainSource() bool {
	if m != nil {
		return m.RemainSource
	}
	return false
}

func (m *Plan) GetTenant() string {
	if m != nil {
		return m.Tenant
	}
	return ""
}

type CreatePlanRequest struct {
	Plan                 *Plan    `protobuf:"bytes,1,opt,name=plan,proto3" json:"plan,omitempty"`
	Tenant               string   `protobuf:"bytes,2,opt,name=tenant,proto3" json:"tenant,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreatePlanRequest) Reset()         { *m = CreatePlanRequest{} }
func (m *CreatePlanRequest) String() string { return proto.CompactTextString(m) }
func (*CreatePlanRequest) ProtoMessage()    {}
func (*CreatePlanRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_dataflow_a958fb8d2e54cbb5, []int{14}
}
func (m *CreatePlanRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreatePlanRequest.Unmarshal(m, b)
}
func (m *CreatePlanRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreatePlanRequest.Marshal(b, m, deterministic)
}
func (dst *CreatePlanRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreatePlanRequest.Merge(dst, src)
}
func (m *CreatePlanRequest) XXX_Size() int {
	return xxx_messageInfo_CreatePlanRequest.Size(m)
}
func (m *CreatePlanRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreatePlanRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreatePlanRequest proto.InternalMessageInfo

func (m *CreatePlanRequest) GetPlan() *Plan {
	if m != nil {
		return m.Plan
	}
	return nil
}

func (m *CreatePlanRequest) GetTenant() string {
	if m != nil {
		return m.Tenant
	}
	return ""
}

type CreatePlanResponse struct {
	Err                  string   `protobuf:"bytes,1,opt,name=err,proto3" json:"err,omitempty"`
	PlanId               string   `protobuf:"bytes,2,opt,name=planId,proto3" json:"planId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreatePlanResponse) Reset()         { *m = CreatePlanResponse{} }
func (m *CreatePlanResponse) String() string { return proto.CompactTextString(m) }
func (*CreatePlanResponse) ProtoMessage()    {}
func (*CreatePlanResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_dataflow_a958fb8d2e54cbb5, []int{15}
}
func (m *CreatePlanResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreatePlanResponse.Unmarshal(m, b)
}
func (m *CreatePlanResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreatePlanResponse.Marshal(b, m, deterministic)
}
func (dst *CreatePlanResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreatePlanResponse.Merge(dst, src)
}
func (m *CreatePlanResponse) XXX_Size() int {
	return xxx_messageInfo_CreatePlanResponse.Size(m)
}
func (m *CreatePlanResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreatePlanResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreatePlanResponse proto.InternalMessageInfo

func (m *CreatePlanResponse) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

func (m *CreatePlanResponse) GetPlanId() string {
	if m != nil {
		return m.PlanId
	}
	return ""
}

type GetPlanRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Tenant               string   `protobuf:"bytes,2,opt,name=tenant,proto3" json:"tenant,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetPlanRequest) Reset()         { *m = GetPlanRequest{} }
func (m *GetPlanRequest) String() string { return proto.CompactTextString(m) }
func (*GetPlanRequest) ProtoMessage()    {}
func (*GetPlanRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_dataflow_a958fb8d2e54cbb5, []int{16}
}
func (m *GetPlanRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPlanRequest.Unmarshal(m, b)
}
func (m *GetPlanRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPlanRequest.Marshal(b, m, deterministic)
}
func (dst *GetPlanRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPlanRequest.Merge(dst, src)
}
func (m *GetPlanRequest) XXX_Size() int {
	return xxx_messageInfo_GetPlanRequest.Size(m)
}
func (m *GetPlanRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPlanRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetPlanRequest proto.InternalMessageInfo

func (m *GetPlanRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *GetPlanRequest) GetTenant() string {
	if m != nil {
		return m.Tenant
	}
	return ""
}

type GetPlanResponse struct {
	Err                  string   `protobuf:"bytes,1,opt,name=err,proto3" json:"err,omitempty"`
	Plans                []*Plan  `protobuf:"bytes,2,rep,name=plans,proto3" json:"plans,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetPlanResponse) Reset()         { *m = GetPlanResponse{} }
func (m *GetPlanResponse) String() string { return proto.CompactTextString(m) }
func (*GetPlanResponse) ProtoMessage()    {}
func (*GetPlanResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_dataflow_a958fb8d2e54cbb5, []int{17}
}
func (m *GetPlanResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPlanResponse.Unmarshal(m, b)
}
func (m *GetPlanResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPlanResponse.Marshal(b, m, deterministic)
}
func (dst *GetPlanResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPlanResponse.Merge(dst, src)
}
func (m *GetPlanResponse) XXX_Size() int {
	return xxx_messageInfo_GetPlanResponse.Size(m)
}
func (m *GetPlanResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPlanResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetPlanResponse proto.InternalMessageInfo

func (m *GetPlanResponse) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

func (m *GetPlanResponse) GetPlans() []*Plan {
	if m != nil {
		return m.Plans
	}
	return nil
}

type UpdatePlanRequest struct {
	Plan                 *Plan    `protobuf:"bytes,1,opt,name=plan,proto3" json:"plan,omitempty"`
	Tenant               string   `protobuf:"bytes,2,opt,name=tenant,proto3" json:"tenant,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdatePlanRequest) Reset()         { *m = UpdatePlanRequest{} }
func (m *UpdatePlanRequest) String() string { return proto.CompactTextString(m) }
func (*UpdatePlanRequest) ProtoMessage()    {}
func (*UpdatePlanRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_dataflow_a958fb8d2e54cbb5, []int{18}
}
func (m *UpdatePlanRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdatePlanRequest.Unmarshal(m, b)
}
func (m *UpdatePlanRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdatePlanRequest.Marshal(b, m, deterministic)
}
func (dst *UpdatePlanRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdatePlanRequest.Merge(dst, src)
}
func (m *UpdatePlanRequest) XXX_Size() int {
	return xxx_messageInfo_UpdatePlanRequest.Size(m)
}
func (m *UpdatePlanRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdatePlanRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdatePlanRequest proto.InternalMessageInfo

func (m *UpdatePlanRequest) GetPlan() *Plan {
	if m != nil {
		return m.Plan
	}
	return nil
}

func (m *UpdatePlanRequest) GetTenant() string {
	if m != nil {
		return m.Tenant
	}
	return ""
}

type UpdatePlanResponse struct {
	Err                  string   `protobuf:"bytes,1,opt,name=err,proto3" json:"err,omitempty"`
	PlanId               string   `protobuf:"bytes,2,opt,name=planId,proto3" json:"planId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdatePlanResponse) Reset()         { *m = UpdatePlanResponse{} }
func (m *UpdatePlanResponse) String() string { return proto.CompactTextString(m) }
func (*UpdatePlanResponse) ProtoMessage()    {}
func (*UpdatePlanResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_dataflow_a958fb8d2e54cbb5, []int{19}
}
func (m *UpdatePlanResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdatePlanResponse.Unmarshal(m, b)
}
func (m *UpdatePlanResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdatePlanResponse.Marshal(b, m, deterministic)
}
func (dst *UpdatePlanResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdatePlanResponse.Merge(dst, src)
}
func (m *UpdatePlanResponse) XXX_Size() int {
	return xxx_messageInfo_UpdatePlanResponse.Size(m)
}
func (m *UpdatePlanResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdatePlanResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdatePlanResponse proto.InternalMessageInfo

func (m *UpdatePlanResponse) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

func (m *UpdatePlanResponse) GetPlanId() string {
	if m != nil {
		return m.PlanId
	}
	return ""
}

type DeletePlanRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Tenant               string   `protobuf:"bytes,2,opt,name=tenant,proto3" json:"tenant,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeletePlanRequest) Reset()         { *m = DeletePlanRequest{} }
func (m *DeletePlanRequest) String() string { return proto.CompactTextString(m) }
func (*DeletePlanRequest) ProtoMessage()    {}
func (*DeletePlanRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_dataflow_a958fb8d2e54cbb5, []int{20}
}
func (m *DeletePlanRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeletePlanRequest.Unmarshal(m, b)
}
func (m *DeletePlanRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeletePlanRequest.Marshal(b, m, deterministic)
}
func (dst *DeletePlanRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeletePlanRequest.Merge(dst, src)
}
func (m *DeletePlanRequest) XXX_Size() int {
	return xxx_messageInfo_DeletePlanRequest.Size(m)
}
func (m *DeletePlanRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeletePlanRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeletePlanRequest proto.InternalMessageInfo

func (m *DeletePlanRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *DeletePlanRequest) GetTenant() string {
	if m != nil {
		return m.Tenant
	}
	return ""
}

type DeletePlanResponse struct {
	Err                  string   `protobuf:"bytes,1,opt,name=err,proto3" json:"err,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeletePlanResponse) Reset()         { *m = DeletePlanResponse{} }
func (m *DeletePlanResponse) String() string { return proto.CompactTextString(m) }
func (*DeletePlanResponse) ProtoMessage()    {}
func (*DeletePlanResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_dataflow_a958fb8d2e54cbb5, []int{21}
}
func (m *DeletePlanResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeletePlanResponse.Unmarshal(m, b)
}
func (m *DeletePlanResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeletePlanResponse.Marshal(b, m, deterministic)
}
func (dst *DeletePlanResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeletePlanResponse.Merge(dst, src)
}
func (m *DeletePlanResponse) XXX_Size() int {
	return xxx_messageInfo_DeletePlanResponse.Size(m)
}
func (m *DeletePlanResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeletePlanResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeletePlanResponse proto.InternalMessageInfo

func (m *DeletePlanResponse) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

type RunPlanRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Tenant               string   `protobuf:"bytes,2,opt,name=tenant,proto3" json:"tenant,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RunPlanRequest) Reset()         { *m = RunPlanRequest{} }
func (m *RunPlanRequest) String() string { return proto.CompactTextString(m) }
func (*RunPlanRequest) ProtoMessage()    {}
func (*RunPlanRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_dataflow_a958fb8d2e54cbb5, []int{22}
}
func (m *RunPlanRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RunPlanRequest.Unmarshal(m, b)
}
func (m *RunPlanRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RunPlanRequest.Marshal(b, m, deterministic)
}
func (dst *RunPlanRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RunPlanRequest.Merge(dst, src)
}
func (m *RunPlanRequest) XXX_Size() int {
	return xxx_messageInfo_RunPlanRequest.Size(m)
}
func (m *RunPlanRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RunPlanRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RunPlanRequest proto.InternalMessageInfo

func (m *RunPlanRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *RunPlanRequest) GetTenant() string {
	if m != nil {
		return m.Tenant
	}
	return ""
}

type RunPlanResponse struct {
	Err                  string   `protobuf:"bytes,1,opt,name=err,proto3" json:"err,omitempty"`
	JobId                string   `protobuf:"bytes,2,opt,name=jobId,proto3" json:"jobId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RunPlanResponse) Reset()         { *m = RunPlanResponse{} }
func (m *RunPlanResponse) String() string { return proto.CompactTextString(m) }
func (*RunPlanResponse) ProtoMessage()    {}
func (*RunPlanResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_dataflow_a958fb8d2e54cbb5, []int{23}
}
func (m *RunPlanResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RunPlanResponse.Unmarshal(m, b)
}
func (m *RunPlanResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RunPlanResponse.Marshal(b, m, deterministic)
}
func (dst *RunPlanResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RunPlanResponse.Merge(dst, src)
}
func (m *RunPlanResponse) XXX_Size() int {
	return xxx_messageInfo_RunPlanResponse.Size(m)
}
func (m *RunPlanResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RunPlanResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RunPlanResponse proto.InternalMessageInfo

func (m *RunPlanResponse) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

func (m *RunPlanResponse) GetJobId() string {
	if m != nil {
		return m.JobId
	}
	return ""
}

type Job struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type                 string   `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	PlanName             string   `protobuf:"bytes,3,opt,name=planName,proto3" json:"planName,omitempty"`
	PlanId               string   `protobuf:"bytes,4,opt,name=planId,proto3" json:"planId,omitempty"`
	Description          string   `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	SourceLocation       string   `protobuf:"bytes,6,opt,name=sourceLocation,proto3" json:"sourceLocation,omitempty"`
	DestLocation         string   `protobuf:"bytes,7,opt,name=destLocation,proto3" json:"destLocation,omitempty"`
	CreateTime           int64    `protobuf:"varint,8,opt,name=createTime,proto3" json:"createTime,omitempty"`
	StartTime            int64    `protobuf:"varint,9,opt,name=startTime,proto3" json:"startTime,omitempty"`
	EndTime              int64    `protobuf:"varint,10,opt,name=endTime,proto3" json:"endTime,omitempty"`
	OverWrite            bool     `protobuf:"varint,11,opt,name=overWrite,proto3" json:"overWrite,omitempty"`
	RemainSource         bool     `protobuf:"varint,12,opt,name=remainSource,proto3" json:"remainSource,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Job) Reset()         { *m = Job{} }
func (m *Job) String() string { return proto.CompactTextString(m) }
func (*Job) ProtoMessage()    {}
func (*Job) Descriptor() ([]byte, []int) {
	return fileDescriptor_dataflow_a958fb8d2e54cbb5, []int{24}
}
func (m *Job) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Job.Unmarshal(m, b)
}
func (m *Job) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Job.Marshal(b, m, deterministic)
}
func (dst *Job) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Job.Merge(dst, src)
}
func (m *Job) XXX_Size() int {
	return xxx_messageInfo_Job.Size(m)
}
func (m *Job) XXX_DiscardUnknown() {
	xxx_messageInfo_Job.DiscardUnknown(m)
}

var xxx_messageInfo_Job proto.InternalMessageInfo

func (m *Job) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Job) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Job) GetPlanName() string {
	if m != nil {
		return m.PlanName
	}
	return ""
}

func (m *Job) GetPlanId() string {
	if m != nil {
		return m.PlanId
	}
	return ""
}

func (m *Job) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Job) GetSourceLocation() string {
	if m != nil {
		return m.SourceLocation
	}
	return ""
}

func (m *Job) GetDestLocation() string {
	if m != nil {
		return m.DestLocation
	}
	return ""
}

func (m *Job) GetCreateTime() int64 {
	if m != nil {
		return m.CreateTime
	}
	return 0
}

func (m *Job) GetStartTime() int64 {
	if m != nil {
		return m.StartTime
	}
	return 0
}

func (m *Job) GetEndTime() int64 {
	if m != nil {
		return m.EndTime
	}
	return 0
}

func (m *Job) GetOverWrite() bool {
	if m != nil {
		return m.OverWrite
	}
	return false
}

func (m *Job) GetRemainSource() bool {
	if m != nil {
		return m.RemainSource
	}
	return false
}

type GetJobRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Tenant               string   `protobuf:"bytes,2,opt,name=tenant,proto3" json:"tenant,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetJobRequest) Reset()         { *m = GetJobRequest{} }
func (m *GetJobRequest) String() string { return proto.CompactTextString(m) }
func (*GetJobRequest) ProtoMessage()    {}
func (*GetJobRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_dataflow_a958fb8d2e54cbb5, []int{25}
}
func (m *GetJobRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetJobRequest.Unmarshal(m, b)
}
func (m *GetJobRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetJobRequest.Marshal(b, m, deterministic)
}
func (dst *GetJobRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetJobRequest.Merge(dst, src)
}
func (m *GetJobRequest) XXX_Size() int {
	return xxx_messageInfo_GetJobRequest.Size(m)
}
func (m *GetJobRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetJobRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetJobRequest proto.InternalMessageInfo

func (m *GetJobRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *GetJobRequest) GetTenant() string {
	if m != nil {
		return m.Tenant
	}
	return ""
}

type GetJobResponse struct {
	Err                  string   `protobuf:"bytes,1,opt,name=err,proto3" json:"err,omitempty"`
	Jobs                 []*Job   `protobuf:"bytes,2,rep,name=jobs,proto3" json:"jobs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetJobResponse) Reset()         { *m = GetJobResponse{} }
func (m *GetJobResponse) String() string { return proto.CompactTextString(m) }
func (*GetJobResponse) ProtoMessage()    {}
func (*GetJobResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_dataflow_a958fb8d2e54cbb5, []int{26}
}
func (m *GetJobResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetJobResponse.Unmarshal(m, b)
}
func (m *GetJobResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetJobResponse.Marshal(b, m, deterministic)
}
func (dst *GetJobResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetJobResponse.Merge(dst, src)
}
func (m *GetJobResponse) XXX_Size() int {
	return xxx_messageInfo_GetJobResponse.Size(m)
}
func (m *GetJobResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetJobResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetJobResponse proto.InternalMessageInfo

func (m *GetJobResponse) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

func (m *GetJobResponse) GetJobs() []*Job {
	if m != nil {
		return m.Jobs
	}
	return nil
}

func init() {
	proto.RegisterType((*Schedule)(nil), "Schedule")
	proto.RegisterType((*Policy)(nil), "Policy")
	proto.RegisterType((*GetPolicyRequest)(nil), "GetPolicyRequest")
	proto.RegisterType((*GetPolicyResponse)(nil), "GetPolicyResponse")
	proto.RegisterType((*CreatePolicyRequest)(nil), "CreatePolicyRequest")
	proto.RegisterType((*CreatePolicyResponse)(nil), "CreatePolicyResponse")
	proto.RegisterType((*UpdatePolicyRequest)(nil), "UpdatePolicyRequest")
	proto.RegisterType((*UpdatePolicyResponse)(nil), "UpdatePolicyResponse")
	proto.RegisterType((*DeletePolicyRequest)(nil), "DeletePolicyRequest")
	proto.RegisterType((*DeletePolicyResponse)(nil), "DeletePolicyResponse")
	proto.RegisterType((*KV)(nil), "KV")
	proto.RegisterType((*Filter)(nil), "Filter")
	proto.RegisterType((*Connector)(nil), "Connector")
	proto.RegisterType((*Plan)(nil), "Plan")
	proto.RegisterType((*CreatePlanRequest)(nil), "CreatePlanRequest")
	proto.RegisterType((*CreatePlanResponse)(nil), "CreatePlanResponse")
	proto.RegisterType((*GetPlanRequest)(nil), "GetPlanRequest")
	proto.RegisterType((*GetPlanResponse)(nil), "GetPlanResponse")
	proto.RegisterType((*UpdatePlanRequest)(nil), "UpdatePlanRequest")
	proto.RegisterType((*UpdatePlanResponse)(nil), "UpdatePlanResponse")
	proto.RegisterType((*DeletePlanRequest)(nil), "DeletePlanRequest")
	proto.RegisterType((*DeletePlanResponse)(nil), "DeletePlanResponse")
	proto.RegisterType((*RunPlanRequest)(nil), "RunPlanRequest")
	proto.RegisterType((*RunPlanResponse)(nil), "RunPlanResponse")
	proto.RegisterType((*Job)(nil), "Job")
	proto.RegisterType((*GetJobRequest)(nil), "GetJobRequest")
	proto.RegisterType((*GetJobResponse)(nil), "GetJobResponse")
}

func init() { proto.RegisterFile("dataflow.proto", fileDescriptor_dataflow_a958fb8d2e54cbb5) }

var fileDescriptor_dataflow_a958fb8d2e54cbb5 = []byte{
	// 982 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x56, 0xff, 0x8e, 0xe3, 0x34,
	0x10, 0x6e, 0x9b, 0xf4, 0xd7, 0x74, 0x69, 0x77, 0xa7, 0x5d, 0x14, 0xc2, 0xaf, 0xca, 0x88, 0xd5,
	0x0a, 0x90, 0x85, 0x16, 0xa4, 0x05, 0x01, 0x2b, 0xc4, 0x9e, 0xf6, 0x74, 0x77, 0x08, 0x2d, 0xb9,
	0xe3, 0xf8, 0x13, 0xa5, 0x8d, 0xf7, 0xc8, 0x6d, 0x36, 0x0e, 0x89, 0x7b, 0x47, 0x9f, 0x80, 0x27,
	0xe2, 0x91, 0x10, 0xaf, 0x81, 0x6c, 0xa7, 0x89, 0x93, 0xb4, 0x07, 0xe5, 0xfe, 0xf3, 0x7c, 0xf6,
	0x78, 0xc6, 0xe3, 0xf9, 0x3e, 0x1b, 0xc6, 0x81, 0x2f, 0xfc, 0x9b, 0x88, 0xbf, 0xa4, 0x49, 0xca,
	0x05, 0x27, 0x3f, 0xc2, 0xe0, 0xf1, 0xf2, 0x57, 0x16, 0xac, 0x22, 0x86, 0x08, 0xb6, 0x58, 0x27,
	0xcc, 0x69, 0xcf, 0xdb, 0xa7, 0x43, 0x4f, 0x8d, 0x25, 0x16, 0xf8, 0xeb, 0xcc, 0xe9, 0xcc, 0x2d,
	0x89, 0xc9, 0x31, 0xbe, 0x0b, 0x20, 0xc2, 0x3b, 0xf6, 0x4b, 0xc2, 0xc3, 0x58, 0x38, 0x96, 0x5a,
	0x3d, 0x94, 0xc8, 0xb5, 0x04, 0xc8, 0x1f, 0x6d, 0xe8, 0x5d, 0xf3, 0x28, 0x5c, 0xae, 0x71, 0x0c,
	0x9d, 0x30, 0xc8, 0xf7, 0xeb, 0x84, 0x81, 0xdc, 0x2d, 0xf6, 0xef, 0x98, 0xd3, 0xd1, 0x11, 0xe4,
	0x18, 0xdf, 0x84, 0x9e, 0x60, 0xb1, 0x5f, 0xec, 0x94, 0x5b, 0x38, 0x87, 0x51, 0xc0, 0xb2, 0x65,
	0x1a, 0x26, 0x22, 0xe4, 0xb1, 0x63, 0xab, 0x49, 0x13, 0xc2, 0xf7, 0xa1, 0x9b, 0xc9, 0xdc, 0x9d,
	0xee, 0xbc, 0x7d, 0x3a, 0x3a, 0x1b, 0xd2, 0xcd, 0x49, 0x3c, 0x8d, 0x93, 0x0b, 0x38, 0xbc, 0xcf,
	0x84, 0xce, 0xc5, 0x63, 0xbf, 0xad, 0x58, 0x26, 0x8a, 0x14, 0xda, 0x5b, 0x53, 0xe8, 0x98, 0x29,
	0x90, 0xef, 0xe0, 0xc8, 0xf0, 0xcf, 0x12, 0x1e, 0x67, 0x0c, 0x0f, 0xc1, 0x62, 0x69, 0x9a, 0xfb,
	0xcb, 0x21, 0xbe, 0x0d, 0x76, 0xc2, 0x23, 0x5d, 0xa3, 0xd1, 0x59, 0x9f, 0xe6, 0x0e, 0x0a, 0x24,
	0x9f, 0xc2, 0xf4, 0x32, 0x65, 0xbe, 0x60, 0xd5, 0x34, 0xde, 0x02, 0x2b, 0xe1, 0x91, 0xda, 0xc5,
	0x70, 0x91, 0x18, 0xb9, 0x80, 0x59, 0xd5, 0x63, 0x67, 0xe0, 0x19, 0x74, 0x13, 0x1e, 0x3d, 0x08,
	0xf2, 0xb4, 0xb5, 0x21, 0x23, 0xfe, 0x94, 0x04, 0x7b, 0x46, 0xac, 0x7a, 0xec, 0x19, 0xf1, 0x43,
	0x98, 0xde, 0x63, 0x11, 0xab, 0x47, 0xac, 0xdd, 0x3e, 0x39, 0x85, 0x59, 0x75, 0xd9, 0xae, 0x30,
	0xe4, 0x13, 0xe8, 0x3c, 0x7a, 0x2a, 0xf1, 0x5b, 0xb6, 0xde, 0xe0, 0xb7, 0x6c, 0x2d, 0xc3, 0xbf,
	0xf0, 0xa3, 0xd5, 0xa6, 0x81, 0xb4, 0x41, 0xce, 0xa1, 0x77, 0x15, 0x46, 0x82, 0xa5, 0xf2, 0x22,
	0x93, 0x94, 0xdd, 0x84, 0xbf, 0xe7, 0x4e, 0xb9, 0x85, 0xc7, 0x60, 0x09, 0xff, 0x59, 0x7e, 0x41,
	0x16, 0x7d, 0xf4, 0xd4, 0x93, 0x36, 0x89, 0x60, 0x78, 0xc9, 0xe3, 0x98, 0x2d, 0x05, 0x4f, 0xd1,
	0x85, 0x41, 0x26, 0x78, 0xfa, 0xa4, 0x64, 0x40, 0x61, 0xe3, 0x7b, 0x00, 0x8b, 0xd5, 0xf2, 0x96,
	0x89, 0x1f, 0xca, 0xee, 0x35, 0x10, 0xfc, 0x00, 0x60, 0xc9, 0xe3, 0xf8, 0x92, 0xc7, 0x37, 0xe1,
	0x33, 0xc7, 0x2a, 0xc3, 0x18, 0x30, 0xf9, 0xbb, 0x03, 0xf6, 0x75, 0xe4, 0xc7, 0xff, 0x89, 0x15,
	0xb5, 0xee, 0xb7, 0x9a, 0xdd, 0xbf, 0x61, 0xab, 0x6d, 0xb0, 0xd5, 0x85, 0x41, 0xa2, 0x6a, 0xfb,
	0x40, 0x93, 0x62, 0xe8, 0x15, 0xb6, 0x3c, 0x83, 0x1e, 0xab, 0x33, 0xf4, 0xf4, 0x19, 0x4a, 0x04,
	0x3f, 0x02, 0xc8, 0xf8, 0x2a, 0x5d, 0x32, 0x59, 0x12, 0xa7, 0xaf, 0xda, 0x04, 0x68, 0x51, 0x1f,
	0xcf, 0x98, 0xc5, 0x13, 0x18, 0x04, 0x2c, 0x13, 0x6a, 0xe5, 0xa0, 0xb1, 0xb2, 0x98, 0x93, 0xcc,
	0xb8, 0x09, 0x23, 0xe1, 0x0c, 0xf3, 0xa6, 0xd3, 0xd7, 0xe4, 0x29, 0x10, 0xdf, 0x81, 0x21, 0x7f,
	0xc1, 0xd2, 0x9f, 0xd3, 0x50, 0x30, 0x07, 0xe6, 0xed, 0xd3, 0x81, 0x57, 0x02, 0x48, 0xe0, 0x20,
	0x65, 0x77, 0x7e, 0x18, 0x3f, 0x56, 0x61, 0x9d, 0x91, 0x5a, 0x50, 0xc1, 0x0c, 0xde, 0x1e, 0x54,
	0x78, 0x7b, 0x05, 0x47, 0x39, 0x83, 0x22, 0x3f, 0x2e, 0xfb, 0xdf, 0x4e, 0x22, 0x3f, 0xce, 0x09,
	0xd0, 0xa5, 0x6a, 0x4e, 0x41, 0x3b, 0xf9, 0x7f, 0x01, 0x68, 0xee, 0xb3, 0x93, 0x15, 0xb2, 0xed,
	0x22, 0x3f, 0x2e, 0x68, 0x91, 0x5b, 0xe4, 0x6b, 0x18, 0x4b, 0xfd, 0x30, 0x92, 0xd8, 0x47, 0x7d,
	0xbe, 0x85, 0x49, 0xe1, 0xfd, 0x0a, 0xed, 0xe9, 0xca, 0x60, 0x1b, 0xf1, 0xc9, 0x8f, 0xa5, 0x31,
	0x59, 0x87, 0x9c, 0xd7, 0xaf, 0x5d, 0x07, 0x73, 0x9f, 0xbd, 0xeb, 0xf0, 0x15, 0x1c, 0xe5, 0xc4,
	0x37, 0xf2, 0xa8, 0xb3, 0x60, 0x57, 0xf0, 0x13, 0x40, 0xd3, 0x79, 0xa7, 0x66, 0x7c, 0x01, 0x63,
	0x6f, 0x15, 0xff, 0x9f, 0x08, 0x5f, 0xc2, 0xa4, 0xf0, 0x7c, 0x95, 0xf2, 0x3d, 0xe7, 0x8b, 0x52,
	0xf9, 0x94, 0x41, 0xfe, 0xea, 0x80, 0xf5, 0x90, 0x2f, 0xb6, 0x51, 0x5a, 0x91, 0xb3, 0x53, 0x23,
	0x67, 0xe4, 0xc7, 0x8a, 0x7e, 0x56, 0x4e, 0xce, 0xdc, 0x36, 0x2a, 0x67, 0x9b, 0x95, 0xab, 0xcb,
	0x40, 0xb7, 0x29, 0x03, 0x27, 0x30, 0xd6, 0xc4, 0xfc, 0x9e, 0x2f, 0x7d, 0xb5, 0x48, 0x53, 0xbb,
	0x86, 0x4a, 0x3e, 0x49, 0x5a, 0x16, 0xab, 0xfa, 0x6a, 0x55, 0x05, 0x93, 0x12, 0xb1, 0x54, 0xfd,
	0xfe, 0x24, 0xbc, 0x63, 0x8a, 0xd8, 0x96, 0x67, 0x20, 0x92, 0xb1, 0x99, 0xf0, 0x53, 0xa1, 0xa6,
	0x87, 0x6a, 0xba, 0x04, 0xd0, 0x81, 0x3e, 0x8b, 0x03, 0x35, 0x07, 0x6a, 0x6e, 0x63, 0x56, 0x99,
	0x3e, 0xfa, 0x37, 0xa6, 0x1f, 0x34, 0x99, 0x4e, 0xce, 0xe1, 0x8d, 0xfb, 0x4c, 0x3c, 0xe4, 0x8b,
	0x7d, 0xef, 0x56, 0x53, 0x50, 0x39, 0xee, 0xbc, 0x5a, 0x07, 0xec, 0xe7, 0x7c, 0xb1, 0xa1, 0x90,
	0x4d, 0xe5, 0x6a, 0x85, 0x9c, 0xfd, 0x69, 0xc3, 0xe0, 0x9e, 0x2f, 0xfc, 0xab, 0x88, 0xbf, 0xc4,
	0xcf, 0x61, 0x58, 0xfc, 0x06, 0xf0, 0x88, 0xd6, 0x7f, 0x16, 0x2e, 0xd2, 0xc6, 0x67, 0x81, 0xb4,
	0xf0, 0x1b, 0x38, 0x30, 0x5f, 0x73, 0x9c, 0xd1, 0x2d, 0xdf, 0x01, 0xf7, 0x98, 0x6e, 0x7b, 0xf2,
	0xb5, 0xbb, 0xf9, 0x34, 0xe3, 0x8c, 0x6e, 0x79, 0xdb, 0xdd, 0x63, 0xba, 0xed, 0xfd, 0xd6, 0xee,
	0xe6, 0x93, 0x8b, 0x33, 0xba, 0xe5, 0xa1, 0x76, 0x8f, 0xe9, 0xb6, 0x77, 0x99, 0xb4, 0x90, 0x42,
	0x3f, 0x97, 0x20, 0x9c, 0xd0, 0xaa, 0x94, 0xb9, 0x87, 0xb4, 0xa6, 0x4e, 0xa4, 0x85, 0xe7, 0x00,
	0xa5, 0x60, 0x22, 0xd2, 0x86, 0x0a, 0xbb, 0x53, 0xda, 0x54, 0x54, 0xed, 0x58, 0x2a, 0x0c, 0x22,
	0x6d, 0xc8, 0x96, 0x3b, 0xa5, 0x4d, 0x09, 0xd2, 0x8e, 0xa5, 0x3a, 0x20, 0xd2, 0x86, 0xce, 0xb8,
	0x53, 0xda, 0x94, 0x0f, 0xd2, 0xc2, 0x8f, 0xa1, 0xa7, 0x1b, 0x03, 0xc7, 0xb4, 0xd2, 0x5a, 0xee,
	0x84, 0x56, 0x3b, 0x46, 0xd7, 0x21, 0x57, 0x08, 0x9c, 0xd0, 0xaa, 0xca, 0xb8, 0x87, 0xb4, 0x26,
	0x1e, 0xa4, 0xb5, 0xe8, 0xa9, 0xcf, 0xf5, 0x67, 0xff, 0x04, 0x00, 0x00, 0xff, 0xff, 0x0f, 0x7b,
	0x01, 0xb9, 0x6e, 0x0b, 0x00, 0x00,
}
