// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.2.0
// source: aksk/proto/aksk.proto

package proto

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type CreateAkSkRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AkSk *AkSkDetail `protobuf:"bytes,1,opt,name=AkSk,proto3" json:"AkSk,omitempty"`
}

func (x *CreateAkSkRequest) Reset() {
	*x = CreateAkSkRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_aksk_proto_aksk_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateAkSkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAkSkRequest) ProtoMessage() {}

func (x *CreateAkSkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aksk_proto_aksk_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAkSkRequest.ProtoReflect.Descriptor instead.
func (*CreateAkSkRequest) Descriptor() ([]byte, []int) {
	return file_aksk_proto_aksk_proto_rawDescGZIP(), []int{0}
}

func (x *CreateAkSkRequest) GetAkSk() *AkSkDetail {
	if x != nil {
		return x.AkSk
	}
	return nil
}

type CreateAkSkResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AkSk *AkSkDetail `protobuf:"bytes,1,opt,name=AkSk,proto3" json:"AkSk,omitempty"`
}

func (x *CreateAkSkResponse) Reset() {
	*x = CreateAkSkResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_aksk_proto_aksk_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateAkSkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAkSkResponse) ProtoMessage() {}

func (x *CreateAkSkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_aksk_proto_aksk_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAkSkResponse.ProtoReflect.Descriptor instead.
func (*CreateAkSkResponse) Descriptor() ([]byte, []int) {
	return file_aksk_proto_aksk_proto_rawDescGZIP(), []int{1}
}

func (x *CreateAkSkResponse) GetAkSk() *AkSkDetail {
	if x != nil {
		return x.AkSk
	}
	return nil
}

type GetAkSkRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetAkSkRequest) Reset() {
	*x = GetAkSkRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_aksk_proto_aksk_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAkSkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAkSkRequest) ProtoMessage() {}

func (x *GetAkSkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aksk_proto_aksk_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAkSkRequest.ProtoReflect.Descriptor instead.
func (*GetAkSkRequest) Descriptor() ([]byte, []int) {
	return file_aksk_proto_aksk_proto_rawDescGZIP(), []int{2}
}

func (x *GetAkSkRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetAkSkResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AkSk *AkSkDetail `protobuf:"bytes,1,opt,name=AkSk,proto3" json:"AkSk,omitempty"`
}

func (x *GetAkSkResponse) Reset() {
	*x = GetAkSkResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_aksk_proto_aksk_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAkSkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAkSkResponse) ProtoMessage() {}

func (x *GetAkSkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_aksk_proto_aksk_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAkSkResponse.ProtoReflect.Descriptor instead.
func (*GetAkSkResponse) Descriptor() ([]byte, []int) {
	return file_aksk_proto_aksk_proto_rawDescGZIP(), []int{3}
}

func (x *GetAkSkResponse) GetAkSk() *AkSkDetail {
	if x != nil {
		return x.AkSk
	}
	return nil
}

type ListAkSkRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Limit    int32             `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset   int32             `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	SortKeys []string          `protobuf:"bytes,3,rep,name=sortKeys,proto3" json:"sortKeys,omitempty"`
	SortDirs []string          `protobuf:"bytes,4,rep,name=sortDirs,proto3" json:"sortDirs,omitempty"`
	Filter   map[string]string `protobuf:"bytes,5,rep,name=Filter,proto3" json:"Filter,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *ListAkSkRequest) Reset() {
	*x = ListAkSkRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_aksk_proto_aksk_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListAkSkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAkSkRequest) ProtoMessage() {}

func (x *ListAkSkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aksk_proto_aksk_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAkSkRequest.ProtoReflect.Descriptor instead.
func (*ListAkSkRequest) Descriptor() ([]byte, []int) {
	return file_aksk_proto_aksk_proto_rawDescGZIP(), []int{4}
}

func (x *ListAkSkRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListAkSkRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ListAkSkRequest) GetSortKeys() []string {
	if x != nil {
		return x.SortKeys
	}
	return nil
}

func (x *ListAkSkRequest) GetSortDirs() []string {
	if x != nil {
		return x.SortDirs
	}
	return nil
}

func (x *ListAkSkRequest) GetFilter() map[string]string {
	if x != nil {
		return x.Filter
	}
	return nil
}

type ListAkSkResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AkSks []*AkSkDetail `protobuf:"bytes,1,rep,name=AkSks,proto3" json:"AkSks,omitempty"`
	Next  int32         `protobuf:"varint,2,opt,name=next,proto3" json:"next,omitempty"`
}

func (x *ListAkSkResponse) Reset() {
	*x = ListAkSkResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_aksk_proto_aksk_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListAkSkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAkSkResponse) ProtoMessage() {}

func (x *ListAkSkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_aksk_proto_aksk_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAkSkResponse.ProtoReflect.Descriptor instead.
func (*ListAkSkResponse) Descriptor() ([]byte, []int) {
	return file_aksk_proto_aksk_proto_rawDescGZIP(), []int{5}
}

func (x *ListAkSkResponse) GetAkSks() []*AkSkDetail {
	if x != nil {
		return x.AkSks
	}
	return nil
}

func (x *ListAkSkResponse) GetNext() int32 {
	if x != nil {
		return x.Next
	}
	return 0
}

type DeleteAkSkRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DeleteAkSkRequest) Reset() {
	*x = DeleteAkSkRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_aksk_proto_aksk_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteAkSkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAkSkRequest) ProtoMessage() {}

func (x *DeleteAkSkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aksk_proto_aksk_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAkSkRequest.ProtoReflect.Descriptor instead.
func (*DeleteAkSkRequest) Descriptor() ([]byte, []int) {
	return file_aksk_proto_aksk_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteAkSkRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteAkSkResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteAkSkResponse) Reset() {
	*x = DeleteAkSkResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_aksk_proto_aksk_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteAkSkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAkSkResponse) ProtoMessage() {}

func (x *DeleteAkSkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_aksk_proto_aksk_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAkSkResponse.ProtoReflect.Descriptor instead.
func (*DeleteAkSkResponse) Descriptor() ([]byte, []int) {
	return file_aksk_proto_aksk_proto_rawDescGZIP(), []int{7}
}

type AkSkDetail struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProjectId string `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	UserId    string `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Blob      string `protobuf:"bytes,3,opt,name=blob,proto3" json:"blob,omitempty"`
	Type      string `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
}

func (x *AkSkDetail) Reset() {
	*x = AkSkDetail{}
	if protoimpl.UnsafeEnabled {
		mi := &file_aksk_proto_aksk_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AkSkDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AkSkDetail) ProtoMessage() {}

func (x *AkSkDetail) ProtoReflect() protoreflect.Message {
	mi := &file_aksk_proto_aksk_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AkSkDetail.ProtoReflect.Descriptor instead.
func (*AkSkDetail) Descriptor() ([]byte, []int) {
	return file_aksk_proto_aksk_proto_rawDescGZIP(), []int{8}
}

func (x *AkSkDetail) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *AkSkDetail) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AkSkDetail) GetBlob() string {
	if x != nil {
		return x.Blob
	}
	return ""
}

func (x *AkSkDetail) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

var File_aksk_proto_aksk_proto protoreflect.FileDescriptor

var file_aksk_proto_aksk_proto_rawDesc = []byte{
	0x0a, 0x15, 0x61, 0x6b, 0x73, 0x6b, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x61, 0x6b, 0x73,
	0x6b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x34, 0x0a, 0x11, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x41, 0x6b, 0x53, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1f, 0x0a, 0x04,
	0x41, 0x6b, 0x53, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x41, 0x6b, 0x53,
	0x6b, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x52, 0x04, 0x41, 0x6b, 0x53, 0x6b, 0x22, 0x35, 0x0a,
	0x12, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x6b, 0x53, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x1f, 0x0a, 0x04, 0x41, 0x6b, 0x53, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0b, 0x2e, 0x41, 0x6b, 0x53, 0x6b, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x52, 0x04,
	0x41, 0x6b, 0x53, 0x6b, 0x22, 0x20, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x41, 0x6b, 0x53, 0x6b, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x32, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x41, 0x6b, 0x53,
	0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1f, 0x0a, 0x04, 0x41, 0x6b, 0x53,
	0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x41, 0x6b, 0x53, 0x6b, 0x44, 0x65,
	0x74, 0x61, 0x69, 0x6c, 0x52, 0x04, 0x41, 0x6b, 0x53, 0x6b, 0x22, 0xe8, 0x01, 0x0a, 0x0f, 0x4c,
	0x69, 0x73, 0x74, 0x41, 0x6b, 0x53, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14,
	0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x6c,
	0x69, 0x6d, 0x69, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x12, 0x1a, 0x0a, 0x08,
	0x73, 0x6f, 0x72, 0x74, 0x4b, 0x65, 0x79, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x08,
	0x73, 0x6f, 0x72, 0x74, 0x4b, 0x65, 0x79, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x6f, 0x72, 0x74,
	0x44, 0x69, 0x72, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x09, 0x52, 0x08, 0x73, 0x6f, 0x72, 0x74,
	0x44, 0x69, 0x72, 0x73, 0x12, 0x34, 0x0a, 0x06, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x18, 0x05,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x41, 0x6b, 0x53, 0x6b, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x45, 0x6e, 0x74,
	0x72, 0x79, 0x52, 0x06, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x1a, 0x39, 0x0a, 0x0b, 0x46, 0x69,
	0x6c, 0x74, 0x65, 0x72, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x49, 0x0a, 0x10, 0x4c, 0x69, 0x73, 0x74, 0x41, 0x6b, 0x53,
	0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x21, 0x0a, 0x05, 0x41, 0x6b, 0x53,
	0x6b, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x41, 0x6b, 0x53, 0x6b, 0x44,
	0x65, 0x74, 0x61, 0x69, 0x6c, 0x52, 0x05, 0x41, 0x6b, 0x53, 0x6b, 0x73, 0x12, 0x12, 0x0a, 0x04,
	0x6e, 0x65, 0x78, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x6e, 0x65, 0x78, 0x74,
	0x22, 0x23, 0x0a, 0x11, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x41, 0x6b, 0x53, 0x6b, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x14, 0x0a, 0x12, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x41,
	0x6b, 0x53, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x6c, 0x0a, 0x0a, 0x41,
	0x6b, 0x53, 0x6b, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x72, 0x6f,
	0x6a, 0x65, 0x63, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x70,
	0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72,
	0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49,
	0x64, 0x12, 0x12, 0x0a, 0x04, 0x62, 0x6c, 0x6f, 0x62, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x62, 0x6c, 0x6f, 0x62, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x32, 0xdb, 0x01, 0x0a, 0x04, 0x41, 0x6b,
	0x53, 0x6b, 0x12, 0x37, 0x0a, 0x0a, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x6b, 0x53, 0x6b,
	0x12, 0x12, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x6b, 0x53, 0x6b, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x13, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x6b, 0x53,
	0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x2e, 0x0a, 0x07, 0x47,
	0x65, 0x74, 0x41, 0x6b, 0x53, 0x6b, 0x12, 0x0f, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x6b, 0x53, 0x6b,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x10, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x6b, 0x53,
	0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x31, 0x0a, 0x08, 0x4c,
	0x69, 0x73, 0x74, 0x41, 0x6b, 0x53, 0x6b, 0x12, 0x10, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x41, 0x6b,
	0x53, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x11, 0x2e, 0x4c, 0x69, 0x73, 0x74,
	0x41, 0x6b, 0x53, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x37,
	0x0a, 0x0a, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x41, 0x6b, 0x53, 0x6b, 0x12, 0x12, 0x2e, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x41, 0x6b, 0x53, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x13, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x41, 0x6b, 0x53, 0x6b, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x0c, 0x5a, 0x0a, 0x61, 0x6b, 0x73, 0x6b, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_aksk_proto_aksk_proto_rawDescOnce sync.Once
	file_aksk_proto_aksk_proto_rawDescData = file_aksk_proto_aksk_proto_rawDesc
)

func file_aksk_proto_aksk_proto_rawDescGZIP() []byte {
	file_aksk_proto_aksk_proto_rawDescOnce.Do(func() {
		file_aksk_proto_aksk_proto_rawDescData = protoimpl.X.CompressGZIP(file_aksk_proto_aksk_proto_rawDescData)
	})
	return file_aksk_proto_aksk_proto_rawDescData
}

var file_aksk_proto_aksk_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_aksk_proto_aksk_proto_goTypes = []interface{}{
	(*CreateAkSkRequest)(nil),  // 0: CreateAkSkRequest
	(*CreateAkSkResponse)(nil), // 1: CreateAkSkResponse
	(*GetAkSkRequest)(nil),     // 2: GetAkSkRequest
	(*GetAkSkResponse)(nil),    // 3: GetAkSkResponse
	(*ListAkSkRequest)(nil),    // 4: ListAkSkRequest
	(*ListAkSkResponse)(nil),   // 5: ListAkSkResponse
	(*DeleteAkSkRequest)(nil),  // 6: DeleteAkSkRequest
	(*DeleteAkSkResponse)(nil), // 7: DeleteAkSkResponse
	(*AkSkDetail)(nil),         // 8: AkSkDetail
	nil,                        // 9: ListAkSkRequest.FilterEntry
}
var file_aksk_proto_aksk_proto_depIdxs = []int32{
	8, // 0: CreateAkSkRequest.AkSk:type_name -> AkSkDetail
	8, // 1: CreateAkSkResponse.AkSk:type_name -> AkSkDetail
	8, // 2: GetAkSkResponse.AkSk:type_name -> AkSkDetail
	9, // 3: ListAkSkRequest.Filter:type_name -> ListAkSkRequest.FilterEntry
	8, // 4: ListAkSkResponse.AkSks:type_name -> AkSkDetail
	0, // 5: AkSk.CreateAkSk:input_type -> CreateAkSkRequest
	2, // 6: AkSk.GetAkSk:input_type -> GetAkSkRequest
	4, // 7: AkSk.ListAkSk:input_type -> ListAkSkRequest
	6, // 8: AkSk.DeleteAkSk:input_type -> DeleteAkSkRequest
	1, // 9: AkSk.CreateAkSk:output_type -> CreateAkSkResponse
	3, // 10: AkSk.GetAkSk:output_type -> GetAkSkResponse
	5, // 11: AkSk.ListAkSk:output_type -> ListAkSkResponse
	7, // 12: AkSk.DeleteAkSk:output_type -> DeleteAkSkResponse
	9, // [9:13] is the sub-list for method output_type
	5, // [5:9] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_aksk_proto_aksk_proto_init() }
func file_aksk_proto_aksk_proto_init() {
	if File_aksk_proto_aksk_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_aksk_proto_aksk_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateAkSkRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_aksk_proto_aksk_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateAkSkResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_aksk_proto_aksk_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAkSkRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_aksk_proto_aksk_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAkSkResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_aksk_proto_aksk_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListAkSkRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_aksk_proto_aksk_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListAkSkResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_aksk_proto_aksk_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteAkSkRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_aksk_proto_aksk_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteAkSkResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_aksk_proto_aksk_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AkSkDetail); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_aksk_proto_aksk_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_aksk_proto_aksk_proto_goTypes,
		DependencyIndexes: file_aksk_proto_aksk_proto_depIdxs,
		MessageInfos:      file_aksk_proto_aksk_proto_msgTypes,
	}.Build()
	File_aksk_proto_aksk_proto = out.File
	file_aksk_proto_aksk_proto_rawDesc = nil
	file_aksk_proto_aksk_proto_goTypes = nil
	file_aksk_proto_aksk_proto_depIdxs = nil
}
