// Code generated by protoc-gen-go. DO NOT EDIT.
// source: s3.proto

package s3

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ACL struct {
	Canned               string   `protobuf:"bytes,1,opt,name=canned,proto3" json:"canned,omitempty"`
	FULL_CONTROL         []string `protobuf:"bytes,2,rep,name=FULL_CONTROL,json=FULLCONTROL,proto3" json:"FULL_CONTROL,omitempty"`
	WRITE                []string `protobuf:"bytes,3,rep,name=WRITE,proto3" json:"WRITE,omitempty"`
	WRITE_ACP            []string `protobuf:"bytes,4,rep,name=WRITE_ACP,json=WRITEACP,proto3" json:"WRITE_ACP,omitempty"`
	READ                 []string `protobuf:"bytes,5,rep,name=READ,proto3" json:"READ,omitempty"`
	READ_ACP             []string `protobuf:"bytes,6,rep,name=READ_ACP,json=READACP,proto3" json:"READ_ACP,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ACL) Reset()         { *m = ACL{} }
func (m *ACL) String() string { return proto.CompactTextString(m) }
func (*ACL) ProtoMessage()    {}
func (*ACL) Descriptor() ([]byte, []int) {
	return fileDescriptor_005e34be4304e022, []int{0}
}

func (m *ACL) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ACL.Unmarshal(m, b)
}
func (m *ACL) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ACL.Marshal(b, m, deterministic)
}
func (m *ACL) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ACL.Merge(m, src)
}
func (m *ACL) XXX_Size() int {
	return xxx_messageInfo_ACL.Size(m)
}
func (m *ACL) XXX_DiscardUnknown() {
	xxx_messageInfo_ACL.DiscardUnknown(m)
}

var xxx_messageInfo_ACL proto.InternalMessageInfo

func (m *ACL) GetCanned() string {
	if m != nil {
		return m.Canned
	}
	return ""
}

func (m *ACL) GetFULL_CONTROL() []string {
	if m != nil {
		return m.FULL_CONTROL
	}
	return nil
}

func (m *ACL) GetWRITE() []string {
	if m != nil {
		return m.WRITE
	}
	return nil
}

func (m *ACL) GetWRITE_ACP() []string {
	if m != nil {
		return m.WRITE_ACP
	}
	return nil
}

func (m *ACL) GetREAD() []string {
	if m != nil {
		return m.READ
	}
	return nil
}

func (m *ACL) GetREAD_ACP() []string {
	if m != nil {
		return m.READ_ACP
	}
	return nil
}

type ServerSideEncryption struct {
	CryptScheme          string   `protobuf:"bytes,1,opt,name=cryptScheme,proto3" json:"cryptScheme,omitempty"`
	Algorithm            string   `protobuf:"bytes,2,opt,name=algorithm,proto3" json:"algorithm,omitempty"`
	MasterKeyId          string   `protobuf:"bytes,3,opt,name=masterKeyId,proto3" json:"masterKeyId,omitempty"`
	Mandtory             bool     `protobuf:"varint,4,opt,name=mandtory,proto3" json:"mandtory,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ServerSideEncryption) Reset()         { *m = ServerSideEncryption{} }
func (m *ServerSideEncryption) String() string { return proto.CompactTextString(m) }
func (*ServerSideEncryption) ProtoMessage()    {}
func (*ServerSideEncryption) Descriptor() ([]byte, []int) {
	return fileDescriptor_005e34be4304e022, []int{1}
}

func (m *ServerSideEncryption) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServerSideEncryption.Unmarshal(m, b)
}
func (m *ServerSideEncryption) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServerSideEncryption.Marshal(b, m, deterministic)
}
func (m *ServerSideEncryption) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServerSideEncryption.Merge(m, src)
}
func (m *ServerSideEncryption) XXX_Size() int {
	return xxx_messageInfo_ServerSideEncryption.Size(m)
}
func (m *ServerSideEncryption) XXX_DiscardUnknown() {
	xxx_messageInfo_ServerSideEncryption.DiscardUnknown(m)
}

var xxx_messageInfo_ServerSideEncryption proto.InternalMessageInfo

func (m *ServerSideEncryption) GetCryptScheme() string {
	if m != nil {
		return m.CryptScheme
	}
	return ""
}

func (m *ServerSideEncryption) GetAlgorithm() string {
	if m != nil {
		return m.Algorithm
	}
	return ""
}

func (m *ServerSideEncryption) GetMasterKeyId() string {
	if m != nil {
		return m.MasterKeyId
	}
	return ""
}

func (m *ServerSideEncryption) GetMandtory() bool {
	if m != nil {
		return m.Mandtory
	}
	return false
}

type VersioningConfiguration struct {
	Status               string   `protobuf:"bytes,1,opt,name=Status,proto3" json:"Status,omitempty"`
	MfaDelete            string   `protobuf:"bytes,2,opt,name=MfaDelete,proto3" json:"MfaDelete,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VersioningConfiguration) Reset()         { *m = VersioningConfiguration{} }
func (m *VersioningConfiguration) String() string { return proto.CompactTextString(m) }
func (*VersioningConfiguration) ProtoMessage()    {}
func (*VersioningConfiguration) Descriptor() ([]byte, []int) {
	return fileDescriptor_005e34be4304e022, []int{2}
}

func (m *VersioningConfiguration) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VersioningConfiguration.Unmarshal(m, b)
}
func (m *VersioningConfiguration) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VersioningConfiguration.Marshal(b, m, deterministic)
}
func (m *VersioningConfiguration) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VersioningConfiguration.Merge(m, src)
}
func (m *VersioningConfiguration) XXX_Size() int {
	return xxx_messageInfo_VersioningConfiguration.Size(m)
}
func (m *VersioningConfiguration) XXX_DiscardUnknown() {
	xxx_messageInfo_VersioningConfiguration.DiscardUnknown(m)
}

var xxx_messageInfo_VersioningConfiguration proto.InternalMessageInfo

func (m *VersioningConfiguration) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *VersioningConfiguration) GetMfaDelete() string {
	if m != nil {
		return m.MfaDelete
	}
	return ""
}

type RedirectAllRequestsTo struct {
	HostName             string   `protobuf:"bytes,1,opt,name=hostName,proto3" json:"hostName,omitempty"`
	Protocol             []string `protobuf:"bytes,2,rep,name=protocol,proto3" json:"protocol,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RedirectAllRequestsTo) Reset()         { *m = RedirectAllRequestsTo{} }
func (m *RedirectAllRequestsTo) String() string { return proto.CompactTextString(m) }
func (*RedirectAllRequestsTo) ProtoMessage()    {}
func (*RedirectAllRequestsTo) Descriptor() ([]byte, []int) {
	return fileDescriptor_005e34be4304e022, []int{3}
}

func (m *RedirectAllRequestsTo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RedirectAllRequestsTo.Unmarshal(m, b)
}
func (m *RedirectAllRequestsTo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RedirectAllRequestsTo.Marshal(b, m, deterministic)
}
func (m *RedirectAllRequestsTo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RedirectAllRequestsTo.Merge(m, src)
}
func (m *RedirectAllRequestsTo) XXX_Size() int {
	return xxx_messageInfo_RedirectAllRequestsTo.Size(m)
}
func (m *RedirectAllRequestsTo) XXX_DiscardUnknown() {
	xxx_messageInfo_RedirectAllRequestsTo.DiscardUnknown(m)
}

var xxx_messageInfo_RedirectAllRequestsTo proto.InternalMessageInfo

func (m *RedirectAllRequestsTo) GetHostName() string {
	if m != nil {
		return m.HostName
	}
	return ""
}

func (m *RedirectAllRequestsTo) GetProtocol() []string {
	if m != nil {
		return m.Protocol
	}
	return nil
}

type Redirect struct {
	Protocol             string   `protobuf:"bytes,1,opt,name=protocol,proto3" json:"protocol,omitempty"`
	HostName             string   `protobuf:"bytes,2,opt,name=hostName,proto3" json:"hostName,omitempty"`
	ReplaceKeyPrefixWith string   `protobuf:"bytes,3,opt,name=replaceKeyPrefixWith,proto3" json:"replaceKeyPrefixWith,omitempty"`
	ReplaceKeyWith       string   `protobuf:"bytes,4,opt,name=replaceKeyWith,proto3" json:"replaceKeyWith,omitempty"`
	HttpRedirectCode     string   `protobuf:"bytes,5,opt,name=httpRedirectCode,proto3" json:"httpRedirectCode,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Redirect) Reset()         { *m = Redirect{} }
func (m *Redirect) String() string { return proto.CompactTextString(m) }
func (*Redirect) ProtoMessage()    {}
func (*Redirect) Descriptor() ([]byte, []int) {
	return fileDescriptor_005e34be4304e022, []int{4}
}

func (m *Redirect) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Redirect.Unmarshal(m, b)
}
func (m *Redirect) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Redirect.Marshal(b, m, deterministic)
}
func (m *Redirect) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Redirect.Merge(m, src)
}
func (m *Redirect) XXX_Size() int {
	return xxx_messageInfo_Redirect.Size(m)
}
func (m *Redirect) XXX_DiscardUnknown() {
	xxx_messageInfo_Redirect.DiscardUnknown(m)
}

var xxx_messageInfo_Redirect proto.InternalMessageInfo

func (m *Redirect) GetProtocol() string {
	if m != nil {
		return m.Protocol
	}
	return ""
}

func (m *Redirect) GetHostName() string {
	if m != nil {
		return m.HostName
	}
	return ""
}

func (m *Redirect) GetReplaceKeyPrefixWith() string {
	if m != nil {
		return m.ReplaceKeyPrefixWith
	}
	return ""
}

func (m *Redirect) GetReplaceKeyWith() string {
	if m != nil {
		return m.ReplaceKeyWith
	}
	return ""
}

func (m *Redirect) GetHttpRedirectCode() string {
	if m != nil {
		return m.HttpRedirectCode
	}
	return ""
}

type Condition struct {
	KeyPrefixEquals             string   `protobuf:"bytes,1,opt,name=keyPrefixEquals,proto3" json:"keyPrefixEquals,omitempty"`
	HttpErrorCodeReturnedEquals string   `protobuf:"bytes,2,opt,name=httpErrorCodeReturnedEquals,proto3" json:"httpErrorCodeReturnedEquals,omitempty"`
	XXX_NoUnkeyedLiteral        struct{} `json:"-"`
	XXX_unrecognized            []byte   `json:"-"`
	XXX_sizecache               int32    `json:"-"`
}

func (m *Condition) Reset()         { *m = Condition{} }
func (m *Condition) String() string { return proto.CompactTextString(m) }
func (*Condition) ProtoMessage()    {}
func (*Condition) Descriptor() ([]byte, []int) {
	return fileDescriptor_005e34be4304e022, []int{5}
}

func (m *Condition) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Condition.Unmarshal(m, b)
}
func (m *Condition) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Condition.Marshal(b, m, deterministic)
}
func (m *Condition) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Condition.Merge(m, src)
}
func (m *Condition) XXX_Size() int {
	return xxx_messageInfo_Condition.Size(m)
}
func (m *Condition) XXX_DiscardUnknown() {
	xxx_messageInfo_Condition.DiscardUnknown(m)
}

var xxx_messageInfo_Condition proto.InternalMessageInfo

func (m *Condition) GetKeyPrefixEquals() string {
	if m != nil {
		return m.KeyPrefixEquals
	}
	return ""
}

func (m *Condition) GetHttpErrorCodeReturnedEquals() string {
	if m != nil {
		return m.HttpErrorCodeReturnedEquals
	}
	return ""
}

type RoutingRules struct {
	Redirect             *Redirect  `protobuf:"bytes,1,opt,name=redirect,proto3" json:"redirect,omitempty"`
	Condition            *Condition `protobuf:"bytes,2,opt,name=condition,proto3" json:"condition,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *RoutingRules) Reset()         { *m = RoutingRules{} }
func (m *RoutingRules) String() string { return proto.CompactTextString(m) }
func (*RoutingRules) ProtoMessage()    {}
func (*RoutingRules) Descriptor() ([]byte, []int) {
	return fileDescriptor_005e34be4304e022, []int{6}
}

func (m *RoutingRules) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoutingRules.Unmarshal(m, b)
}
func (m *RoutingRules) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoutingRules.Marshal(b, m, deterministic)
}
func (m *RoutingRules) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoutingRules.Merge(m, src)
}
func (m *RoutingRules) XXX_Size() int {
	return xxx_messageInfo_RoutingRules.Size(m)
}
func (m *RoutingRules) XXX_DiscardUnknown() {
	xxx_messageInfo_RoutingRules.DiscardUnknown(m)
}

var xxx_messageInfo_RoutingRules proto.InternalMessageInfo

func (m *RoutingRules) GetRedirect() *Redirect {
	if m != nil {
		return m.Redirect
	}
	return nil
}

func (m *RoutingRules) GetCondition() *Condition {
	if m != nil {
		return m.Condition
	}
	return nil
}

type WebsiteConfiguration struct {
	IndexDocument         string                 `protobuf:"bytes,1,opt,name=indexDocument,proto3" json:"indexDocument,omitempty"`
	ErrorDocument         string                 `protobuf:"bytes,2,opt,name=errorDocument,proto3" json:"errorDocument,omitempty"`
	RedirectAllRequestsTo *RedirectAllRequestsTo `protobuf:"bytes,3,opt,name=redirectAllRequestsTo,proto3" json:"redirectAllRequestsTo,omitempty"`
	RoutingRules          []*RoutingRules        `protobuf:"bytes,4,rep,name=routingRules,proto3" json:"routingRules,omitempty"`
	XXX_NoUnkeyedLiteral  struct{}               `json:"-"`
	XXX_unrecognized      []byte                 `json:"-"`
	XXX_sizecache         int32                  `json:"-"`
}

func (m *WebsiteConfiguration) Reset()         { *m = WebsiteConfiguration{} }
func (m *WebsiteConfiguration) String() string { return proto.CompactTextString(m) }
func (*WebsiteConfiguration) ProtoMessage()    {}
func (*WebsiteConfiguration) Descriptor() ([]byte, []int) {
	return fileDescriptor_005e34be4304e022, []int{7}
}

func (m *WebsiteConfiguration) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WebsiteConfiguration.Unmarshal(m, b)
}
func (m *WebsiteConfiguration) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WebsiteConfiguration.Marshal(b, m, deterministic)
}
func (m *WebsiteConfiguration) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WebsiteConfiguration.Merge(m, src)
}
func (m *WebsiteConfiguration) XXX_Size() int {
	return xxx_messageInfo_WebsiteConfiguration.Size(m)
}
func (m *WebsiteConfiguration) XXX_DiscardUnknown() {
	xxx_messageInfo_WebsiteConfiguration.DiscardUnknown(m)
}

var xxx_messageInfo_WebsiteConfiguration proto.InternalMessageInfo

func (m *WebsiteConfiguration) GetIndexDocument() string {
	if m != nil {
		return m.IndexDocument
	}
	return ""
}

func (m *WebsiteConfiguration) GetErrorDocument() string {
	if m != nil {
		return m.ErrorDocument
	}
	return ""
}

func (m *WebsiteConfiguration) GetRedirectAllRequestsTo() *RedirectAllRequestsTo {
	if m != nil {
		return m.RedirectAllRequestsTo
	}
	return nil
}

func (m *WebsiteConfiguration) GetRoutingRules() []*RoutingRules {
	if m != nil {
		return m.RoutingRules
	}
	return nil
}

type CORSConfiguration struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	AllowedMethods       string   `protobuf:"bytes,2,opt,name=allowedMethods,proto3" json:"allowedMethods,omitempty"`
	AllowedOrigins       string   `protobuf:"bytes,3,opt,name=allowedOrigins,proto3" json:"allowedOrigins,omitempty"`
	AllowedHeaders       string   `protobuf:"bytes,4,opt,name=allowedHeaders,proto3" json:"allowedHeaders,omitempty"`
	MaxAgeSeconds        string   `protobuf:"bytes,5,opt,name=maxAgeSeconds,proto3" json:"maxAgeSeconds,omitempty"`
	ExposedHeaders       string   `protobuf:"bytes,6,opt,name=exposedHeaders,proto3" json:"exposedHeaders,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CORSConfiguration) Reset()         { *m = CORSConfiguration{} }
func (m *CORSConfiguration) String() string { return proto.CompactTextString(m) }
func (*CORSConfiguration) ProtoMessage()    {}
func (*CORSConfiguration) Descriptor() ([]byte, []int) {
	return fileDescriptor_005e34be4304e022, []int{8}
}

func (m *CORSConfiguration) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CORSConfiguration.Unmarshal(m, b)
}
func (m *CORSConfiguration) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CORSConfiguration.Marshal(b, m, deterministic)
}
func (m *CORSConfiguration) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CORSConfiguration.Merge(m, src)
}
func (m *CORSConfiguration) XXX_Size() int {
	return xxx_messageInfo_CORSConfiguration.Size(m)
}
func (m *CORSConfiguration) XXX_DiscardUnknown() {
	xxx_messageInfo_CORSConfiguration.DiscardUnknown(m)
}

var xxx_messageInfo_CORSConfiguration proto.InternalMessageInfo

func (m *CORSConfiguration) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *CORSConfiguration) GetAllowedMethods() string {
	if m != nil {
		return m.AllowedMethods
	}
	return ""
}

func (m *CORSConfiguration) GetAllowedOrigins() string {
	if m != nil {
		return m.AllowedOrigins
	}
	return ""
}

func (m *CORSConfiguration) GetAllowedHeaders() string {
	if m != nil {
		return m.AllowedHeaders
	}
	return ""
}

func (m *CORSConfiguration) GetMaxAgeSeconds() string {
	if m != nil {
		return m.MaxAgeSeconds
	}
	return ""
}

func (m *CORSConfiguration) GetExposedHeaders() string {
	if m != nil {
		return m.ExposedHeaders
	}
	return ""
}

type Destination struct {
	Bucket               string   `protobuf:"bytes,1,opt,name=bucket,proto3" json:"bucket,omitempty"`
	StorageClass         string   `protobuf:"bytes,2,opt,name=storageClass,proto3" json:"storageClass,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Destination) Reset()         { *m = Destination{} }
func (m *Destination) String() string { return proto.CompactTextString(m) }
func (*Destination) ProtoMessage()    {}
func (*Destination) Descriptor() ([]byte, []int) {
	return fileDescriptor_005e34be4304e022, []int{9}
}

func (m *Destination) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Destination.Unmarshal(m, b)
}
func (m *Destination) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Destination.Marshal(b, m, deterministic)
}
func (m *Destination) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Destination.Merge(m, src)
}
func (m *Destination) XXX_Size() int {
	return xxx_messageInfo_Destination.Size(m)
}
func (m *Destination) XXX_DiscardUnknown() {
	xxx_messageInfo_Destination.DiscardUnknown(m)
}

var xxx_messageInfo_Destination proto.InternalMessageInfo

func (m *Destination) GetBucket() string {
	if m != nil {
		return m.Bucket
	}
	return ""
}

func (m *Destination) GetStorageClass() string {
	if m != nil {
		return m.StorageClass
	}
	return ""
}

type ReplicationRole struct {
	Id                   string       `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Prefix               string       `protobuf:"bytes,2,opt,name=prefix,proto3" json:"prefix,omitempty"`
	Enabled              bool         `protobuf:"varint,3,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Destination          *Destination `protobuf:"bytes,4,opt,name=destination,proto3" json:"destination,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ReplicationRole) Reset()         { *m = ReplicationRole{} }
func (m *ReplicationRole) String() string { return proto.CompactTextString(m) }
func (*ReplicationRole) ProtoMessage()    {}
func (*ReplicationRole) Descriptor() ([]byte, []int) {
	return fileDescriptor_005e34be4304e022, []int{10}
}

func (m *ReplicationRole) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReplicationRole.Unmarshal(m, b)
}
func (m *ReplicationRole) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReplicationRole.Marshal(b, m, deterministic)
}
func (m *ReplicationRole) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplicationRole.Merge(m, src)
}
func (m *ReplicationRole) XXX_Size() int {
	return xxx_messageInfo_ReplicationRole.Size(m)
}
func (m *ReplicationRole) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplicationRole.DiscardUnknown(m)
}

var xxx_messageInfo_ReplicationRole proto.InternalMessageInfo

func (m *ReplicationRole) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ReplicationRole) GetPrefix() string {
	if m != nil {
		return m.Prefix
	}
	return ""
}

func (m *ReplicationRole) GetEnabled() bool {
	if m != nil {
		return m.Enabled
	}
	return false
}

func (m *ReplicationRole) GetDestination() *Destination {
	if m != nil {
		return m.Destination
	}
	return nil
}

type ReplicationConfiguration struct {
	Role                 string             `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`
	Rules                []*ReplicationRole `protobuf:"bytes,2,rep,name=rules,proto3" json:"rules,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *ReplicationConfiguration) Reset()         { *m = ReplicationConfiguration{} }
func (m *ReplicationConfiguration) String() string { return proto.CompactTextString(m) }
func (*ReplicationConfiguration) ProtoMessage()    {}
func (*ReplicationConfiguration) Descriptor() ([]byte, []int) {
	return fileDescriptor_005e34be4304e022, []int{11}
}

func (m *ReplicationConfiguration) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReplicationConfiguration.Unmarshal(m, b)
}
func (m *ReplicationConfiguration) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReplicationConfiguration.Marshal(b, m, deterministic)
}
func (m *ReplicationConfiguration) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplicationConfiguration.Merge(m, src)
}
func (m *ReplicationConfiguration) XXX_Size() int {
	return xxx_messageInfo_ReplicationConfiguration.Size(m)
}
func (m *ReplicationConfiguration) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplicationConfiguration.DiscardUnknown(m)
}

var xxx_messageInfo_ReplicationConfiguration proto.InternalMessageInfo

func (m *ReplicationConfiguration) GetRole() string {
	if m != nil {
		return m.Role
	}
	return ""
}

func (m *ReplicationConfiguration) GetRules() []*ReplicationRole {
	if m != nil {
		return m.Rules
	}
	return nil
}

type Tag struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Val                  string   `protobuf:"bytes,2,opt,name=val,proto3" json:"val,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Tag) Reset()         { *m = Tag{} }
func (m *Tag) String() string { return proto.CompactTextString(m) }
func (*Tag) ProtoMessage()    {}
func (*Tag) Descriptor() ([]byte, []int) {
	return fileDescriptor_005e34be4304e022, []int{12}
}

func (m *Tag) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Tag.Unmarshal(m, b)
}
func (m *Tag) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Tag.Marshal(b, m, deterministic)
}
func (m *Tag) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Tag.Merge(m, src)
}
func (m *Tag) XXX_Size() int {
	return xxx_messageInfo_Tag.Size(m)
}
func (m *Tag) XXX_DiscardUnknown() {
	xxx_messageInfo_Tag.DiscardUnknown(m)
}

var xxx_messageInfo_Tag proto.InternalMessageInfo

func (m *Tag) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *Tag) GetVal() string {
	if m != nil {
		return m.Val
	}
	return ""
}

type LifecycleFilter struct {
	Prefix               string   `protobuf:"bytes,1,opt,name=prefix,proto3" json:"prefix,omitempty"`
	Tags                 []*Tag   `protobuf:"bytes,2,rep,name=tags,proto3" json:"tags,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LifecycleFilter) Reset()         { *m = LifecycleFilter{} }
func (m *LifecycleFilter) String() string { return proto.CompactTextString(m) }
func (*LifecycleFilter) ProtoMessage()    {}
func (*LifecycleFilter) Descriptor() ([]byte, []int) {
	return fileDescriptor_005e34be4304e022, []int{13}
}

func (m *LifecycleFilter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LifecycleFilter.Unmarshal(m, b)
}
func (m *LifecycleFilter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LifecycleFilter.Marshal(b, m, deterministic)
}
func (m *LifecycleFilter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LifecycleFilter.Merge(m, src)
}
func (m *LifecycleFilter) XXX_Size() int {
	return xxx_messageInfo_LifecycleFilter.Size(m)
}
func (m *LifecycleFilter) XXX_DiscardUnknown() {
	xxx_messageInfo_LifecycleFilter.DiscardUnknown(m)
}

var xxx_messageInfo_LifecycleFilter proto.InternalMessageInfo

func (m *LifecycleFilter) GetPrefix() string {
	if m != nil {
		return m.Prefix
	}
	return ""
}

func (m *LifecycleFilter) GetTags() []*Tag {
	if m != nil {
		return m.Tags
	}
	return nil
}

type Action struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Day                  string   `protobuf:"bytes,2,opt,name=day,proto3" json:"day,omitempty"`
	DeleteMarker         string   `protobuf:"bytes,4,opt,name=deleteMarker,proto3" json:"deleteMarker,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Action) Reset()         { *m = Action{} }
func (m *Action) String() string { return proto.CompactTextString(m) }
func (*Action) ProtoMessage()    {}
func (*Action) Descriptor() ([]byte, []int) {
	return fileDescriptor_005e34be4304e022, []int{14}
}

func (m *Action) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Action.Unmarshal(m, b)
}
func (m *Action) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Action.Marshal(b, m, deterministic)
}
func (m *Action) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Action.Merge(m, src)
}
func (m *Action) XXX_Size() int {
	return xxx_messageInfo_Action.Size(m)
}
func (m *Action) XXX_DiscardUnknown() {
	xxx_messageInfo_Action.DiscardUnknown(m)
}

var xxx_messageInfo_Action proto.InternalMessageInfo

func (m *Action) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Action) GetDay() string {
	if m != nil {
		return m.Day
	}
	return ""
}

func (m *Action) GetDeleteMarker() string {
	if m != nil {
		return m.DeleteMarker
	}
	return ""
}

type LifecycleRole struct {
	Id                   string           `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Status               string           `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Filter               *LifecycleFilter `protobuf:"bytes,3,opt,name=filter,proto3" json:"filter,omitempty"`
	Actions              []*Action        `protobuf:"bytes,4,rep,name=actions,proto3" json:"actions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *LifecycleRole) Reset()         { *m = LifecycleRole{} }
func (m *LifecycleRole) String() string { return proto.CompactTextString(m) }
func (*LifecycleRole) ProtoMessage()    {}
func (*LifecycleRole) Descriptor() ([]byte, []int) {
	return fileDescriptor_005e34be4304e022, []int{15}
}

func (m *LifecycleRole) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LifecycleRole.Unmarshal(m, b)
}
func (m *LifecycleRole) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LifecycleRole.Marshal(b, m, deterministic)
}
func (m *LifecycleRole) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LifecycleRole.Merge(m, src)
}
func (m *LifecycleRole) XXX_Size() int {
	return xxx_messageInfo_LifecycleRole.Size(m)
}
func (m *LifecycleRole) XXX_DiscardUnknown() {
	xxx_messageInfo_LifecycleRole.DiscardUnknown(m)
}

var xxx_messageInfo_LifecycleRole proto.InternalMessageInfo

func (m *LifecycleRole) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *LifecycleRole) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *LifecycleRole) GetFilter() *LifecycleFilter {
	if m != nil {
		return m.Filter
	}
	return nil
}

func (m *LifecycleRole) GetActions() []*Action {
	if m != nil {
		return m.Actions
	}
	return nil
}

type ReplicationInfo struct {
	Status               string   `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Backend              string   `protobuf:"bytes,2,opt,name=backend,proto3" json:"backend,omitempty"`
	StorageClass         string   `protobuf:"bytes,3,opt,name=storageClass,proto3" json:"storageClass,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReplicationInfo) Reset()         { *m = ReplicationInfo{} }
func (m *ReplicationInfo) String() string { return proto.CompactTextString(m) }
func (*ReplicationInfo) ProtoMessage()    {}
func (*ReplicationInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_005e34be4304e022, []int{16}
}

func (m *ReplicationInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReplicationInfo.Unmarshal(m, b)
}
func (m *ReplicationInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReplicationInfo.Marshal(b, m, deterministic)
}
func (m *ReplicationInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplicationInfo.Merge(m, src)
}
func (m *ReplicationInfo) XXX_Size() int {
	return xxx_messageInfo_ReplicationInfo.Size(m)
}
func (m *ReplicationInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplicationInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ReplicationInfo proto.InternalMessageInfo

func (m *ReplicationInfo) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *ReplicationInfo) GetBackend() string {
	if m != nil {
		return m.Backend
	}
	return ""
}

func (m *ReplicationInfo) GetStorageClass() string {
	if m != nil {
		return m.StorageClass
	}
	return ""
}

type Bucket struct {
	Name                     string                    `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Owner                    string                    `protobuf:"bytes,2,opt,name=owner,proto3" json:"owner,omitempty"`
	OwnerDisplayName         string                    `protobuf:"bytes,3,opt,name=ownerDisplayName,proto3" json:"ownerDisplayName,omitempty"`
	Acl                      *ACL                      `protobuf:"bytes,4,opt,name=acl,proto3" json:"acl,omitempty"`
	CreationDate             int64                     `protobuf:"varint,5,opt,name=creationDate,proto3" json:"creationDate,omitempty"`
	Transient                bool                      `protobuf:"varint,6,opt,name=transient,proto3" json:"transient,omitempty"`
	Deleted                  bool                      `protobuf:"varint,7,opt,name=deleted,proto3" json:"deleted,omitempty"`
	ServerSideEncryption     *ServerSideEncryption     `protobuf:"bytes,8,opt,name=serverSideEncryption,proto3" json:"serverSideEncryption,omitempty"`
	VersioningConfiguration  *VersioningConfiguration  `protobuf:"bytes,9,opt,name=versioningConfiguration,proto3" json:"versioningConfiguration,omitempty"`
	Backend                  string                    `protobuf:"bytes,10,opt,name=backend,proto3" json:"backend,omitempty"`
	WebsiteConfiguration     *WebsiteConfiguration     `protobuf:"bytes,11,opt,name=websiteConfiguration,proto3" json:"websiteConfiguration,omitempty"`
	Cors                     *CORSConfiguration        `protobuf:"bytes,12,opt,name=cors,proto3" json:"cors,omitempty"`
	ReplicationConfiguration *ReplicationConfiguration `protobuf:"bytes,13,opt,name=replicationConfiguration,proto3" json:"replicationConfiguration,omitempty"`
	LifecycleConfiguration   []*LifecycleRole          `protobuf:"bytes,14,rep,name=lifecycleConfiguration,proto3" json:"lifecycleConfiguration,omitempty"`
	XXX_NoUnkeyedLiteral     struct{}                  `json:"-"`
	XXX_unrecognized         []byte                    `json:"-"`
	XXX_sizecache            int32                     `json:"-"`
}

func (m *Bucket) Reset()         { *m = Bucket{} }
func (m *Bucket) String() string { return proto.CompactTextString(m) }
func (*Bucket) ProtoMessage()    {}
func (*Bucket) Descriptor() ([]byte, []int) {
	return fileDescriptor_005e34be4304e022, []int{17}
}

func (m *Bucket) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Bucket.Unmarshal(m, b)
}
func (m *Bucket) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Bucket.Marshal(b, m, deterministic)
}
func (m *Bucket) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Bucket.Merge(m, src)
}
func (m *Bucket) XXX_Size() int {
	return xxx_messageInfo_Bucket.Size(m)
}
func (m *Bucket) XXX_DiscardUnknown() {
	xxx_messageInfo_Bucket.DiscardUnknown(m)
}

var xxx_messageInfo_Bucket proto.InternalMessageInfo

func (m *Bucket) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Bucket) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *Bucket) GetOwnerDisplayName() string {
	if m != nil {
		return m.OwnerDisplayName
	}
	return ""
}

func (m *Bucket) GetAcl() *ACL {
	if m != nil {
		return m.Acl
	}
	return nil
}

func (m *Bucket) GetCreationDate() int64 {
	if m != nil {
		return m.CreationDate
	}
	return 0
}

func (m *Bucket) GetTransient() bool {
	if m != nil {
		return m.Transient
	}
	return false
}

func (m *Bucket) GetDeleted() bool {
	if m != nil {
		return m.Deleted
	}
	return false
}

func (m *Bucket) GetServerSideEncryption() *ServerSideEncryption {
	if m != nil {
		return m.ServerSideEncryption
	}
	return nil
}

func (m *Bucket) GetVersioningConfiguration() *VersioningConfiguration {
	if m != nil {
		return m.VersioningConfiguration
	}
	return nil
}

func (m *Bucket) GetBackend() string {
	if m != nil {
		return m.Backend
	}
	return ""
}

func (m *Bucket) GetWebsiteConfiguration() *WebsiteConfiguration {
	if m != nil {
		return m.WebsiteConfiguration
	}
	return nil
}

func (m *Bucket) GetCors() *CORSConfiguration {
	if m != nil {
		return m.Cors
	}
	return nil
}

func (m *Bucket) GetReplicationConfiguration() *ReplicationConfiguration {
	if m != nil {
		return m.ReplicationConfiguration
	}
	return nil
}

func (m *Bucket) GetLifecycleConfiguration() []*LifecycleRole {
	if m != nil {
		return m.LifecycleConfiguration
	}
	return nil
}

type Partion struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	PartNumber           string   `protobuf:"bytes,2,opt,name=partNumber,proto3" json:"partNumber,omitempty"`
	Size                 int64    `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	Etag                 string   `protobuf:"bytes,4,opt,name=etag,proto3" json:"etag,omitempty"`
	LastModified         int64    `protobuf:"varint,5,opt,name=lastModified,proto3" json:"lastModified,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Partion) Reset()         { *m = Partion{} }
func (m *Partion) String() string { return proto.CompactTextString(m) }
func (*Partion) ProtoMessage()    {}
func (*Partion) Descriptor() ([]byte, []int) {
	return fileDescriptor_005e34be4304e022, []int{18}
}

func (m *Partion) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Partion.Unmarshal(m, b)
}
func (m *Partion) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Partion.Marshal(b, m, deterministic)
}
func (m *Partion) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Partion.Merge(m, src)
}
func (m *Partion) XXX_Size() int {
	return xxx_messageInfo_Partion.Size(m)
}
func (m *Partion) XXX_DiscardUnknown() {
	xxx_messageInfo_Partion.DiscardUnknown(m)
}

var xxx_messageInfo_Partion proto.InternalMessageInfo

func (m *Partion) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *Partion) GetPartNumber() string {
	if m != nil {
		return m.PartNumber
	}
	return ""
}

func (m *Partion) GetSize() int64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *Partion) GetEtag() string {
	if m != nil {
		return m.Etag
	}
	return ""
}

func (m *Partion) GetLastModified() int64 {
	if m != nil {
		return m.LastModified
	}
	return 0
}

type Version struct {
	Versionid            string   `protobuf:"bytes,1,opt,name=versionid,proto3" json:"versionid,omitempty"`
	Etag                 string   `protobuf:"bytes,2,opt,name=etag,proto3" json:"etag,omitempty"`
	IsLatest             string   `protobuf:"bytes,3,opt,name=isLatest,proto3" json:"isLatest,omitempty"`
	LastModified         int64    `protobuf:"varint,4,opt,name=lastModified,proto3" json:"lastModified,omitempty"`
	Size                 int64    `protobuf:"varint,5,opt,name=size,proto3" json:"size,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Version) Reset()         { *m = Version{} }
func (m *Version) String() string { return proto.CompactTextString(m) }
func (*Version) ProtoMessage()    {}
func (*Version) Descriptor() ([]byte, []int) {
	return fileDescriptor_005e34be4304e022, []int{19}
}

func (m *Version) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Version.Unmarshal(m, b)
}
func (m *Version) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Version.Marshal(b, m, deterministic)
}
func (m *Version) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Version.Merge(m, src)
}
func (m *Version) XXX_Size() int {
	return xxx_messageInfo_Version.Size(m)
}
func (m *Version) XXX_DiscardUnknown() {
	xxx_messageInfo_Version.DiscardUnknown(m)
}

var xxx_messageInfo_Version proto.InternalMessageInfo

func (m *Version) GetVersionid() string {
	if m != nil {
		return m.Versionid
	}
	return ""
}

func (m *Version) GetEtag() string {
	if m != nil {
		return m.Etag
	}
	return ""
}

func (m *Version) GetIsLatest() string {
	if m != nil {
		return m.IsLatest
	}
	return ""
}

func (m *Version) GetLastModified() int64 {
	if m != nil {
		return m.LastModified
	}
	return 0
}

func (m *Version) GetSize() int64 {
	if m != nil {
		return m.Size
	}
	return 0
}

type Object struct {
	ObjectKey               string                `protobuf:"bytes,1,opt,name=objectKey,proto3" json:"objectKey,omitempty"`
	BucketName              string                `protobuf:"bytes,2,opt,name=bucketName,proto3" json:"bucketName,omitempty"`
	Owner                   string                `protobuf:"bytes,3,opt,name=owner,proto3" json:"owner,omitempty"`
	OwnerDisplayName        string                `protobuf:"bytes,4,opt,name=ownerDisplayName,proto3" json:"ownerDisplayName,omitempty"`
	CacheControl            string                `protobuf:"bytes,5,opt,name=cacheControl,proto3" json:"cacheControl,omitempty"`
	ContentDisposition      string                `protobuf:"bytes,6,opt,name=contentDisposition,proto3" json:"contentDisposition,omitempty"`
	ContentEncoding         string                `protobuf:"bytes,7,opt,name=contentEncoding,proto3" json:"contentEncoding,omitempty"`
	Expires                 string                `protobuf:"bytes,8,opt,name=expires,proto3" json:"expires,omitempty"`
	ContentLength           string                `protobuf:"bytes,9,opt,name=contentLength,proto3" json:"contentLength,omitempty"`
	ContentType             string                `protobuf:"bytes,10,opt,name=contentType,proto3" json:"contentType,omitempty"`
	ContentMd5              string                `protobuf:"bytes,11,opt,name=contentMd5,proto3" json:"contentMd5,omitempty"`
	Versions                []*Version            `protobuf:"bytes,12,rep,name=versions,proto3" json:"versions,omitempty"`
	StorageClass            string                `protobuf:"bytes,13,opt,name=storageClass,proto3" json:"storageClass,omitempty"`
	ServerSideEncryption    *ServerSideEncryption `protobuf:"bytes,14,opt,name=serverSideEncryption,proto3" json:"serverSideEncryption,omitempty"`
	WebsiteRedirectLocation string                `protobuf:"bytes,15,opt,name=websiteRedirectLocation,proto3" json:"websiteRedirectLocation,omitempty"`
	Acl                     *ACL                  `protobuf:"bytes,16,opt,name=acl,proto3" json:"acl,omitempty"`
	Backend                 string                `protobuf:"bytes,17,opt,name=backend,proto3" json:"backend,omitempty"`
	IsNull                  string                `protobuf:"bytes,18,opt,name=isNull,proto3" json:"isNull,omitempty"`
	IsDeleteMarker          string                `protobuf:"bytes,19,opt,name=isDeleteMarker,proto3" json:"isDeleteMarker,omitempty"`
	ReplicationInfo         []*ReplicationInfo    `protobuf:"bytes,20,rep,name=replicationInfo,proto3" json:"replicationInfo,omitempty"`
	Size                    int64                 `protobuf:"varint,21,opt,name=size,proto3" json:"size,omitempty"`
	Partions                []*Partion            `protobuf:"bytes,22,rep,name=partions,proto3" json:"partions,omitempty"`
	Tags                    []*Tag                `protobuf:"bytes,23,rep,name=tags,proto3" json:"tags,omitempty"`
	LastModified            string                `protobuf:"bytes,24,opt,name=lastModified,proto3" json:"lastModified,omitempty"`
	InitFlag                string                `protobuf:"bytes,25,opt,name=initFlag,proto3" json:"initFlag,omitempty"`
	ETag                    string                `protobuf:"bytes,26,opt,name=ETag,proto3" json:"ETag,omitempty"`
	XXX_NoUnkeyedLiteral    struct{}              `json:"-"`
	XXX_unrecognized        []byte                `json:"-"`
	XXX_sizecache           int32                 `json:"-"`
}

func (m *Object) Reset()         { *m = Object{} }
func (m *Object) String() string { return proto.CompactTextString(m) }
func (*Object) ProtoMessage()    {}
func (*Object) Descriptor() ([]byte, []int) {
	return fileDescriptor_005e34be4304e022, []int{20}
}

func (m *Object) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Object.Unmarshal(m, b)
}
func (m *Object) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Object.Marshal(b, m, deterministic)
}
func (m *Object) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Object.Merge(m, src)
}
func (m *Object) XXX_Size() int {
	return xxx_messageInfo_Object.Size(m)
}
func (m *Object) XXX_DiscardUnknown() {
	xxx_messageInfo_Object.DiscardUnknown(m)
}

var xxx_messageInfo_Object proto.InternalMessageInfo

func (m *Object) GetObjectKey() string {
	if m != nil {
		return m.ObjectKey
	}
	return ""
}

func (m *Object) GetBucketName() string {
	if m != nil {
		return m.BucketName
	}
	return ""
}

func (m *Object) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *Object) GetOwnerDisplayName() string {
	if m != nil {
		return m.OwnerDisplayName
	}
	return ""
}

func (m *Object) GetCacheControl() string {
	if m != nil {
		return m.CacheControl
	}
	return ""
}

func (m *Object) GetContentDisposition() string {
	if m != nil {
		return m.ContentDisposition
	}
	return ""
}

func (m *Object) GetContentEncoding() string {
	if m != nil {
		return m.ContentEncoding
	}
	return ""
}

func (m *Object) GetExpires() string {
	if m != nil {
		return m.Expires
	}
	return ""
}

func (m *Object) GetContentLength() string {
	if m != nil {
		return m.ContentLength
	}
	return ""
}

func (m *Object) GetContentType() string {
	if m != nil {
		return m.ContentType
	}
	return ""
}

func (m *Object) GetContentMd5() string {
	if m != nil {
		return m.ContentMd5
	}
	return ""
}

func (m *Object) GetVersions() []*Version {
	if m != nil {
		return m.Versions
	}
	return nil
}

func (m *Object) GetStorageClass() string {
	if m != nil {
		return m.StorageClass
	}
	return ""
}

func (m *Object) GetServerSideEncryption() *ServerSideEncryption {
	if m != nil {
		return m.ServerSideEncryption
	}
	return nil
}

func (m *Object) GetWebsiteRedirectLocation() string {
	if m != nil {
		return m.WebsiteRedirectLocation
	}
	return ""
}

func (m *Object) GetAcl() *ACL {
	if m != nil {
		return m.Acl
	}
	return nil
}

func (m *Object) GetBackend() string {
	if m != nil {
		return m.Backend
	}
	return ""
}

func (m *Object) GetIsNull() string {
	if m != nil {
		return m.IsNull
	}
	return ""
}

func (m *Object) GetIsDeleteMarker() string {
	if m != nil {
		return m.IsDeleteMarker
	}
	return ""
}

func (m *Object) GetReplicationInfo() []*ReplicationInfo {
	if m != nil {
		return m.ReplicationInfo
	}
	return nil
}

func (m *Object) GetSize() int64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *Object) GetPartions() []*Partion {
	if m != nil {
		return m.Partions
	}
	return nil
}

func (m *Object) GetTags() []*Tag {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *Object) GetLastModified() string {
	if m != nil {
		return m.LastModified
	}
	return ""
}

func (m *Object) GetInitFlag() string {
	if m != nil {
		return m.InitFlag
	}
	return ""
}

func (m *Object) GetETag() string {
	if m != nil {
		return m.ETag
	}
	return ""
}

type ListBucketsResponse struct {
	Buckets              []*Bucket `protobuf:"bytes,1,rep,name=buckets,proto3" json:"buckets,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *ListBucketsResponse) Reset()         { *m = ListBucketsResponse{} }
func (m *ListBucketsResponse) String() string { return proto.CompactTextString(m) }
func (*ListBucketsResponse) ProtoMessage()    {}
func (*ListBucketsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_005e34be4304e022, []int{21}
}

func (m *ListBucketsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListBucketsResponse.Unmarshal(m, b)
}
func (m *ListBucketsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListBucketsResponse.Marshal(b, m, deterministic)
}
func (m *ListBucketsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListBucketsResponse.Merge(m, src)
}
func (m *ListBucketsResponse) XXX_Size() int {
	return xxx_messageInfo_ListBucketsResponse.Size(m)
}
func (m *ListBucketsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListBucketsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListBucketsResponse proto.InternalMessageInfo

func (m *ListBucketsResponse) GetBuckets() []*Bucket {
	if m != nil {
		return m.Buckets
	}
	return nil
}

type BaseResponse struct {
	ErrorCode            string   `protobuf:"bytes,1,opt,name=errorCode,proto3" json:"errorCode,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BaseResponse) Reset()         { *m = BaseResponse{} }
func (m *BaseResponse) String() string { return proto.CompactTextString(m) }
func (*BaseResponse) ProtoMessage()    {}
func (*BaseResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_005e34be4304e022, []int{22}
}

func (m *BaseResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BaseResponse.Unmarshal(m, b)
}
func (m *BaseResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BaseResponse.Marshal(b, m, deterministic)
}
func (m *BaseResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BaseResponse.Merge(m, src)
}
func (m *BaseResponse) XXX_Size() int {
	return xxx_messageInfo_BaseResponse.Size(m)
}
func (m *BaseResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BaseResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BaseResponse proto.InternalMessageInfo

func (m *BaseResponse) GetErrorCode() string {
	if m != nil {
		return m.ErrorCode
	}
	return ""
}

func (m *BaseResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type BaseRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BaseRequest) Reset()         { *m = BaseRequest{} }
func (m *BaseRequest) String() string { return proto.CompactTextString(m) }
func (*BaseRequest) ProtoMessage()    {}
func (*BaseRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_005e34be4304e022, []int{23}
}

func (m *BaseRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BaseRequest.Unmarshal(m, b)
}
func (m *BaseRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BaseRequest.Marshal(b, m, deterministic)
}
func (m *BaseRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BaseRequest.Merge(m, src)
}
func (m *BaseRequest) XXX_Size() int {
	return xxx_messageInfo_BaseRequest.Size(m)
}
func (m *BaseRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BaseRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BaseRequest proto.InternalMessageInfo

func (m *BaseRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type ListObjectsRequest struct {
	// Bucket is a required field
	Bucket               string   `protobuf:"bytes,1,opt,name=Bucket,proto3" json:"Bucket,omitempty"`
	Delimiter            string   `protobuf:"bytes,2,opt,name=Delimiter,proto3" json:"Delimiter,omitempty"`
	Owner                string   `protobuf:"bytes,3,opt,name=Owner,proto3" json:"Owner,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListObjectsRequest) Reset()         { *m = ListObjectsRequest{} }
func (m *ListObjectsRequest) String() string { return proto.CompactTextString(m) }
func (*ListObjectsRequest) ProtoMessage()    {}
func (*ListObjectsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_005e34be4304e022, []int{24}
}

func (m *ListObjectsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListObjectsRequest.Unmarshal(m, b)
}
func (m *ListObjectsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListObjectsRequest.Marshal(b, m, deterministic)
}
func (m *ListObjectsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListObjectsRequest.Merge(m, src)
}
func (m *ListObjectsRequest) XXX_Size() int {
	return xxx_messageInfo_ListObjectsRequest.Size(m)
}
func (m *ListObjectsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListObjectsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListObjectsRequest proto.InternalMessageInfo

func (m *ListObjectsRequest) GetBucket() string {
	if m != nil {
		return m.Bucket
	}
	return ""
}

func (m *ListObjectsRequest) GetDelimiter() string {
	if m != nil {
		return m.Delimiter
	}
	return ""
}

func (m *ListObjectsRequest) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

type ListObjectResponse struct {
	ListObjects          []*Object `protobuf:"bytes,1,rep,name=ListObjects,proto3" json:"ListObjects,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *ListObjectResponse) Reset()         { *m = ListObjectResponse{} }
func (m *ListObjectResponse) String() string { return proto.CompactTextString(m) }
func (*ListObjectResponse) ProtoMessage()    {}
func (*ListObjectResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_005e34be4304e022, []int{25}
}

func (m *ListObjectResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListObjectResponse.Unmarshal(m, b)
}
func (m *ListObjectResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListObjectResponse.Marshal(b, m, deterministic)
}
func (m *ListObjectResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListObjectResponse.Merge(m, src)
}
func (m *ListObjectResponse) XXX_Size() int {
	return xxx_messageInfo_ListObjectResponse.Size(m)
}
func (m *ListObjectResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListObjectResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListObjectResponse proto.InternalMessageInfo

func (m *ListObjectResponse) GetListObjects() []*Object {
	if m != nil {
		return m.ListObjects
	}
	return nil
}

type DeleteObjectInput struct {
	Bucket               string   `protobuf:"bytes,1,opt,name=Bucket,proto3" json:"Bucket,omitempty"`
	Key                  string   `protobuf:"bytes,2,opt,name=Key,proto3" json:"Key,omitempty"`
	Versionid            string   `protobuf:"bytes,3,opt,name=Versionid,proto3" json:"Versionid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteObjectInput) Reset()         { *m = DeleteObjectInput{} }
func (m *DeleteObjectInput) String() string { return proto.CompactTextString(m) }
func (*DeleteObjectInput) ProtoMessage()    {}
func (*DeleteObjectInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_005e34be4304e022, []int{26}
}

func (m *DeleteObjectInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteObjectInput.Unmarshal(m, b)
}
func (m *DeleteObjectInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteObjectInput.Marshal(b, m, deterministic)
}
func (m *DeleteObjectInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteObjectInput.Merge(m, src)
}
func (m *DeleteObjectInput) XXX_Size() int {
	return xxx_messageInfo_DeleteObjectInput.Size(m)
}
func (m *DeleteObjectInput) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteObjectInput.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteObjectInput proto.InternalMessageInfo

func (m *DeleteObjectInput) GetBucket() string {
	if m != nil {
		return m.Bucket
	}
	return ""
}

func (m *DeleteObjectInput) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *DeleteObjectInput) GetVersionid() string {
	if m != nil {
		return m.Versionid
	}
	return ""
}

type GetObjectInput struct {
	Bucket               string   `protobuf:"bytes,1,opt,name=Bucket,proto3" json:"Bucket,omitempty"`
	Key                  string   `protobuf:"bytes,2,opt,name=Key,proto3" json:"Key,omitempty"`
	Versionid            string   `protobuf:"bytes,3,opt,name=Versionid,proto3" json:"Versionid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetObjectInput) Reset()         { *m = GetObjectInput{} }
func (m *GetObjectInput) String() string { return proto.CompactTextString(m) }
func (*GetObjectInput) ProtoMessage()    {}
func (*GetObjectInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_005e34be4304e022, []int{27}
}

func (m *GetObjectInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetObjectInput.Unmarshal(m, b)
}
func (m *GetObjectInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetObjectInput.Marshal(b, m, deterministic)
}
func (m *GetObjectInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetObjectInput.Merge(m, src)
}
func (m *GetObjectInput) XXX_Size() int {
	return xxx_messageInfo_GetObjectInput.Size(m)
}
func (m *GetObjectInput) XXX_DiscardUnknown() {
	xxx_messageInfo_GetObjectInput.DiscardUnknown(m)
}

var xxx_messageInfo_GetObjectInput proto.InternalMessageInfo

func (m *GetObjectInput) GetBucket() string {
	if m != nil {
		return m.Bucket
	}
	return ""
}

func (m *GetObjectInput) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *GetObjectInput) GetVersionid() string {
	if m != nil {
		return m.Versionid
	}
	return ""
}

type MultipartUpload struct {
	Bucket               string   `protobuf:"bytes,1,opt,name=Bucket,proto3" json:"Bucket,omitempty"`
	Key                  string   `protobuf:"bytes,2,opt,name=Key,proto3" json:"Key,omitempty"`
	UploadId             string   `protobuf:"bytes,3,opt,name=uploadId,proto3" json:"uploadId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MultipartUpload) Reset()         { *m = MultipartUpload{} }
func (m *MultipartUpload) String() string { return proto.CompactTextString(m) }
func (*MultipartUpload) ProtoMessage()    {}
func (*MultipartUpload) Descriptor() ([]byte, []int) {
	return fileDescriptor_005e34be4304e022, []int{28}
}

func (m *MultipartUpload) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MultipartUpload.Unmarshal(m, b)
}
func (m *MultipartUpload) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MultipartUpload.Marshal(b, m, deterministic)
}
func (m *MultipartUpload) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MultipartUpload.Merge(m, src)
}
func (m *MultipartUpload) XXX_Size() int {
	return xxx_messageInfo_MultipartUpload.Size(m)
}
func (m *MultipartUpload) XXX_DiscardUnknown() {
	xxx_messageInfo_MultipartUpload.DiscardUnknown(m)
}

var xxx_messageInfo_MultipartUpload proto.InternalMessageInfo

func (m *MultipartUpload) GetBucket() string {
	if m != nil {
		return m.Bucket
	}
	return ""
}

func (m *MultipartUpload) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *MultipartUpload) GetUploadId() string {
	if m != nil {
		return m.UploadId
	}
	return ""
}

type ListParts struct {
	Bucket               string   `protobuf:"bytes,1,opt,name=Bucket,proto3" json:"Bucket,omitempty"`
	Key                  string   `protobuf:"bytes,2,opt,name=Key,proto3" json:"Key,omitempty"`
	UploadId             string   `protobuf:"bytes,3,opt,name=uploadId,proto3" json:"uploadId,omitempty"`
	MaxParts             int64    `protobuf:"varint,4,opt,name=MaxParts,proto3" json:"MaxParts,omitempty"`
	PartNumberMarker     int64    `protobuf:"varint,5,opt,name=PartNumberMarker,proto3" json:"PartNumberMarker,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListParts) Reset()         { *m = ListParts{} }
func (m *ListParts) String() string { return proto.CompactTextString(m) }
func (*ListParts) ProtoMessage()    {}
func (*ListParts) Descriptor() ([]byte, []int) {
	return fileDescriptor_005e34be4304e022, []int{29}
}

func (m *ListParts) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListParts.Unmarshal(m, b)
}
func (m *ListParts) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListParts.Marshal(b, m, deterministic)
}
func (m *ListParts) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListParts.Merge(m, src)
}
func (m *ListParts) XXX_Size() int {
	return xxx_messageInfo_ListParts.Size(m)
}
func (m *ListParts) XXX_DiscardUnknown() {
	xxx_messageInfo_ListParts.DiscardUnknown(m)
}

var xxx_messageInfo_ListParts proto.InternalMessageInfo

func (m *ListParts) GetBucket() string {
	if m != nil {
		return m.Bucket
	}
	return ""
}

func (m *ListParts) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *ListParts) GetUploadId() string {
	if m != nil {
		return m.UploadId
	}
	return ""
}

func (m *ListParts) GetMaxParts() int64 {
	if m != nil {
		return m.MaxParts
	}
	return 0
}

func (m *ListParts) GetPartNumberMarker() int64 {
	if m != nil {
		return m.PartNumberMarker
	}
	return 0
}

func init() {
	proto.RegisterType((*ACL)(nil), "ACL")
	proto.RegisterType((*ServerSideEncryption)(nil), "ServerSideEncryption")
	proto.RegisterType((*VersioningConfiguration)(nil), "VersioningConfiguration")
	proto.RegisterType((*RedirectAllRequestsTo)(nil), "RedirectAllRequestsTo")
	proto.RegisterType((*Redirect)(nil), "Redirect")
	proto.RegisterType((*Condition)(nil), "Condition")
	proto.RegisterType((*RoutingRules)(nil), "RoutingRules")
	proto.RegisterType((*WebsiteConfiguration)(nil), "WebsiteConfiguration")
	proto.RegisterType((*CORSConfiguration)(nil), "CORSConfiguration")
	proto.RegisterType((*Destination)(nil), "Destination")
	proto.RegisterType((*ReplicationRole)(nil), "ReplicationRole")
	proto.RegisterType((*ReplicationConfiguration)(nil), "ReplicationConfiguration")
	proto.RegisterType((*Tag)(nil), "Tag")
	proto.RegisterType((*LifecycleFilter)(nil), "LifecycleFilter")
	proto.RegisterType((*Action)(nil), "Action")
	proto.RegisterType((*LifecycleRole)(nil), "LifecycleRole")
	proto.RegisterType((*ReplicationInfo)(nil), "ReplicationInfo")
	proto.RegisterType((*Bucket)(nil), "Bucket")
	proto.RegisterType((*Partion)(nil), "Partion")
	proto.RegisterType((*Version)(nil), "Version")
	proto.RegisterType((*Object)(nil), "Object")
	proto.RegisterType((*ListBucketsResponse)(nil), "ListBucketsResponse")
	proto.RegisterType((*BaseResponse)(nil), "BaseResponse")
	proto.RegisterType((*BaseRequest)(nil), "BaseRequest")
	proto.RegisterType((*ListObjectsRequest)(nil), "ListObjectsRequest")
	proto.RegisterType((*ListObjectResponse)(nil), "ListObjectResponse")
	proto.RegisterType((*DeleteObjectInput)(nil), "DeleteObjectInput")
	proto.RegisterType((*GetObjectInput)(nil), "GetObjectInput")
	proto.RegisterType((*MultipartUpload)(nil), "MultipartUpload")
	proto.RegisterType((*ListParts)(nil), "ListParts")
}

func init() { proto.RegisterFile("s3.proto", fileDescriptor_005e34be4304e022) }

var fileDescriptor_005e34be4304e022 = []byte{
	// 1862 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x58, 0x4f, 0x73, 0x1b, 0x49,
	0x15, 0x8f, 0x2c, 0x59, 0xd2, 0x3c, 0xc9, 0x7f, 0xd2, 0x51, 0x94, 0x89, 0xd7, 0x40, 0x76, 0x2a,
	0x04, 0x2f, 0x87, 0xa9, 0xc2, 0x2e, 0xaa, 0x16, 0x0e, 0x80, 0x56, 0x76, 0x16, 0x57, 0xe4, 0xd8,
	0xd5, 0x76, 0x12, 0xaa, 0x38, 0x84, 0xf6, 0x4c, 0x5b, 0x6e, 0x3c, 0x9a, 0xd1, 0x76, 0xb7, 0x12,
	0x8b, 0x2b, 0x54, 0x71, 0xe4, 0xc2, 0x85, 0xa2, 0xb8, 0x70, 0xe7, 0x8b, 0xf0, 0x35, 0x38, 0xf1,
	0x2d, 0xa8, 0xfe, 0x37, 0x9a, 0x91, 0x46, 0x2c, 0x5b, 0xc5, 0x9e, 0xd4, 0xef, 0xd7, 0xaf, 0x5f,
	0xbf, 0xd7, 0xef, 0xaf, 0x06, 0xda, 0xe2, 0x28, 0x9c, 0xf2, 0x4c, 0x66, 0xc1, 0xdf, 0x6b, 0x50,
	0x1f, 0x0c, 0x47, 0xa8, 0x0f, 0xcd, 0x88, 0xa4, 0x29, 0x8d, 0xfd, 0xda, 0xb3, 0xda, 0x81, 0x87,
	0x2d, 0x85, 0x3e, 0x85, 0xee, 0xcb, 0x37, 0xa3, 0xd1, 0xfb, 0xe1, 0xf9, 0xeb, 0x2b, 0x7c, 0x3e,
	0xf2, 0x37, 0x9e, 0xd5, 0x0f, 0x3c, 0xdc, 0x51, 0x98, 0x85, 0x50, 0x0f, 0x36, 0xdf, 0xe1, 0xd3,
	0xab, 0x13, 0xbf, 0xae, 0xf7, 0x0c, 0x81, 0x3e, 0x01, 0x4f, 0x2f, 0xde, 0x0f, 0x86, 0x17, 0x7e,
	0x43, 0xef, 0xb4, 0x35, 0x30, 0x18, 0x5e, 0x20, 0x04, 0x0d, 0x7c, 0x32, 0x38, 0xf6, 0x37, 0x35,
	0xae, 0xd7, 0xe8, 0x29, 0xb4, 0xd5, 0xaf, 0xe6, 0x6f, 0x6a, 0xbc, 0xa5, 0xe8, 0xc1, 0xf0, 0x22,
	0xf8, 0x73, 0x0d, 0x7a, 0x97, 0x94, 0x7f, 0xa0, 0xfc, 0x92, 0xc5, 0xf4, 0x24, 0x8d, 0xf8, 0x7c,
	0x2a, 0x59, 0x96, 0xa2, 0x67, 0xd0, 0xd1, 0xeb, 0xcb, 0xe8, 0x96, 0x4e, 0xa8, 0x55, 0xbd, 0x08,
	0xa1, 0x7d, 0xf0, 0x48, 0x32, 0xce, 0x38, 0x93, 0xb7, 0x13, 0x7f, 0x43, 0xef, 0x2f, 0x00, 0x75,
	0x7e, 0x42, 0x84, 0xa4, 0xfc, 0x15, 0x9d, 0x9f, 0xc6, 0x7e, 0xdd, 0x9c, 0x2f, 0x40, 0x68, 0x0f,
	0xda, 0x13, 0x92, 0xc6, 0x32, 0xe3, 0x73, 0xbf, 0xf1, 0xac, 0x76, 0xd0, 0xc6, 0x39, 0x1d, 0x9c,
	0xc3, 0x93, 0xb7, 0x94, 0x0b, 0x96, 0xa5, 0x2c, 0x1d, 0x0f, 0xb3, 0xf4, 0x86, 0x8d, 0x67, 0x9c,
	0x68, 0xc5, 0xfa, 0xd0, 0xbc, 0x94, 0x44, 0xce, 0x84, 0x7b, 0x4e, 0x43, 0x29, 0x75, 0xce, 0x6e,
	0xc8, 0x31, 0x4d, 0xa8, 0xa4, 0x4e, 0x9d, 0x1c, 0x08, 0xce, 0xe1, 0x31, 0xa6, 0x31, 0xe3, 0x34,
	0x92, 0x83, 0x24, 0xc1, 0xf4, 0xab, 0x19, 0x15, 0x52, 0x5c, 0x65, 0x4a, 0x8b, 0xdb, 0x4c, 0xc8,
	0xd7, 0x24, 0x37, 0x32, 0xa7, 0xd5, 0x9e, 0x76, 0x65, 0x94, 0x25, 0xd6, 0x3b, 0x39, 0x1d, 0xfc,
	0xb3, 0x06, 0x6d, 0x27, 0xb1, 0xc4, 0x68, 0x85, 0x38, 0xba, 0x74, 0xc1, 0xc6, 0xd2, 0x05, 0x87,
	0xd0, 0xe3, 0x74, 0x9a, 0x90, 0x88, 0xbe, 0xa2, 0xf3, 0x0b, 0x4e, 0x6f, 0xd8, 0xfd, 0x3b, 0x26,
	0x6f, 0xed, 0x6b, 0x55, 0xee, 0xa1, 0x17, 0xb0, 0xbd, 0xc0, 0x35, 0x77, 0x43, 0x73, 0x2f, 0xa1,
	0xe8, 0x87, 0xb0, 0x7b, 0x2b, 0xe5, 0xd4, 0xe9, 0x38, 0xcc, 0x62, 0xea, 0x6f, 0x6a, 0xce, 0x15,
	0x3c, 0xf8, 0x08, 0xde, 0x30, 0x4b, 0x63, 0xa6, 0x1f, 0xf8, 0x00, 0x76, 0xee, 0xdc, 0x8d, 0x27,
	0x5f, 0xcd, 0x48, 0xe2, 0x5e, 0x7a, 0x19, 0x46, 0xbf, 0x80, 0x4f, 0x94, 0xa8, 0x13, 0xce, 0x33,
	0xae, 0xe4, 0x60, 0x2a, 0x67, 0x3c, 0xa5, 0xb1, 0x3d, 0x65, 0xac, 0xfd, 0x6f, 0x2c, 0xc1, 0x7b,
	0xe8, 0xe2, 0x6c, 0x26, 0x59, 0x3a, 0xc6, 0xb3, 0x84, 0x0a, 0xf4, 0x7d, 0x68, 0x73, 0xab, 0x98,
	0xbe, 0xb4, 0x73, 0xe8, 0x85, 0x4e, 0x53, 0x9c, 0x6f, 0xa1, 0x03, 0xf0, 0x22, 0xa7, 0xaf, 0xbe,
	0xa6, 0x73, 0x08, 0x61, 0x6e, 0x01, 0x5e, 0x6c, 0x06, 0xff, 0xaa, 0x41, 0xef, 0x1d, 0xbd, 0x16,
	0x4c, 0xd2, 0x72, 0x18, 0x3d, 0x87, 0x2d, 0x96, 0xc6, 0xf4, 0xfe, 0x38, 0x8b, 0x66, 0x13, 0x9a,
	0x4a, 0x6b, 0x63, 0x19, 0x54, 0x5c, 0x54, 0xa9, 0x9e, 0x73, 0x19, 0x9b, 0xca, 0x20, 0x1a, 0xc1,
	0x63, 0x5e, 0x15, 0x5c, 0xda, 0x8f, 0x9d, 0xc3, 0x7e, 0x58, 0x19, 0x7a, 0xb8, 0xfa, 0x10, 0xfa,
	0x11, 0x74, 0x79, 0xe1, 0x4d, 0x74, 0x86, 0x77, 0x0e, 0xb7, 0xc2, 0xe2, 0x43, 0xe1, 0x12, 0x4b,
	0xf0, 0xef, 0x1a, 0x3c, 0x1c, 0x9e, 0xe3, 0xcb, 0xb2, 0x89, 0xdb, 0xb0, 0xc1, 0x5c, 0xd1, 0xd9,
	0x60, 0xb1, 0x8a, 0x1c, 0x92, 0x24, 0xd9, 0x47, 0x1a, 0x9f, 0x51, 0x79, 0x9b, 0xc5, 0xce, 0x43,
	0x4b, 0x68, 0x81, 0xef, 0x9c, 0xb3, 0x31, 0x4b, 0x85, 0x8d, 0xc7, 0x25, 0xb4, 0xc0, 0xf7, 0x4b,
	0x4a, 0x62, 0xca, 0x85, 0x8b, 0xc4, 0x32, 0xaa, 0x1e, 0x71, 0x42, 0xee, 0x07, 0x63, 0x7a, 0x49,
	0x95, 0x63, 0x84, 0x0d, 0xc3, 0x32, 0xa8, 0xa4, 0xd1, 0xfb, 0x69, 0x26, 0x16, 0xd2, 0x9a, 0x46,
	0x5a, 0x19, 0x0d, 0x4e, 0xa1, 0x73, 0x4c, 0x85, 0x64, 0x69, 0x5e, 0x0e, 0xae, 0x67, 0xd1, 0x1d,
	0x75, 0x0e, 0xb4, 0x14, 0x0a, 0xa0, 0x2b, 0x64, 0xc6, 0xc9, 0x98, 0x0e, 0x13, 0x22, 0x9c, 0xa9,
	0x25, 0x2c, 0xf8, 0x7d, 0x0d, 0x76, 0x30, 0x9d, 0x26, 0x2c, 0xd2, 0xb2, 0x70, 0x96, 0xd0, 0x95,
	0x47, 0xeb, 0x43, 0x73, 0xaa, 0x63, 0xde, 0x4a, 0xb0, 0x14, 0xf2, 0xa1, 0x45, 0x53, 0x72, 0x9d,
	0x50, 0x53, 0xdb, 0xda, 0xd8, 0x91, 0x28, 0x84, 0x4e, 0xbc, 0x50, 0x50, 0xbf, 0x49, 0xe7, 0xb0,
	0x1b, 0x16, 0x94, 0xc6, 0x45, 0x86, 0xe0, 0x2d, 0xf8, 0x05, 0x25, 0xca, 0x2e, 0x44, 0xd0, 0xe0,
	0x59, 0xe2, 0x2a, 0x93, 0x5e, 0xa3, 0x17, 0xb0, 0xc9, 0x75, 0x60, 0x6c, 0xe8, 0xc0, 0xd8, 0x0d,
	0x97, 0x4c, 0xc0, 0x66, 0x3b, 0xf8, 0x0c, 0xea, 0x57, 0x64, 0x8c, 0x76, 0xa1, 0x7e, 0x47, 0xe7,
	0x56, 0x82, 0x5a, 0x2a, 0xe4, 0x03, 0x49, 0xac, 0x3d, 0x6a, 0x19, 0x0c, 0x61, 0x67, 0xc4, 0x6e,
	0x68, 0x34, 0x8f, 0x12, 0xfa, 0x92, 0x25, 0x92, 0xf2, 0x82, 0xdd, 0xb5, 0x25, 0xbb, 0x1b, 0x92,
	0x8c, 0xdd, 0xe5, 0x8d, 0xf0, 0x8a, 0x8c, 0xb1, 0x46, 0x02, 0x0c, 0xcd, 0x41, 0xe4, 0xb4, 0x4e,
	0x17, 0xf5, 0x54, 0xaf, 0xd5, 0xa5, 0x31, 0x99, 0xbb, 0x4b, 0x63, 0x32, 0x57, 0x1e, 0x8a, 0x75,
	0x71, 0x3e, 0x23, 0xfc, 0x8e, 0x72, 0x1b, 0x3c, 0x25, 0x2c, 0xf8, 0x43, 0x0d, 0xb6, 0x72, 0xcd,
	0xd6, 0xf9, 0x47, 0x98, 0x76, 0x60, 0xfd, 0x63, 0x28, 0x74, 0x00, 0xcd, 0x1b, 0x6d, 0x89, 0x4d,
	0xc2, 0xdd, 0x70, 0xc9, 0x42, 0x6c, 0xf7, 0xd1, 0xa7, 0xd0, 0x22, 0x5a, 0x6f, 0x97, 0x6a, 0xad,
	0xd0, 0xd8, 0x81, 0x1d, 0x1e, 0x8c, 0x4b, 0x71, 0x72, 0x9a, 0xde, 0x64, 0x85, 0x7b, 0x6b, 0xa5,
	0x7b, 0x7d, 0x68, 0x5d, 0x93, 0xe8, 0x8e, 0xa6, 0xb1, 0x55, 0xc8, 0x91, 0x2b, 0x11, 0x59, 0xaf,
	0x88, 0xc8, 0xbf, 0x6d, 0x42, 0xf3, 0x0b, 0x13, 0xc0, 0x55, 0x8f, 0xd8, 0x83, 0xcd, 0xec, 0x63,
	0x4a, 0xb9, 0x15, 0x6d, 0x08, 0x55, 0xe9, 0xf5, 0xe2, 0x98, 0x89, 0x69, 0x42, 0xe6, 0xba, 0xd3,
	0x18, 0xe1, 0x2b, 0x38, 0xea, 0x43, 0x9d, 0x44, 0x89, 0x0d, 0xca, 0x46, 0x38, 0x18, 0x8e, 0xb0,
	0x02, 0x94, 0x72, 0x11, 0xa7, 0xda, 0xbc, 0x63, 0x22, 0x4d, 0xa7, 0xa8, 0xe3, 0x12, 0xa6, 0x3a,
	0xac, 0xe4, 0x24, 0x15, 0x4c, 0x15, 0xc2, 0xa6, 0x0e, 0xfa, 0x05, 0xa0, 0x0c, 0x37, 0xae, 0x8b,
	0xfd, 0x96, 0x49, 0x08, 0x4b, 0xa2, 0x53, 0xe8, 0x89, 0x8a, 0x11, 0xc3, 0x6f, 0x6b, 0x25, 0x1e,
	0x87, 0x55, 0xf3, 0x07, 0xae, 0x3c, 0x82, 0x30, 0x3c, 0xf9, 0x50, 0x3d, 0x17, 0xf8, 0x9e, 0x96,
	0xe6, 0x87, 0x6b, 0xe6, 0x06, 0xbc, 0xee, 0x60, 0xd1, 0x63, 0x50, 0xf6, 0xd8, 0x29, 0xf4, 0x3e,
	0x56, 0xf4, 0x0e, 0xbf, 0x63, 0x15, 0xaf, 0x6a, 0x2c, 0xb8, 0xf2, 0x08, 0x7a, 0x01, 0x8d, 0x28,
	0xe3, 0xc2, 0xef, 0xea, 0xa3, 0x28, 0x5c, 0xa9, 0xd6, 0x58, 0xef, 0xa3, 0x37, 0xe0, 0xf3, 0x35,
	0xc5, 0xc0, 0xdf, 0xd2, 0x67, 0x9f, 0x86, 0xeb, 0xaa, 0x05, 0x5e, 0x7b, 0x14, 0xbd, 0x84, 0x7e,
	0xe2, 0xc2, 0xbf, 0x2c, 0x74, 0x5b, 0x87, 0xfc, 0x76, 0x58, 0xca, 0x32, 0xbc, 0x86, 0x3b, 0xf8,
	0x63, 0x0d, 0x5a, 0x17, 0x84, 0x6b, 0x99, 0xab, 0x85, 0xe5, 0xbb, 0x00, 0x53, 0xc2, 0xe5, 0xeb,
	0xd9, 0xe4, 0x3a, 0x8f, 0xd1, 0x02, 0xa2, 0x42, 0x5a, 0xb0, 0xdf, 0x99, 0xe0, 0xac, 0x63, 0xbd,
	0x56, 0x18, 0x95, 0x64, 0x6c, 0xb3, 0x5f, 0xaf, 0x55, 0x30, 0x26, 0x44, 0xc8, 0xb3, 0x2c, 0x66,
	0x37, 0x8c, 0xc6, 0x2e, 0x18, 0x8b, 0x58, 0xf0, 0xa7, 0x1a, 0xb4, 0xac, 0xab, 0x55, 0x60, 0x3a,
	0xe7, 0xba, 0xd2, 0xb0, 0x00, 0xf2, 0x1b, 0x36, 0x0a, 0x37, 0xec, 0x41, 0x9b, 0x89, 0x11, 0x91,
	0x54, 0x48, 0x9b, 0x2a, 0x39, 0xbd, 0x72, 0x7b, 0x63, 0xf5, 0xf6, 0xdc, 0x92, 0xcd, 0x85, 0x25,
	0xc1, 0x3f, 0x5a, 0xd0, 0x3c, 0xbf, 0xfe, 0xad, 0x9a, 0x4f, 0xf6, 0xc1, 0xcb, 0xf4, 0xea, 0x55,
	0xfe, 0x40, 0x0b, 0x40, 0x3d, 0x93, 0x69, 0x52, 0x85, 0x99, 0xb0, 0x80, 0x2c, 0xb2, 0xbc, 0xfe,
	0x75, 0x59, 0xde, 0x58, 0x93, 0xe5, 0x2a, 0x9b, 0x49, 0x74, 0xab, 0x9c, 0x27, 0x79, 0x96, 0xd8,
	0x86, 0x5b, 0xc2, 0x50, 0x08, 0x28, 0xca, 0x52, 0x49, 0x53, 0xa9, 0x4e, 0x66, 0xc2, 0x0c, 0x53,
	0xa6, 0xe7, 0x56, 0xec, 0xa8, 0xb1, 0xd0, 0xa2, 0x27, 0x69, 0x94, 0xc5, 0x2c, 0x1d, 0xeb, 0x3c,
	0xf7, 0xf0, 0x32, 0xac, 0x5b, 0xe3, 0xfd, 0x94, 0x71, 0x2a, 0x74, 0x8a, 0x7b, 0xd8, 0x91, 0x6a,
	0x12, 0xb0, 0xcc, 0x23, 0x9a, 0x8e, 0xe5, 0xad, 0x4e, 0x5a, 0x0f, 0x97, 0x41, 0xfd, 0xd7, 0xc3,
	0x00, 0x57, 0xf3, 0x29, 0xb5, 0x49, 0x59, 0x84, 0xd4, 0x0b, 0x5a, 0xf2, 0x2c, 0xfe, 0xb1, 0x4e,
	0x47, 0x0f, 0x17, 0x10, 0xf4, 0x1c, 0xda, 0xd6, 0xff, 0x2a, 0xe3, 0x54, 0x80, 0xb7, 0x5d, 0x5d,
	0xc0, 0xf9, 0xce, 0x4a, 0x41, 0xde, 0x5a, 0x2d, 0xc8, 0x6b, 0x6b, 0xd7, 0xf6, 0x37, 0xaf, 0x5d,
	0x9f, 0xc3, 0x13, 0x5b, 0x1a, 0xdc, 0x38, 0x38, 0xca, 0x4c, 0xae, 0xfa, 0x3b, 0xfa, 0xe6, 0x75,
	0xdb, 0xae, 0x68, 0xef, 0x2e, 0x17, 0xed, 0x42, 0xe5, 0x7a, 0x58, 0xae, 0x5c, 0x7d, 0x68, 0x32,
	0xf1, 0x7a, 0x96, 0x24, 0x3e, 0x32, 0xdd, 0xc9, 0x50, 0x6a, 0xc8, 0x62, 0xe2, 0xb8, 0xd8, 0x75,
	0x1f, 0x99, 0x21, 0xab, 0x8c, 0xa2, 0x9f, 0xc2, 0x0e, 0x2f, 0x37, 0x3c, 0xbf, 0xb7, 0x3a, 0x6d,
	0x28, 0x1c, 0x2f, 0x33, 0xe6, 0xb9, 0xf1, 0xb8, 0x90, 0xe5, 0xcf, 0xa1, 0x3d, 0x35, 0x65, 0x43,
	0xf8, 0x7d, 0xeb, 0x10, 0x5b, 0x47, 0x70, 0xbe, 0x93, 0xcf, 0x16, 0x4f, 0x96, 0x67, 0x8b, 0x95,
	0x9c, 0xf4, 0x8d, 0xab, 0x4a, 0x39, 0xa9, 0x72, 0x3a, 0x65, 0xf2, 0x65, 0x42, 0xc6, 0xfe, 0x53,
	0x9b, 0xd3, 0x96, 0x56, 0x3a, 0x9d, 0x5c, 0x91, 0xb1, 0xbf, 0x67, 0x6a, 0x80, 0x5a, 0x07, 0x9f,
	0xc3, 0xa3, 0x11, 0x13, 0xd2, 0xb4, 0x5b, 0x81, 0xa9, 0x98, 0x66, 0xa9, 0xa0, 0x6a, 0x1c, 0x30,
	0xb9, 0xa8, 0x3a, 0xbb, 0x19, 0x07, 0x0c, 0x0b, 0x76, 0x78, 0xf0, 0x33, 0xe8, 0x7e, 0x41, 0x04,
	0xcd, 0x8f, 0xec, 0x83, 0x47, 0xdd, 0x1f, 0x1c, 0x97, 0xee, 0x39, 0xa0, 0xea, 0xe4, 0x44, 0xb8,
	0xf2, 0xa3, 0x96, 0xc1, 0x77, 0xa0, 0x63, 0xce, 0xeb, 0x99, 0x7f, 0x79, 0xa4, 0x09, 0x7e, 0x03,
	0x48, 0x29, 0x66, 0x6a, 0x89, 0x70, 0x5c, 0x7d, 0x37, 0x19, 0xb8, 0x81, 0xc3, 0xce, 0x09, 0xfb,
	0xe0, 0x1d, 0xd3, 0x84, 0x4d, 0x98, 0xcc, 0x6b, 0xee, 0x02, 0x50, 0xb5, 0xe4, 0xbc, 0x58, 0x4b,
	0x34, 0x11, 0xfc, 0xbc, 0x78, 0x43, 0x6e, 0xc6, 0x67, 0xd0, 0x29, 0xdc, 0x9b, 0x5b, 0x6f, 0xb9,
	0x8a, 0x7b, 0xc1, 0xaf, 0xe1, 0xa1, 0x89, 0x17, 0x03, 0x9c, 0xa6, 0xd3, 0xd9, 0x7a, 0x0d, 0x77,
	0xa1, 0xae, 0xea, 0xa0, 0x7d, 0x00, 0x55, 0x01, 0xf7, 0xc1, 0x7b, 0x9b, 0x17, 0x6c, 0xa3, 0xd9,
	0x02, 0x08, 0x7e, 0x05, 0xdb, 0x5f, 0x52, 0xf9, 0x6d, 0x48, 0x7e, 0x07, 0x3b, 0x67, 0xb3, 0x44,
	0x32, 0x15, 0x71, 0x6f, 0xa6, 0x49, 0x46, 0xe2, 0x6f, 0x20, 0x7a, 0x0f, 0xda, 0x33, 0x7d, 0x26,
	0xff, 0x9c, 0x91, 0xd3, 0xc1, 0x5f, 0x6a, 0xe0, 0xa9, 0xf7, 0x51, 0x31, 0x2d, 0xfe, 0x3f, 0x32,
	0xd5, 0xde, 0x19, 0xb9, 0xd7, 0x12, 0x6d, 0x0f, 0xca, 0x69, 0xd5, 0x0c, 0x2e, 0xf2, 0xbe, 0x6a,
	0x33, 0xd9, 0xf4, 0xa2, 0x15, 0xfc, 0xf0, 0xaf, 0x75, 0xd8, 0xb8, 0x3c, 0x42, 0x47, 0xc6, 0xbb,
	0x36, 0xdc, 0x51, 0x37, 0x2c, 0x84, 0xe0, 0x5e, 0x2f, 0xac, 0x48, 0x85, 0xe0, 0x01, 0x3a, 0x80,
	0xee, 0x50, 0x8d, 0x80, 0xd4, 0x5a, 0xe0, 0x72, 0x61, 0x6f, 0x2b, 0x2c, 0x66, 0x80, 0xe1, 0x34,
	0x11, 0xf1, 0xb5, 0x9c, 0xdf, 0x03, 0xef, 0x4b, 0x2a, 0x97, 0xd9, 0xdc, 0x22, 0x78, 0x80, 0x7e,
	0x52, 0x8a, 0x43, 0xf4, 0x28, 0x5c, 0xcd, 0x86, 0xbd, 0x22, 0x58, 0xa5, 0xaf, 0x6d, 0xc4, 0x2e,
	0x7a, 0x2b, 0xf5, 0x7d, 0x33, 0x8d, 0xff, 0x17, 0xce, 0x1f, 0x68, 0x7d, 0x2d, 0xdb, 0x4e, 0x58,
	0x0e, 0xcd, 0x3d, 0x77, 0x2e, 0x78, 0x80, 0x8e, 0xdc, 0x13, 0x58, 0x5e, 0x14, 0xae, 0xe4, 0xc8,
	0x8a, 0xf4, 0xeb, 0xa6, 0xfe, 0x50, 0x74, 0xf4, 0x9f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x76, 0xb7,
	0x06, 0x7c, 0x38, 0x14, 0x00, 0x00,
}

/* Example implementation of S3 service :

package your_package // TODO change to your project package name

import "github.com/golang/protobuf/proto"
import pb "s3" // TODO change to the Go package in which your .pb.go has been generated

// TODO change packagePath value to match your package full import path
//go:generate goprotopy --packagePath=your_org/your_name/your_package $GOFILE

// input is a serialized protobuf object of type BaseRequest
// output is a serialized protobuf object of type ListBucketsResponse
// @protopy
func ListBuckets(input []byte) (output []byte, err error) {
    baseRequest := new(pb.BaseRequest)
    err = proto.Unmarshal(input, baseRequest)
    if err != nil {
        return
    }

    // TODO : implement ListBuckets(baseRequest *pb.BaseRequest) (*pb.ListBucketsResponse, error)
    // listBucketsResponse, err := yourListBucketsImplementation(baseRequest)

    listBucketsResponse := new(pb.ListBucketsResponse)
    output, err = proto.Marshal(listBucketsResponse)
    return
}

// input is a serialized protobuf object of type Bucket
// output is a serialized protobuf object of type BaseResponse
// @protopy
func CreateBucket(input []byte) (output []byte, err error) {
    bucket := new(pb.Bucket)
    err = proto.Unmarshal(input, bucket)
    if err != nil {
        return
    }

    // TODO : implement CreateBucket(bucket *pb.Bucket) (*pb.BaseResponse, error)
    // baseResponse, err := yourCreateBucketImplementation(bucket)

    baseResponse := new(pb.BaseResponse)
    output, err = proto.Marshal(baseResponse)
    return
}

// input is a serialized protobuf object of type Bucket
// output is a serialized protobuf object of type BaseResponse
// @protopy
func DeleteBucket(input []byte) (output []byte, err error) {
    bucket := new(pb.Bucket)
    err = proto.Unmarshal(input, bucket)
    if err != nil {
        return
    }

    // TODO : implement DeleteBucket(bucket *pb.Bucket) (*pb.BaseResponse, error)
    // baseResponse, err := yourDeleteBucketImplementation(bucket)

    baseResponse := new(pb.BaseResponse)
    output, err = proto.Marshal(baseResponse)
    return
}

// input is a serialized protobuf object of type Bucket
// output is a serialized protobuf object of type Bucket
// @protopy
func GetBucket(input []byte) (output []byte, err error) {
    bucket := new(pb.Bucket)
    err = proto.Unmarshal(input, bucket)
    if err != nil {
        return
    }

    // TODO : implement GetBucket(bucket *pb.Bucket) (*pb.Bucket, error)
    // bucket, err := yourGetBucketImplementation(bucket)

    bucket := new(pb.Bucket)
    output, err = proto.Marshal(bucket)
    return
}

// input is a serialized protobuf object of type ListObjectsRequest
// output is a serialized protobuf object of type ListObjectResponse
// @protopy
func ListObjects(input []byte) (output []byte, err error) {
    listObjectsRequest := new(pb.ListObjectsRequest)
    err = proto.Unmarshal(input, listObjectsRequest)
    if err != nil {
        return
    }

    // TODO : implement ListObjects(listObjectsRequest *pb.ListObjectsRequest) (*pb.ListObjectResponse, error)
    // listObjectResponse, err := yourListObjectsImplementation(listObjectsRequest)

    listObjectResponse := new(pb.ListObjectResponse)
    output, err = proto.Marshal(listObjectResponse)
    return
}

// input is a serialized protobuf object of type Object
// output is a serialized protobuf object of type BaseResponse
// @protopy
func CreateObject(input []byte) (output []byte, err error) {
    object := new(pb.Object)
    err = proto.Unmarshal(input, object)
    if err != nil {
        return
    }

    // TODO : implement CreateObject(object *pb.Object) (*pb.BaseResponse, error)
    // baseResponse, err := yourCreateObjectImplementation(object)

    baseResponse := new(pb.BaseResponse)
    output, err = proto.Marshal(baseResponse)
    return
}

// input is a serialized protobuf object of type Object
// output is a serialized protobuf object of type BaseResponse
// @protopy
func UpdateObject(input []byte) (output []byte, err error) {
    object := new(pb.Object)
    err = proto.Unmarshal(input, object)
    if err != nil {
        return
    }

    // TODO : implement UpdateObject(object *pb.Object) (*pb.BaseResponse, error)
    // baseResponse, err := yourUpdateObjectImplementation(object)

    baseResponse := new(pb.BaseResponse)
    output, err = proto.Marshal(baseResponse)
    return
}

// input is a serialized protobuf object of type GetObjectInput
// output is a serialized protobuf object of type Object
// @protopy
func GetObject(input []byte) (output []byte, err error) {
    getObjectInput := new(pb.GetObjectInput)
    err = proto.Unmarshal(input, getObjectInput)
    if err != nil {
        return
    }

    // TODO : implement GetObject(getObjectInput *pb.GetObjectInput) (*pb.Object, error)
    // object, err := yourGetObjectImplementation(getObjectInput)

    object := new(pb.Object)
    output, err = proto.Marshal(object)
    return
}

// input is a serialized protobuf object of type DeleteObjectInput
// output is a serialized protobuf object of type BaseResponse
// @protopy
func DeleteObject(input []byte) (output []byte, err error) {
    deleteObjectInput := new(pb.DeleteObjectInput)
    err = proto.Unmarshal(input, deleteObjectInput)
    if err != nil {
        return
    }

    // TODO : implement DeleteObject(deleteObjectInput *pb.DeleteObjectInput) (*pb.BaseResponse, error)
    // baseResponse, err := yourDeleteObjectImplementation(deleteObjectInput)

    baseResponse := new(pb.BaseResponse)
    output, err = proto.Marshal(baseResponse)
    return
}

*/
